### ISSUE TITLE
Show bond card for bespoke durations

### ISSUE THREAD

**Issue by steveliupai** [osmosis-labs/osmosis-frontend#1003]
Hi, someone encounter such situation that he bonded LAMB/OSMOS(poolid:826) LP for 7day and the pool expired. He could unbond his LP in last frontend version and he couldn't find anywhere to unbond his 7days LP in new version.

**Comment by jonator** [comment]
Hi. This is a bug I need to fix. I should provide the card with the unbond option if users have tokens bonded there.
