### ISSUE TITLE
Non-localized stablecoin type

### ISSUE THREAD

**Issue by iam-agf** [osmosis-labs/osmosis-frontend#1011]
When you add **one** asset for liquidity to a pool that involves a stable coin, the last word is called from the variable `{mechanism}`, forcing it to be in English. 

<img width="612" alt="image" src="https://user-images.githubusercontent.com/61362029/202033056-460f1912-d5f2-49de-835c-419d8ce72130.png">

In a same LP view, you can notice the word "Unbounded" isn't affected by the translation.
<img width="1124" alt="image" src="https://user-images.githubusercontent.com/61362029/202034251-6934b1dd-2809-4805-9dd7-060f89a75715.png">

Also when you go to a LP and Bond Liquidity, there are words that aren't translated.
<img width="713" alt="image" src="https://user-images.githubusercontent.com/61362029/202034058-0c15ad25-70b1-4a6f-889b-f2f092e34c2d.png">

**Comment by jonator** [comment]
The collateral type should instead be used as a key into the respective localization json file

**Comment by iam-agf** [comment]
I guess the issue continue but now in another format.

<img width="603" alt="image" src="https://user-images.githubusercontent.com/61362029/204474469-4488c358-b40d-4e4b-9dda-03f9ae375654.png">
