### ISSUE TITLE
Optimize pool query

### ISSUE THREAD

**Issue by jonator** [osmosis-labs/osmosis-frontend#1015]
### Problem
Our current performance bottleneck on the frontend is currently the [pools](https://lcd-osmosis.keplr.app/osmosis/gamm/v1beta1/pools?pagination.limit=1000) query. If the node is slow to respond, the UI appears bricked, responsive but void of data as it's our primary data dependency. Additionally, the newly-arrived 800+ pools then have to be processed reactively by mobx, firing off 1000s of computedFns and @computed getters, causing lag.

#### Primary
Sometime shortly after v13, @mattverse and others should have released a pools query with parameters for liquidity. Initially, we should only fetch the top ~120 pools by liquidity. Our swap router filters the pools to about 120 based on liquidity already. Then, we should add logic to show more pagination pages or initiate a full query later as the user searches in the pools table, selects "All pools", and/or paginates right.

#### Secondary
Look into using Next.js server side rendering to fetch and possibly minimize pools data from the node every few minutes. Ideally, we should find a way to have the pools data immediately available to the render function so we can SSR tables/cards with data as well. Then, on the client, we'd need to add a hydration mechanism to take the pools data from the NextPage props and fill the store pre-render, thus preventing another pools fetch. See [old issue that Tony advised against implementing](https://github.com/osmosis-labs/osmosis-frontend/issues/359), and [commit](https://github.com/osmosis-labs/osmosis-frontend/commit/2560af7f748a520980e5c562b32e86fe9906e47c) where I reverted my attempt.

**Comment by daniel-farina** [comment]
A simple example of what a difference this would make: 

<img width="1679" alt="image" src="https://user-images.githubusercontent.com/13665117/202295159-fe7ec842-9fce-4820-b22c-26a8389366ef.png">

**Comment by jonator** [comment]
Currently blocked since there's no support for encoding a list of coins in a query param for protobuf.
