### ISSUE TITLE
Automate Token Pricing

### ISSUE THREAD

**Issue by JeremyParish69** [osmosis-labs/osmosis-frontend#1016]
### Problem
**Token Asset Pricing currently requires an explicit manual effort which could be eliminated.**

The current token listing process is fragmented between a few different files (e.g., ibc-assets.ts, chain-infos.ts, prices.ts, images/tokens/, etc.). In addition, some users or teams prefer to use the Osmosis frontend to add liquidity, which may require that the token listing process requires multiple rounds (one for adding the (chain and) token details, and another for defining the pricing for the token).

The Osmosis Frontend currently uses two ways different way to get the price of a token. In some cases, the token's price can be determined by sending an Id to CoinGecko's API, which can be specified in the Chain-infos.ts file; while in other cases, the price can be derived by looking at the Osmosis-local exchange rate between a token and another token with known price, which is defined in the prices.ts file.

### Solution
With a clear algorithm and sufficient liquidity of the new token in a set of pools that can ultimately be swapped for OSMO, we could automate the process of defining this manually. This would reduce the extra round required to complete a token listing, eliminate the need for a prices.ts file, provide higher quality and adaptable prices, and reduce the number of calls to external APIs (e.g., CoinGecko).

As an additional benefit, this could also be used to service the function determining Osmosis gas fees in the form of tokens that aren't OSMO (because that fee payment really gets swapped to OSMO in the backend).

**Comment by jonator** [comment]
Closing since it's an idea in ClickUp. Can reopen if pursued.
