### ISSUE TITLE
Menu bar stays after pages load between screens on mobile

### ISSUE THREAD

**Issue by arispech** [osmosis-labs/osmosis-frontend#1031]
After opening the swap, assets and pools page, it require users to click away(somewhere on the screen) to make the menu sidebar pop-up disappear. and it will stay as users start to scroll down without tapping on the screen first time

<img width="300" alt="Screen Shot 2022-11-21 at 2 45 50 PM" src="https://user-images.githubusercontent.com/56182049/203145470-94bb28a8-5463-4eb7-ab9e-3ee475620fee.png">
<img width="300" alt="Screen Shot 2022-11-21 at 2 46 07 PM" src="https://user-images.githubusercontent.com/56182049/203145589-6410c121-93db-486b-8939-7ff19e784a4d.png">
<img width="300" alt="Screen Shot 2022-11-21 at 2 46 30 PM" src="https://user-images.githubusercontent.com/56182049/203145615-34537b1b-a6e4-4ca2-8f04-0be9374272f9.png">

**Comment by arispech** [comment]
@JoseRFelix 

There is another issue with the dropdown on mobile. You are unable to disconnect the Kepler wallet after clicking on the dropdown because it hides the menu right away instead of disconnecting the wallet so it becomes unclickable. 

Please let me know if you have any questions.

**Comment by JoseRFelix** [comment]
Thanks for the report. I will take a look!
