### ISSUE TITLE
IXO missing from Assets

### ISSUE THREAD

**Issue by alwyn-ixo** [osmosis-labs/osmosis-frontend#1054]
#### System information

Osmosis version: [`Osmosis version`](https://app.osmosis.zone/assets)
OS & Version: OSX
Commit hash: N/A

#### Expected behaviour
When a user searches for the IXO token they should find it.

#### Actual behaviour
IXO token can no longer be found when searching for it.
The IXO/OSMO and IXO/ATOM pools are still available.

#### Steps to reproduce the behaviour
Search for the IXO token on the Assets screen or any other screen where search is possible.

#### Backtrace

````
[backtrace]
````

When submitting logs: please submit them as text and not screenshots.

**Comment by JeremyParish69** [comment]
It was removed from Main site yesterday: https://github.com/osmosis-labs/osmosis-frontend/pull/1049
Can still be found on Frontier.

**Comment by alwyn-ixo** [comment]
@JeremyParish69 Can you provide more information, please?
How do we reinstate IXO on the Main site?

**Comment by JeremyParish69** [comment]
@alwyn-ixo Main site tokens require Osmosis Governance approval of the token. Either, Osmosis Governance can vote to incentivize a pool containing the token, or Osmosis governance can vote to add the token to the Main site (without incentivizing any of its pools), which would just be a text proposal.
