### ISSUE TITLE
Pools Tabs shouldn't stay in 0.

### ISSUE THREAD

**Issue by iam-agf** [osmosis-labs/osmosis-frontend#1057]
To replicate the error make:

1) External Incentives pools 
2) Search "huahua". This will let an empty list of pools.
3) Click on any of the side arrows.

<img width="1153" alt="image" src="https://user-images.githubusercontent.com/61362029/204049253-14d12e41-9597-41a2-8604-a94b7b124717.png">

4) Delete the searched string ( in this case "huahua")
5) Now you're in the tab 0/4

<img width="1153" alt="image" src="https://user-images.githubusercontent.com/61362029/204049408-5ee57d38-21df-4e62-9734-7877bd9d1d02.png">

This can be solved by keeping updated the tab number to 0 or 1 depending on if at least 1 pool exists.

**Comment by jonator** [comment]
Hoping for this to be deleted entirely with completion of #1175
