### ISSUE TITLE
Clean up old gauges

### ISSUE THREAD

**Issue by daniel-farina** [osmosis-labs/osmosis-frontend#1073]
There are many expired gauges that are kept in the frontend's source code that should be removed, fo example: 

For example: 
https://github.com/osmosis-labs/osmosis-frontend/blob/d21075d2c96b890870235d783e0abbf836746431/packages/web/config/feature-flag.ts#L67

I also think we should start adding comments to a gauge when it's added with meta information such as expiration and token denom. (As a comment for example).

**Comment by jonator** [comment]
Would be ideal to remove this config all together by implementing issue #853

**Comment by jonator** [comment]
Config removed by PR #1190
