### ISSUE TITLE
Add support for testnet IBC transactions. 

### ISSUE THREAD

**Issue by daniel-farina** [osmosis-labs/osmosis-frontend#1074]
Based on the recent work from Nico and Dilan, we would like to add support for IBC transfer on the testnet with other testnets.  The following are some of the items we would like to track for this work. 

- [ ] Document hermes setup
- [ ] Document updates needed on the front-end
- [ ] Look into possibly updating `/packages/web/config/ibc-assets.ts` to automatically support IS_TESTNET channels.
- [ ] Update asset info page and break it down into mainet and testnet https://docs.osmosis.zone/osmosis-core/asset-info/  (this references https://raw.githubusercontent.com/osmosis-labs/assetlists/main/osmosis-1/osmosis-1.assetlist.json)

**Comment by jonator** [comment]
On the ibc-assets.ts config, we'd use the `IS_TESTNET` toggle to set the testnet channel IDs:
```
{
    counterpartyChainId: IS_TESTNET
      ? "axelar-testnet-lisbon-3"
      : "axelar-dojo-1",
    sourceChannelId: IS_TESTNET ? "channel-312" : "channel-208",
    destChannelId: IS_TESTNET ? "channel-22" : "channel-3",
    coinMinimalDenom: "weth-wei",
    sourceChainNameOverride: IS_TESTNET ? "Goerli Ethereum" : "Ethereum",
    isVerified: true,
    originBridgeInfo: {
      bridge: "axelar" as const,
      wallets: ["metamask" as const, "walletconnect" as const],
      method: "deposit-address" as const,
      sourceChains: [AxelarSourceChainConfigs.weth.ethereum],
    },
  },
```

**Comment by jonator** [comment]
Closing in favor of tracking on ClickUp
