### ISSUE TITLE
Missing unbond button

### ISSUE THREAD

**Issue by artemFFtod** [osmosis-labs/osmosis-frontend#1077]
# Pool number 596 BOOT/ATOM missing unbond button

 There is no way to withdraw liquidity

<img width="841" alt="Снимок экрана 2022-11-30 в 13 10 31" src="https://user-images.githubusercontent.com/86662764/204757867-f3bf3d3f-7a29-4bf9-aec8-cd51784a3cfb.png">

**Comment by Cordtus** [comment]
Use https://legacy.osmosis.zone/pool/596 for now

**Comment by jonator** [comment]
@Cordtus I recently pushed an update to the app to address this, could you check and see if it works now?

**Comment by jonator** [comment]
Should be fixed
