### ISSUE TITLE
Reduce precision on external pool incentives

### ISSUE THREAD

**Issue by dylanschultzie** [osmosis-labs/osmosis-frontend#108]
If dust is added to external incentives, it appears that it shows up on the pools themselves. I imagine this isn't the ideal behavior; I ended up just adding more SCRT to even it out.

![Screen_Shot_2021-11-29_at_6 49 06_PM](https://user-images.githubusercontent.com/9121234/143977614-8625c838-5b27-4358-8ba6-c14197103e51.png)

**Comment by dogemos** [comment]
@delivan can we set it to no decimals? or would that be too complicated due to decimals?

**Comment by JeremyParish69** [comment]
IMO 6 decimal places of precision is preferred, even if it's .000000; could make the digits after the decimal a bit smaller to aid in readability.
<img width="302" alt="External Incentives Precision" src="https://user-images.githubusercontent.com/95667791/145094013-16495888-2777-47e5-be67-9a5f9e0757e3.png">

**Comment by dylanschultzie** [comment]
@JeremyParish69  I disagree, I think setting it to 0 decimals displayed makes more sense for external incentives. Why show that many decimals split over so many epochs? It doesn't add anything to the experience, but actively makes the UI noisier.

**Comment by delivan** [comment]
I think decimals on this UI can cause users misunderstand the actual bonus amount. Reducing its size is also a good solution but it's still likely to mislead users and I think decimals isn't important for total bonus amount. So I'm gonna change to no decimals soon.
