### ISSUE TITLE
Pool Volume always Displays as $0 unless Pool is Incentivized

### ISSUE THREAD

**Issue by JeremyParish69** [osmosis-labs/osmosis-frontend#1084]
As descived well in the title, Pool Volume always Displays as $0 unless Pool is Incentivized.

I've checked several pools, and I am confident that many of them actually do have >$0 volume, simply not being shown.

Note that Volume displays correctly when the incentive is only internal or only external.

Only Internal:
<img width="229" alt="image" src="https://user-images.githubusercontent.com/95667791/205165775-0f4a9a59-485b-4044-962a-2f16e49accdd.png">

Only External:
<img width="338" alt="image" src="https://user-images.githubusercontent.com/95667791/205165370-c1a36c01-a8e2-46be-a85d-de829d4f5193.png">

No incentives:
<img width="239" alt="image" src="https://user-images.githubusercontent.com/95667791/205165871-bc48a428-9009-4ce4-a250-d45bd990234d.png">

**Comment by jonator** [comment]
@IbrarMakaveli do incentives affect the return from Imperator data query?

**Comment by jonator** [comment]
It appears this is no longer an issue:

<img width="1109" alt="Screen Shot 2023-02-15 at 12 51 46 PM" src="https://user-images.githubusercontent.com/4606373/219124708-4ff2a284-4e45-4420-919e-8921fb570182.png">
