### ISSUE TITLE
🎄 Holiday Artwork: Wosmongton is coming to town 🎵

### ISSUE THREAD

**Issue by victortokaito** [osmosis-labs/osmosis-frontend#111]
Let's bring Wosmongton and friends to the app.osmosis.zone mainpage!

I think folks are gonna love these illustrations!

![Home-Xmas](https://user-images.githubusercontent.com/39136683/144328721-3c612926-b0c4-414a-a172-f872227f8873.png)

**Comment by dogemos** [comment]
closing because wosmongton is in town
