### ISSUE TITLE
Stylish scrollbars

### ISSUE THREAD

**Issue by chmichael** [osmosis-labs/osmosis-frontend#113]
Hello,
  I would be nice to replace the "windows"/native scrollbars with modern ones like:
  https://www.jqueryscript.net/blog/Best-Custom-Scroll-Bar-jQuery-Plugins.html

Thank you

**Comment by dogemos** [comment]
Agreed. Will see if there are any potential issues.

Should be good to go as long as it doesn't cause major issues.

**Comment by chmichael** [comment]
It will make the UI complete clean. Especially if you use the scrollbars which they hide when the mouse is not over the area. (Like windows 10)

**Comment by jonator** [comment]
I'm a fan of this, but only on windows if possible.
