### ISSUE TITLE
Query ICNS contracts

### ISSUE THREAD

**Issue by jonator** [osmosis-labs/osmosis-frontend#1141]
1. Ensure wallet is connected
2. Query ICNS contract with connected wallet's bech32 address
3. Display osmo name if there is one, the address otherwise

**Comment by jonator** [comment]
Questions:
* Should we create a new `icns` npm package to handle the osmo ICNS-related functionality? Or perhaps a broader `profile` package to handle NFT stuff in the future as well, and social stuff in the far future?

**Comment by dogemos** [comment]
Here is the initial API doc for reference. While it doesn't have documentation for exec messages, it should be enough for name/address resolution + reverse resolution.

https://github.com/icns-xyz/icns/pull/19
