### ISSUE TITLE
Match Design Guidelines and Headless Components 

### ISSUE THREAD

**Issue by JoseRFelix** [osmosis-labs/osmosis-frontend#1148]
## Problem

As the app grows we must start relying on design guidelines to maintain consistent styling and user experience. Further, components must be customizable, and accessible for screen readers and keyboard users.

## Proposed Solution

We must start creating components that adhere to our design guidelines and maintain accessibility throughout the app. Since we use Tailwind CSS, it makes sense to use headless components like [Headless UI](https://headlessui.com/) and [Radix](https://www.radix-ui.com/) that integrate beautifully and are accessible. Furthermore, following modern practices standardized by libraries like Material UI and Chakra UI, we'll use the library [CVA](https://github.com/joe-bell/cva) to build components with variants to avoid the arduous task of class matching. 

I've identified the following components that must be migrated/integrated:

### Button
- [x] General Component (#1157)
- [x] Icon Button ([inspiration](https://chakra-ui.com/docs/components/icon-button/usage)) (#1199)
### Popover
- [x] Topbar Settings (#1201)
- [x] Transaction Settings (#1201)
### Modal
- [ ] New Pool
- [ ] Deposit 
- [ ] Withdraw
- [ ] Connect Wallet
### Input
- [x] Search input (#1212)
### Select
- [ ] Deposit (Network select)
### Drawer
- [x] General Component (#1176)
- [ ] Token select
- [ ] Bond Card
### Icons
- [ ] Add Accessible [Icon Component](https://www.radix-ui.com/docs/primitives/utilities/accessible-icon)

**Comment by syed8rahman** [comment]
Adjust Swap settings to match Figma UI https://www.figma.com/file/om93lu8iXOhxwGHSUpAXEP/Trade-UI?node-id=93%3A1765&t=3ZhgpLpgcHzq2Pia-1
<img width="278" alt="Screen Shot 2022-12-16 at 11 55 56 AM" src="https://user-images.githubusercontent.com/22246254/208149434-4f043358-6320-4ca8-b5ea-fc04956316f2.png">

**Comment by jonator** [comment]
Closing in favor of tracking on ClickUp
