### ISSUE TITLE
Spacing Errors on Pool Descriptions Using Mobile

### ISSUE THREAD

**Issue by RoboMcGobo** [osmosis-labs/osmosis-frontend#115]
![image](https://user-images.githubusercontent.com/95544279/144720747-fd7b777b-0516-4ba9-8dbc-ec050d13fd45.png)

A space is missing here in the pool description. Seems to be mobile only. 

![image](https://user-images.githubusercontent.com/95544279/144720782-5b3e2317-adb7-470f-baaf-1775d0ccc6cf.png)

Desktop version for reference

**Comment by Thunnini** [comment]
Thank you!
