### ISSUE TITLE
Polish localisation - very unfortunate translation!

### ISSUE THREAD

**Issue by cryptonetD** [osmosis-labs/osmosis-frontend#1160]
in the polish (pl.json) localization the term "Unbond" has very wrong translation:

144:    "unbond": "Zwiąż",

this translation means exactly opposite to the orginal meaning. "Zwiąż" means in polish: Bond, not Unbond (that is why I was searching for unbonding feature for 3-4 minutes before I switched to english and noticed this bug

Correct wording for that should be:

144: "unbond": "Odwiąż", (means that You can untie something that is hanging from something or is attached to something) - preferred translation
or
144: "unbond": "Rozwiąż", (nearly the same meaning as above but has even better correlation to another polish wordings close to this subject) (this means that You can untie something what is tied: the rope for example)

You can substitute this word also with "Odwołaj" (Cancel) or "Wycofaj" (Withdraw)

Current wording is totally wrong, because it has opposite meaning to the desired one.

**Comment by jonator** [comment]
Thanks for pointing this out! Will be sure to address it.

**Comment by sehyunc** [comment]
@cryptonetD Does `"unbonding": "rozwiązywane"` also need to change?
