### ISSUE TITLE
Project: migrate queries from mobx to swr

### ISSUE THREAD

**Issue by jonator** [osmosis-labs/osmosis-frontend#1165]
### Problem
We currently ask a lot of MobX for querying all of our data from the chain and imperator. Particularly for pools, it results in a lot of chained dependent calculations once data loads, thus resulting in a degraded performance in less performant devices. Also, we import a lot of bloated typescript code (as base classes) from keplr-wallet to handle the logic of fetching from the chain. The code is over-optimized for working with multiple chains, whereas we only really work with Osmosis chain. Removing this dependency could result in much smaller bundle sizes (goal: <200kb).

### Proposed Solution
Refactor to use https://swr.vercel.app/ React hooks to fetch and cache data from the chain. This would increase our dependency on React, but may result in less renders and more caching/fetching handled for us. Further, it is natively supported in Next.js (it is a Vercel product). Likely, we'd create a series of use<X> hooks that deal with querying and computing on queried data. We'd define rich TypeScript types that would be returned from the hooks, and leverage `useMemo` to only compute on the queried data when needed. We'd then be able to remove a lot of bloat from our root store.

MobX will still be useful for coordinating UI Config from user input, but in the future we could use hooks to handle those as well, and remove our MobX dependency entirely.

Pros
* Reduce bundle sizes: remove keplr-wallet dependency, possibly MobX in far future
* Improve performance: remove memory-hunbry mobx stores from root store in context

Cons
* A lot of refactoring work is required as we have quite a few mobx stores. Should figure out how to memoize computation across app instead of per page wherever the queries are used since we are removing from the root store in the React context.

Input appreciated:
cc @Thunnini @delivan @sehyunc @JoseRFelix

**Comment by JoseRFelix** [comment]
I agree this is the correct way to have the best performance possible. Though, I suggest using [React Query](https://tanstack.com/query/v4) instead of SWR. SWR is constantly lagging behind React Query. Just recently they included dev tools and separate mutations hook; while RQ already had this for a long time.

**Comment by jonator** [comment]
From the #1171 PR, it seems the biggest performance bottleneck was the processing of too many pools. We should put such a drastic and high-investment refactor on hold for now as we seek other avenues of optimization, as I think there are more. I do, however, think we'd greatly benefit in a smaller initial bundle size, and such a refactor would be the only way we would achieve a sub 200kb main bundle size.
