### ISSUE TITLE
Warning to users about the Keplr-UST issues (Recommendation)

### ISSUE THREAD

**Issue by WorkerB33** [osmosis-labs/osmosis-frontend#117]
Just some type of heads up for new users about the UST situation and a recommendation to swap to Luna before they withdraw their UST to their Terra Keplr address

**Comment by dogemos** [comment]
Could the Osmosis Support DAO create a short blogpost providing a basic step-by-step guide on the two options?
1. Swap to Luna and withdraw
2. Use the same mnemonic on Keplr and Terra and use Terra Station to transfer UST

**Comment by WorkerB33** [comment]
Writing that blogpost up now

**Comment by victortokaito** [comment]
Thank you WorkerB33! And the Figma is up, the UI will link out to this post :)
