### ISSUE TITLE
stableswap pool doesn't load properly

### ISSUE THREAD

**Issue by hachi-27** [osmosis-labs/osmosis-frontend#1177]
When I try to visit the pools page on [osmosis app](https://app.osmosis.zone) like this [877 pool page](https://app.osmosis.zone/pool/877). If I want to swap tokens by clicking on the _**Trade Pair**_ button then there is:

- there is no option to choose which token I want to swap my token to/from?
- there are no visible icons there on the swap window. So it is practically impossible to know which token is being swapped into what.
- Also on [main page app](https://app.osmosis.zone/) I can't swap any of the stable swap pool tokens like USDC -> USDC.grv or USDT -> BUSD. I simply can't find any of those tokens to choose from.

This is what I am facing in my system so I felt it was my duty to report it. Let me know if I can provide any more details.
Thanks

**Comment by jonator** [comment]
Thanks. Have you tried frontier? I just fixed that issue on the development branch, and it was because those tokens aren't available on main app.

https://frontier.osmosis.zone/pool/877

**Comment by hachi-27** [comment]
alright thanks for the info
