### ISSUE TITLE
LP bonding transaction failing, gas wanted less than gas used, fails when I manually increase gas

### ISSUE THREAD

**Issue by TroySargent** [osmosis-labs/osmosis-frontend#12]
I am trying to bond LP tokens and get the following message when sending transaction type 'osmosis/lockup/lock-tokens' : "out of gas in location: WritePerByte; gasWanted: 1500000, gasUsed: 297259: out of gas"

I manually set the gas to 2500000 and the transaction failed again. Possible this issue is with IBC or Keplr wallet, but I would appreciate help troubleshooting. 

https://www.mintscan.io/osmosis/txs/385E220FEA5075FBC08578AFCB530D822A789DE8C573B34B70B0A52CDC6E0BC9

**Comment by ValarDragon** [comment]
Awesome, glad this worked after the gas bump on Monday!
