### ISSUE TITLE
Disappearing LP's pool

### ISSUE THREAD

**Issue by arispech** [osmosis-labs/osmosis-frontend#1225]
https://frontier.osmosis.zone/pool/888

After regular usage, Assets page fails to load a few pools. Notable new ones I've made, stable swap WETH.g:WETH & stableswap WBTC.g:WBTC.

Also notably pool WETH.g:WBTC.g also disappears. Interestingly the respective pairs with $ATOM do not (WETH.g:ATOM , WBTC.g:ATOM)

Clearing the cache restores these pools' appearance to the front-end and random triggers seem to pull them away. See screenshots of my home assets page before & after the cache clears to witness pools 're-appearing'

![image](https://user-images.githubusercontent.com/56182049/213203561-06ae3acc-bc35-4f71-8178-cdc08883b5d5.png)
![image](https://user-images.githubusercontent.com/56182049/213203721-cc9a407c-6f64-4bca-a566-cab5e92b30a7.png)

**Comment by jonator** [comment]
I think this would be an issue related to caching... we can reopen if we notice it again
