### ISSUE TITLE
Intermittent Front-End Display bug (swap tab & pools creation)

### ISSUE THREAD

**Issue by arispech** [osmosis-labs/osmosis-frontend#1226]
https://app.osmosis.zone/?from=ATOM&to=stATOM

User report:
Bug presents with specific assets like stATOM and WETH.g where the front-end bugs displaying the asset as another asset (For example stATOM=ATOM or WETH.g = WETH)

This mainly is a visual bug but conflicts with user flow (such as creating pools, for example I experienced this bug trying to make the WETH.g:WETH stable swap pool where it actually showed both assets as WETH. It was a front-end problem and underneath both assets were actually unique)
Hard to force, clearing cache seems to help. 

As seen in the images it shows ATOM, not stATOM 

![image](https://user-images.githubusercontent.com/56182049/213205593-335998d1-c793-455f-9054-d724d17820dc.png)
![image](https://user-images.githubusercontent.com/56182049/213205721-d378bddb-dcfa-461c-993b-8db6b410ab37.png)

**Comment by jonator** [comment]
I'm having trouble replicating this, even after clearing cache

**Comment by arispech** [comment]
Me too, trying to get this on a video but having a hard time getting one. However, there are constant reports coming in from multiple users and OSL : 
- Arc reporting in a screenshot on a successful example of "front-end" mismatch that's been happening ~
Observed is WETH.axl displayed as WETH.grv
![image](https://user-images.githubusercontent.com/56182049/214019730-809e9d3b-1428-4cc6-8794-33fd87f33c7c.png)

-
![image](https://user-images.githubusercontent.com/56182049/214021265-a83e82f7-0cc8-4889-ba95-d288c2b77256.png)

**Comment by JeremyParish69** [comment]
FYI, this issue is not resolved
