### ISSUE TITLE
Unable to swap stATOM form/to multiple tokens

### ISSUE THREAD

**Issue by arispech** [osmosis-labs/osmosis-frontend#1231]
As seen in the video the swap table shows the approximate amount swap to, when swap from ATOM and OSMO but not from USDC EVMOS STRD stOSMO for example

https://user-images.githubusercontent.com/56182049/213376278-753ce0cb-985c-463b-b983-a5340d412d05.mov

**Comment by jonator** [comment]
When we implement the optimized router, it should allow for this since our router doesn't route through more than 2 pools currently :(

**Comment by jonator** [comment]
This is due to our naive router implementation. Once we get a full router, this should be handled.
