### ISSUE TITLE
Need for Planned Deposit/Withdraw Outage Times

### ISSUE THREAD

**Issue by JeremyParish69** [osmosis-labs/osmosis-frontend#1232]
## Description

For the sake of appearing reliable, there is need to be able to pre-plan outage times for Token/Network Deposits and Withdrawals. A common example would be when Axelar undergoes an upgrade, and all bridging attempts from Osmosis, if permitted by the frontend, would fail for a few hours. These upgrades are at predicable times and block heights, with sufficient warning, so there is npo reason why can't plan for them.

We've historically had two methods to deal with this: either,
- mark all the tokens associated with that network as `isUnstable: true`, and _hope_ that the PR gets created, validated, and approved in time for the upgrade, and also make sure someone is around to merge precisely when the upgrade begins, and repeat for the completion of the upgrade, which is sometime not known ahead of time; or,
- do nothing, and allow users experience unexplained degraded performance, sullying their impression of Osmosis, Osmosis frontend, and/or Axelar.

## Requested Functionality

In the future, it would be ideal if we could pre-plan an outage, automatically disabling deposits/withdrawal for all tokens associated with the network at exactly when the upgrade is scheduled to begin, and automatically restoring deposits/withdrawls when the generous outage time-frame is complete, or when the outage is manually updated as 'finished', (or when an API/endpoints returns a certain value??,) whichever comes first.

In addition, it would be best to have an additional generic deposit/withdrawal disablement message beyond 'instability', due to potential negative implications. Something more like, 'temporarily disabled due to network upgrade' would give a better indication to the user that the network isn't actually unstable/broken/built poorly/etc., but rather that it's just going through an upgrade; as well, that deposits and withdrawals will be restored soon.

## Potential Solution

Add an additional outage message, and have it activate at a certain block height. Assuming that a network with reach a specific block height when scheduled to upgrade and not advance to a new block until the block height is complete, a simple endpoint status query should be able to indicate to the client whether the upgrade is still ongoing.

Please discuss other ideas below.

**Comment by jonator** [comment]
Closing for now until that convo is arrived at.
