### ISSUE TITLE
Make 'token select' hitbox bigger on swap UI

### ISSUE THREAD

**Issue by victortokaito** [osmosis-labs/osmosis-frontend#124]
Can we increase the size of the hitbox (the interactive area that you can click on) for the 'token select' UI? 

Right now, the hitbox is small enough that it's easy to miss and click outside of the drop-down menu. Clicking the token and its icons don't activate the dropdown. 

[See loom video for example: https://www.loom.com/share/f3efb9a080a045808d8ce5ec83ec78a2](https://www.loom.com/share/f3efb9a080a045808d8ce5ec83ec78a2)

**Comment by victortokaito** [comment]
Thank you! 🚀

**Comment by dogemos** [comment]
Thanks Jon!

**Comment by victortokaito** [comment]
Can we implement this on the Single-Asset LP swap as well?
