### ISSUE TITLE
Add Partial Unbond to UI

### ISSUE THREAD

**Issue by JeremyParish69** [osmosis-labs/osmosis-frontend#126]
I think the image explains it well. Since `begin-partial-unbond` is here (or coming soon), we should be able to allow for something like this, where the user can enter a specific amount of LP tokens to unbond:

We may be able to eventually have some kind of combined 'Manage LP tokens' or 'Manage bondings' section/prompt for a cleaner interface (like how Sushi has), but for now you should be able to bascially reuse the 'Bond LP tokens' prompt for allowing to specify for partial unbond. Since LP tokens aren't always in user friendly numbers (in terms of readability), perhaps an option to enter a % of bonded tokens and showing $ value of specified amount could also be nice.

![image](https://user-images.githubusercontent.com/95667791/145312838-808f87ee-b95a-4c39-92cd-1d3c5d776d9b.png)

**Comment by dogemos** [comment]
Unfortunately, LP bonding positions are still not fungible. Each bonding tx has its unique bonding tx ids (similar to NFTs), therefore I think trying to accommodate a UI for this may be too complex for the average user at this time.

Will re-approach this issue once the bonding positions become fungified.
