### ISSUE TITLE
Consider adding LBP simulation chart for LBPs

### ISSUE THREAD

**Issue by dogemos** [osmosis-labs/osmosis-frontend#129]
## Background / Problem
* LBPs follow a drastic 'start high, end low' dutch-auction-like mechanism for markets demand to be reflected in initial price discovery of tokens
* LBPs are effective when there is demand 'at a certain price', not 'at a certain time'
* Lack of understanding of the LBP mechanism can lead users to 'ape-in' early
* Mechanism between pool weight <> token price can be too difficult to understand

## Solution
* Provide a more digestible graph/chart on the LBP pool details page breaking down the simulated price graph over time
* Show that 'buying the token' moves price up vs 'not buying the token' moves price down

## Potential issues/ things to consider
* LBP pool on Osmosis, while not insignificant, is relatively smaller in comparison to existing pools. Don't overcomplicate, overengineer, overdesign. Need to be resource efficient with bigger priorities if needed.
* Working with the Imperator historical data may be necessary to provide non-onchain information that may need to be included in chart

## Helpful resources
* [Copper LBP](https://copperlaunch.com/auctions) is a good example
* Stargaze team created a [LBP simulator for Cosmos](https://github.com/public-awesome/lbp-simulator)

**Comment by victortokaito** [comment]
Quick sanity check: Are the 3d/4d/5d sample charts supposed to be [increasing in token price](https://lbp-simulator.publicawesome.dev/)?

**Comment by jhernandezb** [comment]
@victortokaito this is due to the default fake volume set in the UI ($1M) set it to 0 and you will see it price naturally drops, will default it to 0 to avoid any confusion but the idea is that you can play with an estimation of expected volume and see how this behaves.
