### ISSUE TITLE
Menu icon image missing on mobile

### ISSUE THREAD

**Issue by arispech** [osmosis-labs/osmosis-frontend#1296]
Mobile swap page missing menu icon (both direct on a mobile browser and via Keplr mobile)
![image](https://user-images.githubusercontent.com/56182049/216637690-4dcd1444-5179-4654-866b-466228dcdc11.png)
![image](https://user-images.githubusercontent.com/56182049/216637728-d3b84867-b5b2-4a5b-a959-49139fd162ac.png)
![image](https://user-images.githubusercontent.com/56182049/216637782-e56deac5-78ab-4af0-99ff-32493c324fbd.png)

**Comment by jonator** [comment]
@JoseRFelix @daniel-farina I believe this is still an issue, I even cleared the cache and still does not appear..

**Comment by jonator** [comment]
Fixed, caching issue
