### ISSUE TITLE
Low-Definition Asset Logos

### ISSUE THREAD

**Issue by arispech** [osmosis-labs/osmosis-frontend#1309]
The low-quality images, to lesser or greater degree, on Desktop and Mobile, for assets like: HUAHUA, FET, MED, XPRT, KUJI, CMDX, EEUR WBTC, even  ION are a bit pixelated too. 

![image](https://user-images.githubusercontent.com/56182049/217125009-a49d6348-c72f-4824-a6f1-248079303812.png)
![image](https://user-images.githubusercontent.com/56182049/217125026-dd54a29a-ce1d-4c08-9e75-4e2aebcb40d7.png)

**Comment by jonator** [comment]
@JeremyParish69 is this due to the use of png vs svg? IMO we should use SVG where possible

**Comment by JeremyParish69** [comment]
> @JeremyParish69 is this due to the use of png vs svg? IMO we should use SVG where possible

Probably, yes,but I'm not certain. I've even heard claims that the svg looked worse than the png (although I didn't believe it).
Whenever I add a token, I use the svg if it's available, but many times there is only a png available.
