### ISSUE TITLE
Earning/day showing $0

### ISSUE THREAD

**Issue by arispech** [osmosis-labs/osmosis-frontend#1336]
if a user bonded $223 in pool#1, it should show the earning of at least $0.09/day according to the calculator from the info site.

<img width="1079" alt="Screen Shot 2023-02-15 at 6 07 54 AM" src="https://user-images.githubusercontent.com/56182049/219014605-19560613-717b-4546-a4e4-df88f58088e2.png">

**Comment by jonator** [comment]
This is working for me... perhaps it is a caching issue. Is this still an issue, after clearing cache?
