### ISSUE TITLE
Correct APR on Pools Page

### ISSUE THREAD

**Issue by arispech** [osmosis-labs/osmosis-frontend#1337]
The APR listed on the pools page is currently just the incentives received, not including the Swap fee or Superfluid.
![image](https://user-images.githubusercontent.com/56182049/219016527-0b727636-ab41-4463-a886-9287eb024e8b.png)

This is displayed in the pool page itself correctly:
![image](https://user-images.githubusercontent.com/56182049/219016750-109e6c47-e1b1-406a-9deb-ca95d55122ad.png)

**Comment by jonator** [comment]
Not sure why that was happening. I don't see the issue now, can reopen if we notice it again.

**Comment by arispech** [comment]
There are reports coming in about this issue and I'm still seeing it. @jonator

**Comment by arispech** [comment]
Fixed https://github.com/osmosis-labs/osmosis-frontend/pull/1369
