### ISSUE TITLE
EVMOS decimals on the swap page break UI

### ISSUE THREAD

**Issue by arispech** [osmosis-labs/osmosis-frontend#1346]
![image](https://user-images.githubusercontent.com/56182049/219960404-2aa3f933-352e-4065-a2b4-2ade01fd79ca.png)

**Comment by arispech** [comment]
Would like to add more cases here for better UX, perhaps this is not just EVMOS issue

<img width="434" alt="Screen Shot 2023-02-21 at 12 06 10 PM" src="https://user-images.githubusercontent.com/56182049/220413003-6a3a9ae4-4b94-4667-b06b-0af8caab9194.png">
<img width="426" alt="Screen Shot 2023-02-21 at 12 06 34 PM" src="https://user-images.githubusercontent.com/56182049/220413033-d24519ae-6a00-48d9-9fc4-8648ae2abe88.png">

**Comment by jonator** [comment]
https://github.com/osmosis-labs/osmosis-frontend/pull/1347

Feel free to check out previews here to double check this category of issues

**Comment by arispech** [comment]
> #1347
> 
> Feel free to check out previews here to double check this category of issues

Just checked the preview link, still see the long decimals(more than 8)

<img width="1108" alt="Screen Shot 2023-02-21 at 12 43 25 PM" src="https://user-images.githubusercontent.com/56182049/220421058-afb96715-1faf-4d11-bf33-5d4fc6ce41b8.png">

**Comment by jonator** [comment]
Ah ok I didn't know we'd restrict them on the token select.

I can do that too

**Comment by arispech** [comment]
Oh I thought it would show the same in swap card and tokens select😅 didn't know they were different element.
If that is the case, yes, the decimals are fixed.

However triming decimals in tokens select may also result a cleaner UI imo

**Comment by jonator** [comment]
Done:

<img width="456" alt="Screen Shot 2023-02-21 at 2 50 05 PM" src="https://user-images.githubusercontent.com/4606373/220455585-871bc853-8c00-4cdd-bd99-c509a52f7d2a.png">
