### ISSUE TITLE
External incentives not showing up on the main app

### ISSUE THREAD

**Issue by arispech** [osmosis-labs/osmosis-frontend#1352]
From TG: looks like the external incentives cables are unplugged from the main site and causing the apr issue and making `Bond Shares` unavailable

![telegram-cloud-photo-size-4-6032901194030104053-y](https://user-images.githubusercontent.com/56182049/220856634-83920378-89dc-4d96-be99-cd45e5377b11.jpg)

![telegram-cloud-photo-size-4-6032901194030104054-y](https://user-images.githubusercontent.com/56182049/220856682-df7f87a1-2776-4bfa-bdd1-8fad4e14548c.jpg)

![telegram-cloud-photo-size-4-6032901194030104059-y](https://user-images.githubusercontent.com/56182049/220856666-25fcf2b9-7479-4ae9-91eb-8f72e64b6ce6.jpg)

![telegram-cloud-photo-size-4-6032901194030104060-y](https://user-images.githubusercontent.com/56182049/220856707-c5b38973-74fc-4777-989f-9e7310e1bc86.jpg)

![telegram-cloud-photo-size-4-6032901194030104063-y](https://user-images.githubusercontent.com/56182049/220856730-3ffd2a14-16a1-44d0-9f8c-67f33df0fc37.jpg)

**Comment by jonator** [comment]
Hey I'm no longer seeing this issue:

<img width="479" alt="Screenshot 2023-02-23 at 2 13 16 PM" src="https://user-images.githubusercontent.com/4606373/221019574-570bf05a-384c-40c3-8de4-a309cff2efc5.png">

<img width="572" alt="Screenshot 2023-02-23 at 2 13 25 PM" src="https://user-images.githubusercontent.com/4606373/221019620-2d463167-20f6-4424-90e7-149e76d3675e.png">

**Comment by arispech** [comment]
Hmm, this however still shows me: 
<img width="637" alt="Screen Shot 2023-02-23 at 10 27 55 PM" src="https://user-images.githubusercontent.com/56182049/221084984-5f26b830-be3a-4946-8ffe-5647248bd269.png">

**Comment by arispech** [comment]
Fixed
