### ISSUE TITLE
Firefox and Chrome show different routes in the swap window

### ISSUE THREAD

**Issue by arispech** [osmosis-labs/osmosis-frontend#1366]
Firefox show:
<img width="1058" alt="Screen Shot 2023-03-01 at 9 16 36 AM" src="https://user-images.githubusercontent.com/56182049/222167643-cfc253a4-96a7-49c8-9bf4-faee08c4652b.png">

Chrome show:
<img width="1168" alt="Screen Shot 2023-03-01 at 9 16 58 AM" src="https://user-images.githubusercontent.com/56182049/222167690-a137cf3e-f08b-4e0a-bb19-20c9b1e122e9.png">

**Comment by jonator** [comment]
Hmm.. not sure why this is. Low prio since we don't support firefox

**Comment by jasbanza** [comment]
@jonator in which case, should the site not restrict Firefox users based on user-agent? (I'm not sure this is the best solution either, since a public website should conform to standards)

**Comment by jonator** [comment]
> @jonator in which case, should the site not restrict Firefox users based on user-agent?

This is true

I looked into this. The sort() function is working differently on firefox vs chrome...

Closing for now since we don't support firefox.
