### ISSUE TITLE
Redesign Liquidity Mining Rewards section

### ISSUE THREAD

**Issue by JeremyParish69** [osmosis-labs/osmosis-frontend#138]
I'd argue that the current liquidity mining screen is not as intuitive as it could be, doesn't convey enough information--and where it does, it's scattered--and isn't sustainable for potential future scenarios.

For example, let's say Juno network provides 2045 JUNO as bonus rewards. How will users know whether that bonus is being matched by Osmosis? Or let's say someone else offers a few extra JUNO to the bonus. Does that additional offer get matched? (I assume not). Could someone add a totally random token, e.g., SCRT, to an unrelated pool, e.g., JUNO/OSMO? Or how much does my current LP tokens earn of each token, and by dollar amount, each day?

It would be nice to be able to easily see what the extrenal incentives are (daily amount, which token, remaining # of epochs),  whether they're matched by Osmosis, and what their APRs from each are.

My suggestion here is to have a section for Osmosis Rewards, Matched Rewards, and Bonus Rewards. This should clear much of the confusion around rewards and will be able to handle all kinds of multiple people offering all kinds of different tokens and bonus rewards for all kinds of durations.
I even added a 'My Rewards' section, as an additional suggestion, to show how much the user has bonded to each gauge, and what the daily rewards look like.

I really think something like this (albeit a tad cluttered when there is many types of external incentives) is much more intuitive. Using tooltips can cut down on the explainer paragraphs (e.g., on what bonus rewards are). I ask that you consider taking inspiration from this:

![image](https://user-images.githubusercontent.com/95667791/145752820-1612bc63-413b-417a-bc27-7d607e43c4a3.png)

**Comment by JeremyParish69** [comment]
Kept playing with the concept. Tried to match the original aesthetic more closely. I know it's a lot, but the rewards breakdown is 'below the fold'.

![image](https://user-images.githubusercontent.com/95667791/146658639-f939cd1b-c2c4-4272-bd9d-dfc20dcd358f.png)

**Comment by jonator** [comment]
These are interesting designs and are packed with info. We may look into this as a post-refactor feature.
