### ISSUE TITLE
Front-end crashes when both phantom + keplr is active

### ISSUE THREAD

**Issue by arispech** [osmosis-labs/osmosis-frontend#1392]
On app.osmosis.zone

Front-end ends up in a loop when both phantom wallet and keplr wallet are enabled.

Tested on both Windows + Mac.

It appears that it could be related to NextJS and/or Phantom. Not Osmosis Web App, as it seems mintscan also runs into the same issue.

![image](https://user-images.githubusercontent.com/56182049/225697934-3c5843c7-ea54-47fc-a355-ad0ec94cdfe2.png)

**Comment by jonator** [comment]
Have we somehow notified the phantom + keplr team?

**Comment by jonator** [comment]
@arispech lmk if this is still reproducible, perhaps wallet teams have pushed a fix.

**Comment by arispech** [comment]
Just confirmed with Josh that this is no longer an issue.
