### ISSUE TITLE
Use token logos under Pool Catalyst

### ISSUE THREAD

**Issue by JeremyParish69** [osmosis-labs/osmosis-frontend#142]
### Problem

Within the *Pool Catalyst* section of a pool's page (*/pool/###*), the current colored circles with bubbles in them don't serve much value, and misses an opportunity to make it quicker and easier to visually understand which tokens make up the pool.

### Solution

Replacing the generic bubbling liquid with the token logo will vastly improve readability. See image below for an example of current vs proposed.

![image](https://user-images.githubusercontent.com/95667791/146625861-b8bfa301-5366-4ce0-8c9e-12251a93a68b.png)

**Comment by victortokaito** [comment]
Hi Jeremy, we're currently working on similar UX solutions in #152. Shipping soon:)
