### ISSUE TITLE
Slow pools page load time, unresponsiveness, and lagging when scrolling on MacOs and Windows devices

### ISSUE THREAD

**Issue by daniel-farina** [osmosis-labs/osmosis-frontend#1421]
I've been using the website on various platforms, including MacOs and Windows devices, and noticed that the page load time is a bit slow. Additionally, once the page loads, I'm experiencing some unresponsiveness and lagging.  As reported internally, adding it here for tracking. 

Additional info copied from chat: 

This shows on the console on local dev environment:

```
next-dev.js?36dd:32 Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
    at Image (webpack-internal:///../../node_modules/next/dist/client/image.js:381:22)
    at div
    at div
    at PoolQuickActionCell (webpack-internal:///./components/table/cells/pool-quick-actions.tsx:74:24)
    at cell (webpack-internal:///./components/complex/all-pools-table.tsx:385:192)
```

RatePretty, PricePretty takes a long time to process

https://files.slack.com/files-pri/T0263JRR934-F04V10G5W2X/image.png

**Comment by jonator** [comment]
@JoseRFelix perhaps we can pull out the gauge_by_id query into the render function, then process the rest of the pool list data in the useMemo hook as we had? Would prevent a lot of downstream rendering and data processing. 

For a while in stage, it was a lot faster than it is now, but we were running into strange issues with Mobx query objects being called from useMemo hook (causing 3-4x more requests than needed)
