### ISSUE TITLE
[EPIC] Main trading page

### ISSUE THREAD

**Issue by ValarDragon** [osmosis-labs/osmosis-frontend#144]
Currently the tokens in main page's UI, when you click the "From" button, are sorted by what appears to be the order in the assets page.

Instead, we should change it so that it puts tokens you already have at the top. (So you don't have to scroll as far as to find them)

# Tracking tasks

- [x] #349

**Comment by JeremyParish69** [comment]
Agreed.

To me, makes sense to have this sorted in descending order by dollar value of amount owned.
Does this include tokens LP'd? or just available? My guess is that it's much easier to only look at available tokens.
Should these still be listed after OSMO regardless of how much OSMO they own?

Could also be nice to see near the top the token(s) involved in their most recently transaction. (is that too much work?)
So if their most recent transaction were a swap, or LP, then it would list the two (or more) tokens.
But if their most recent transaction were a deposit/withdrawal, then that one token would be listed.

Example order:
- OSMO
- MOSTLY RECENT TX TOKEN(S) (only if their last tx incuded a non-osmo token, descending by dollar value  owned and available)
- OWNED AVAILABLE TOKENS (descending by dollar value owned and available)
- OWNED PROVIDED TOKENS (optional, probably too much work, not really necessary)
- DEFAULT ASSET LIST ORDER

**Comment by Thunnini** [comment]
this is wip as part of the refactor #163

**Comment by jonator** [comment]
@Thunnini I added this issue to the "In Progress" column of the refactor project

**Comment by jonator** [comment]
@Thunnini I'm "repurposing" this issue to encircle _all_ functionality on the main trading page (routing, GammSwapManager, etc.)

**Comment by jonator** [comment]
- [ ] Create a separate issue to improve routing post refactor @Thunnini @dogemos
