### ISSUE TITLE
question: how to display pool external incentives

### ISSUE THREAD

**Issue by aleem1314** [osmosis-labs/osmosis-frontend#1465]
Pool 629 now has external incentives, which added recently. However, I'm unable to locate instructions on displaying them in the Osmosis frontend.

**Comment by aleem1314** [comment]
Not yet. Start time is `2023-04-08 05:56:24` . This is transaction hash https://www.mintscan.io/osmosis/txs/7FBB410870D694E9C5376E72A5FB9F7D03B976E9F316AC94E0C40C0163A26B09

**Comment by jonator** [comment]
Once it's started they will be displayed.
