### ISSUE TITLE
Application error: a client-side exception has occurred

### ISSUE THREAD

**Issue by Galadrin** [osmosis-labs/osmosis-frontend#1472]
when selecting MNTL to WBTC pool on Osmosis Frontier, the application crash.
see console log attached.

[frontier.osmosis.zone-1680986361129.log](https://github.com/osmosis-labs/osmosis-frontend/files/11184212/frontier.osmosis.zone-1680986361129.log)

Way to reproduce:

- go to swap
- select from MNTL
- selct to WBTC
=> crash

**Comment by jonator** [comment]
Currently looking into this

**Comment by jonator** [comment]
Exception no longer makes it to window
