### ISSUE TITLE
Make it possible to filter Pools and Assets on Asset/Chain

### ISSUE THREAD

**Issue by gucky25** [osmosis-labs/osmosis-frontend#148]
Because the number of Pools and Assets are growing it is sometimes difficult to find the Pool or Asset you are searching for.

I think this can be solved by adding a filter (in the top) on the Pools and Assets pages.

Thank you for all the good work in this beautiful project.

**Comment by victortokaito** [comment]
Hi Gucky, thank you for your feedback and continued use of osmosis :).

We're currently working on providing more tools for users to filter data as mentioned in #128. These fixes will be implemented alongside other general UI enhancements in #152
