### ISSUE TITLE
USD Prices are incorrect

### ISSUE THREAD

**Issue by chmichael** [osmosis-labs/osmosis-frontend#153]
Hello,
  Using the up/down button to switch the tokens the USD price of the tokens will not be the same.

1) Use a token pair eg. Luna/Osmo
2) Wait for a USD change (no cents) of one of the token and the press the middle button to switch.

The USD price will be different. I expect to be the same.

So it seems that frontend doesn't correctly update the USD values of both tokens or are you getting the USD values from CoinGecko which it's slow ? Isn't an oracle better like Band ?

![Osmosis-Prices](https://user-images.githubusercontent.com/13120950/147176176-fe44d56c-4779-4ba1-835a-13dd5f883512.jpg)

**Comment by RowanUtrecht** [comment]
This is just how a AMM pool works.
A pool tries to stay in balance, but with each swap the pool is moved out of balance.

And the price in USD (from Coingecko) can be delayed. And it can be that a coin has a slightly different price on other exchanges.

But this can give you small arbitrary opportunities.
With $173 worth of Osmo you can buy $175 worth of Luna according to the market prices

**Comment by chmichael** [comment]
By the time you press the button the prices might be already different.
