### ISSUE TITLE
Remove Pool 562 LUNA/UST from Trade page

### ISSUE THREAD

**Issue by JeremyParish69** [osmosis-labs/osmosis-frontend#154]
## Ask

Please remove Pool 562 LUNA/UST from being used from the Trade page.

## Problem

The Trade page on Osmosis app defaults to using pool 562 to trade between LUNA and UST with a swap fee of 0.535%. The primary issue is that this swap fee is high and discourages trading on Osmosis. For those who don't know that a cheaper routes exist (e.g., through Pool 560 (at 0.2% fee) and then Pool 561 (at 0.2% fee) == 0.4% fee total) are charged extra swap fee and might choose an alternative trading platform (e.g., TerraSwap); while those who do know that a cheaper route exists are inconvenienced by manually having to swap to OSMO first as an intermediate step.

<img width="335" alt="image" src="https://user-images.githubusercontent.com/95667791/147421760-ceb604e1-ee18-446c-bb95-a2db6ccf5423.png">

In addition, due the fact that this pool is selected for these types of trades when it is not the cheapest trade option, we have more of the Osmosis incentives being allocated to LPs of this pool--a pool without OSMO--which is Liquidity that is not benefitting Osmosis (yet) because cheaper routes exist.

## Solution

The solution in the short term is simple: ensure that trades between on LUNA and UST on the Trade page instead go through pools 560 (UST/OSMO) and 561 (LUNA/OSMO).

I think it might just need to be removed from `GAMMSwapManager` at [osmosis-frontend/src/stores/root.ts](https://github.com/osmosis-labs/osmosis-frontend/blob/e325778ec7753487d03004d9e2860b272ed29f10/src/stores/root.ts), however, more change might be required to ensure the route does a hop through pools 560 and 561 instead of pool 562.

### Discussion

There has been discussion on this on [Commonwealth](https://commonwealth.im/osmosis/proposal/discussion/3075-remove-pool-562-lunaust-from-trade-screen) and a bit on Osmosis Siberia, which explore further the problem, the possible solutions, and all seem to conclude that removal of Pool 562 as default on the Trade page is the only solution we have right now. (i.e., unless pool sub-governance or optimized trade routing are coming very very soon).

**Comment by JeremyParish69** [comment]
On second thought, we should just make ALL non-OSMO token swaps via the Trade page route through OSMO, regardless of how much liquidity or swap fee there might be. Until we have an optimized trade router, it's the best we got, and it at least benefits OSMO LPs over LPs who don't provide any OSMO.

**Comment by dogemos** [comment]
Hey @JeremyParish69! Thanks for the issue.

I think this can be broken down to two subtasks:
1. Improving the trade router (definitely on the to-do list post-refactor)
2. A strategic discussion around the role of OSMO as a middle-currency. (https://github.com/osmosis-labs/osmosis-frontend/issues/164)

While #1 is in progress, I think it's does require more foundational architecture design decisions on the router itself. Let's continue the discussion around the 'OSMO' as a conversion-currency on issue #164
