### ISSUE TITLE
Use asset registry

### ISSUE THREAD

**Issue by dogemos** [osmosis-labs/osmosis-frontend#158]
# Problem
Currently, token information is included to the osmosis-frontend source build. This means there is a duplicated effort of adding token information for every time a new token needs to be added to Osmosis. 

# Potential Solution
* There already is [osmosis-labs/assetlists](github.com/osmosis-labs/assetlists) which has all the information (including token logos) needed.
* The Osmosis frontend should fetch all the information from assetlists including token denom, decimals, IBC channels, logo, etc.
* One issue could be RPC/REST endpoints do not exist in assetlists, and will need to be added from [cosmos/chain-registry](github.com/cosmos/chain-registry). However, because Keplr requires websockets to be enabled there needs to be some checking of the endpoint to ensure that websocket works.

**Comment by jonator** [comment]
From convo with Sunny - given new bridge integration, we will need to include non-IBC bridge (i.e. Axelar) config info in the canonical asset list.

**Comment by jonator** [comment]
Closing in favor of tracking on ClickUp
