### ISSUE TITLE
Enable lambda ibc transfer in frontier

### ISSUE THREAD

**Issue by steveliupai** [osmosis-labs/osmosis-frontend#1583]
Lamb has been disabled for ibc client instability.
<img width="710" alt="image" src="https://github.com/osmosis-labs/osmosis-frontend/assets/3140474/e293987e-997e-414c-a2c6-2577dc15acdb">

Now, the [update client proposal](https://www.mintscan.io/osmosis/proposals/511) has passed and is there any way to enable lamb again in frontier?
<img width="981" alt="image" src="https://github.com/osmosis-labs/osmosis-frontend/assets/3140474/e000b4eb-3f60-4b58-84b7-5d412f13a60f">

**Comment by steveliupai** [comment]
@JeremyParish69 Hi Jeremy, do u know how to fix this to recover LAMB ibc transfer in osmosis frontier

**Comment by JeremyParish69** [comment]
Thanks @steveliupai Resolved now.

**Comment by steveliupai** [comment]
> 

Thank you so much, Jeremy
