### ISSUE TITLE
[Epic] Osmosis Frontend Refactoring

### ISSUE THREAD

**Issue by dogemos** [osmosis-labs/osmosis-frontend#163]
## Goals
* Component standardization
   * Need dependency on design team (cc @victortokaito)
   * Allow reusable components
* Separation of logic-related code and view-related code
   * Currently code related to logic and code related to view are mixed up, causing lots of bugs
   * Adding new features are resource intensive
* Previous refactor was started but wasn't finished
* Standardize frontend styling framework to tailwind
   * Currently using two frameworks for frontend styling (tailwind and emotion)
* Move to NextJS

**Comment by jonator** [comment]
Perhaps as a stretch goal we could include unit tests w/ jest/enzyme post refactor. This could provide sanity checks moving forward.

**Comment by jonator** [comment]
Planned this out in a [project](https://github.com/osmosis-labs/osmosis-frontend/projects/1?add_cards_query=is%3Aopen)

**Comment by CMarshall92** [comment]
Heads up reframe from enzyme it's been completely deprecated, author suggests uptake of RTL

**Comment by dogemos** [comment]
Closing in favor of the refactor project board
