### ISSUE TITLE
Default Multi-hop trades should use OSMO pools

### ISSUE THREAD

**Issue by JohnnyWyles** [osmosis-labs/osmosis-frontend#164]
Multi-hops are using non-optimal routes by not using OSMO pools.  OSMO pools tend to have 0.2% fees compared to 0.3% fees for ATOM pools as well usually having substantially more Liquidity to minimise slippage due to the OSMO bias on incentives attracting more liquidity before a stable Liquidity is reached.

Example:
Swap from DVPN to HUAHUA via OSMO multi hop: costing **0.4%** swap fees and **0.142%** slippage
![image](https://user-images.githubusercontent.com/97029546/147927237-a557af08-aaae-43bf-a6ca-3b1586ba1b6f.png)

Swap back from HUAHUA to DVPN goes via ATOM pools and costs **0.6%** fees and **0.727%** slippage
![image](https://user-images.githubusercontent.com/97029546/147927253-bcbe99a5-72d4-45d4-a03a-67b8a74df0ec.png)

Discussion on this here: [Commonwealth](https://commonwealth.im/osmosis/proposal/discussion/3125-default-routing-via-osmo-pools)

**Comment by JeremyParish69** [comment]
At least defaulting to using OSMO as a hop would present a path for each trade. Currently, for some trades there is no path given. E.g.,:
![image](https://user-images.githubusercontent.com/95667791/148471248-838a5d76-bfb4-4139-b6aa-162b3cf49a79.png)

**Comment by RowanUtrecht** [comment]
I really love this idea! Would create extra value for people swapping (most times lower fee) and osmo holders in pool!
