### ISSUE TITLE
mnemonic

### ISSUE THREAD

**Issue by c29r3** [osmosis-labs/osmosis-frontend#17]
https://github.com/osmosis-labs/osmosis-frontend/blob/develop/localnet/mnemonics.txt#L4
https://github.com/osmosis-labs/osmosis-frontend/blob/develop/localnet/Dockerfile#L53

`cosmos1h5rcx73zj474nrkkcyf28tud47k8thy5d6cyuh` // 0.913 ATOM  
`osmo1h5rcx73zj474nrkkcyf28tud47k8thy59pt529` // 9.865 OSMO  
`cosmos1ymk637a7wljvt4w7q9lnrw95mg9sr37y4s4an9` // 0.593 ATOM

**Comment by sko-kr** [comment]
💸

**Comment by ValarDragon** [comment]
gg haha
