### ISSUE TITLE
Add LUM token to Trade page

### ISSUE THREAD

**Issue by JeremyParish69** [osmosis-labs/osmosis-frontend#170]
Now that IBC has been re-enabled for LUM network, the LUM token aught to be added back onto the Trade page, which is currently missing.

![image](https://user-images.githubusercontent.com/95667791/148134101-c5b42e77-0272-4828-a0e1-9d53d4eb9714.png)

**Comment by ValarDragon** [comment]
Should be closed by #171

**Comment by ValarDragon** [comment]
Leaving open until its confirmed on there

**Comment by ValarDragon** [comment]
its on there
