### ISSUE TITLE
IBC deposit failed for all evmos type Denom

### ISSUE THREAD

**Issue by steveliupai** [osmosis-labs/osmosis-frontend#1707]
Lambda deposit will throw out an error  "pubKey does not match signer address xxx with signer index: 0: invalid pubkey" ,
Same problem occurs for all evmos type chains like `evmos`, `rebus`, `planq`.

BTW, it works fine by using Keplr IBC transfer directly.

**Comment by JeremyParish69** [comment]
REBUS (type 118) works fine, but PLQ has issues for Deposit (Withdraw works fine), and EVMOS has an alternative frontend. Will redirect Planq Deposit to TFM for the time being.

@jonator using TFM is more of a bandaid solution we got lucky with. Should we close this when the solution is applied? or keep it open until the frontend has the coin type 60 deposit transaction supported?

**Comment by jonator** [comment]
Yeah if tokens don't follow the standard, we should open some other frontend to do the bridging.

We should not support or encourage deviations from the standard

**Comment by JeremyParish69** [comment]
Note that linking to TFM can still cause UX issues because it doesn't simulate gas. Users have to be smart enough to subtract the amount of gas it'd cost if they want to transfer the max amount.
