### ISSUE TITLE
ibc assets that aren't yet identified run out of bounds

### ISSUE THREAD

**Issue by dylanschultzie** [osmosis-labs/osmosis-frontend#187]
This can be seen here: https://app.osmosis.zone/pool/621

FWIW: This is the *dig* asset

<img width="1312" alt="Screen Shot 2022-01-13 at 6 27 28 PM" src="https://user-images.githubusercontent.com/9121234/149441138-2ed3b7b8-0331-4f06-bf0b-9a9cd0851201.png">

**Comment by dogemos** [comment]
Just going to merge this with this issue https://github.com/osmosis-labs/osmosis-frontend/issues/158. Technically, any assets on Osmosis *should* be on assetlists.
