### ISSUE TITLE
Testnet frontend

### ISSUE THREAD

**Issue by czarcas7ic** [osmosis-labs/osmosis-frontend#227]
Testnet frontend not recognizing balances.

https://testnet.osmosis-frontend.pages.dev/

Current issue is https/http mismatch

**Comment by dogemos** [comment]
Any chance we can use https for the testnet endpoints?

**Comment by czarcas7ic** [comment]
We originally used these which still produced a different error

https://osmosistest-rpc.quickapi.com:443/
https://osmosistest-lcd.quickapi.com:443/

**Comment by jonator** [comment]
@czarcas7ic updates on your end? New URLs to try?

**Comment by czarcas7ic** [comment]
@jonator this is blocked on me until I fix the testnet. The chain halted last night and we are still diagnosing the issue. Ill keep you in the loop and will circle back to this once we get the testnet back up and running

**Comment by czarcas7ic** [comment]
@jonator got the new testnet up with the new RPC located here: http://143.198.139.33:26657/

Please let me know what I can do to assist with setting up this frontend!

**Comment by czarcas7ic** [comment]
@clemensgg from cryptocrew set up an RPC and LCD we can use for the frontend in this PR https://github.com/osmosis-labs/osmosis-frontend/pull/266 (thanks again!)

Should be enough to begin further testing, let me know what I can do to help

**Comment by czarcas7ic** [comment]
• Public RPC 
      https://rpc.osmo-test.ccvalidators.com/ (hosted by CryptoCrew)
      https://osmosistest-rpc.quickapi.com/ (hosted by ChainLayer)
      http://143.198.139.33:26657

• Public LCD
      https://osmosistest-lcd.quickapi.com/ (hosted by ChainLayer)
      https://lcd.osmo-test.ccvalidators.com/ (hosted by CryptoCrew)
      http://143.198.139.33:1317/

**Comment by czarcas7ic** [comment]
Closed, https://testnet.osmosis.zone
