### ISSUE TITLE
Module not found: Error: Can't resolve '../styles/index.scss

### ISSUE THREAD

**Issue by pengjinning** [osmosis-labs/osmosis-frontend#229]
ERROR in ./src/pages/NotFound.tsx
Module not found: Error: Can't resolve '../styles/index.scss' in '/Users/**/Desktop/dapp/osmosis/osmosis-frontend/src/pages'
 @ ./src/pages/NotFound.tsx 2:0-30
 @ ./src/index.tsx
 @ multi ./src/index.tsx

ERROR in ./src/index.tsx
Module not found: Error: Can't resolve './styles/index.scss' in '/Users/**/Desktop/dapp/osmosis/osmosis-frontend/src'
 @ ./src/index.tsx 25:0-29
 @ multi ./src/index.tsx

**Comment by dogemos** [comment]
> Please run `yarn build:css` before building.

https://github.com/osmosis-labs/osmosis-frontend/issues/212#issuecomment-1021323207
