### ISSUE TITLE
Too many numbers cause an error and site crash

### ISSUE THREAD

**Issue by machinsoft** [osmosis-labs/osmosis-frontend#240]
Throws an error when there are too many digits

![img](https://i.ibb.co/p0C4jZQ/i01-1.jpg)

**Comment by jonator** [comment]
Hey! Thanks for finding this. If you have the capacity, we'd love to see a pull request to address this!

**Comment by machinsoft** [comment]
I did not make a pool request, but as an option, you can simply limit the number of digits and the problem will disappear.

**Comment by jonator** [comment]
On `optimized-routes` branch? I'll check now
