### ISSUE TITLE
If I've already closed the banner, never have it show on FE reload

### ISSUE THREAD

**Issue by ValarDragon** [osmosis-labs/osmosis-frontend#2433]
Currently there is code to make the frontend banner not re-show on refresh if I've already closed it.

However when I refresh, it shows for one to two seconds until what appears to be more JS loading.

Would be great to never see it. (Or if were aiming to move away from the banner, then maybe this is wasted work)

**Comment by MaxMillington** [comment]
https://github.com/osmosis-labs/osmosis-frontend/issues/2565
