### ISSUE TITLE
Add support for Trust Wallet Extension

### ISSUE THREAD

**Issue by sunnya97** [osmosis-labs/osmosis-frontend#2440]
Begun in #2434 but it's not working rn.

**Comment by DavideSegullo** [comment]
There is a bug on trust wallet side, cosmos-kit expects to find a provider for cosmos injected into the window: "window.trustwallet.cosmos", but it's undefined:

![image](https://github.com/osmosis-labs/osmosis-frontend/assets/17269969/0202c13e-c26f-4705-8ecf-788af614e821)

The only thing available related to cosmos is the "CosmosProvider" class, we can use this one to create an instance of "trustwallet":

```js
const provider = new window.trustwallet.CosmosProvider(false)
```

It seems to works, but some methods are broken, for example if you try to use "getKey" it'll throw up an exception:

![image](https://github.com/osmosis-labs/osmosis-frontend/assets/17269969/8633685a-146e-4c40-a251-19352019e44f)

I wrote a message on their discord, but at the moment I have not received any response

**Comment by DavideSegullo** [comment]
I got a reply on discord telling me that currently the web extension does not support cosmos and that is why the providers are not working

**Comment by MaxMillington** [comment]
https://github.com/osmosis-labs/osmosis-frontend/issues/2563
