### ISSUE TITLE
Trade page's extra 0 in From amt

### ISSUE THREAD

**Issue by JeremyParish69** [osmosis-labs/osmosis-frontend#246]
On the Trade page, when you select the two coins you want to swap, the '0' amount of coins under the 'From' coin is greyed-out, and selecting that field will allow you to enter a number normally. So if you enter '10', it will say '10'.
![image](https://user-images.githubusercontent.com/95667791/153107548-9310eb15-4388-4502-b407-473fcd613c82.png)

But if you click the switch button (that moves the 'From' coin to the 'To' side, and vice versa), the '0' amount in the 'From' amount is now white, and if you click anywhere just left of that '0', any input numbers are prepended before that '0'. So if you enter '10', it will now say '100'.
![image](https://user-images.githubusercontent.com/95667791/153107863-a2ae5f38-94d3-4a19-9dd5-12b75d33a5dc.png)

I get that bringing the value in the 'To' field is useful; if there had been a number input before switching, it can be quite handy to have the same number brought up to the 'From' side. But when it's a zero, it's especially annoying.

This can lead to accidentally spending 10x the amount meant to be spent, if not at least quite annoying because you now have to be mindful, and precisely guide the cursor to delete the extra 0.

Therefore, I suggest that when the 'To' amount has exactly '0', it be a special case such that it is not carried up to the 'From' field.

**Comment by landiehan** [comment]
Hello, I can solve this issue by filtering this special case at where it is rendered.

**Comment by sunnya97** [comment]
Closed by #261
