### ISSUE TITLE
Automatically deduct fees when swapping with MAX [100 USDC reward!] 

### ISSUE THREAD

**Issue by MaxMillington** [osmosis-labs/osmosis-frontend#2518]
🐛  Bug Bounty: Fix Needed! 🛠️ 
Reward: :trophy: 100 USDC 🏆 

We are excited to announce a bug bounty for third-party developers! If you've got the skills and know-how, here's your chance to earn some 💸  and contribute to our project.

Issue Description 📄
Automatically deduct fees when swapping MAX

Expected Behavior 💡
As a user, fees should be deducted when I'm swapping assets and select the 'MAX' option

Current Behavior ❌
Currently, fees are not deducted

Requirements for the Bounty 🏁

 Submit a pull request with a verified fix to the issue.
 The fix should not introduce any new bugs or vulnerabilities.
 Code should follow our project's style and contribution guidelines.
 Your solution will be reviewed by our team, and the bounty will be awarded upon approval.
How to Claim Your Bounty 💰

 Fork our repository.
 Create a new branch for your fix.
 Submit a pull request to our main branch.
 Include detailed information about your fix and how it addresses the issue.

 Once reviewed and merged, the 100 USDC will be transferred to your wallet.
We look forward to your contributions and thank you for helping improve our project!

**Please Note**: All bounty claimants must undergo a KYC (Know Your Customer) process with our finance team to receive the reward. This is a mandatory step to ensure compliance with financial regulations.

**Comment by BalthazarB** [comment]
attempting this

**Comment by HarjobandeepSingh** [comment]
@MaxMillington in local project swap function is not working then how i can test and debug it 
![image](https://github.com/osmosis-labs/osmosis-frontend/assets/81474463/7aa345d0-5457-4cca-85a8-36cc9966adc1)

**Comment by MaxMillington** [comment]
@HarjobandeepSingh Did you run yarn, yarn build, and then yarn run dev? It should work on mainnet locally. Make sure to pull the latest changes.

**Comment by HarjobandeepSingh** [comment]
> @HarjobandeepSingh Did you run yarn, yarn build, and then yarn run dev? It should work on mainnet locally. Make sure to pull the latest changes. 

Yes i did

**Comment by HarjobandeepSingh** [comment]
> @HarjobandeepSingh Did you run yarn, yarn build, and then yarn run dev? It should work on mainnet locally. Make sure to pull the latest changes.

i tried again but its still not working @MaxMillington

**Comment by HarjobandeepSingh** [comment]
> > @HarjobandeepSingh Did you run yarn, yarn build, and then yarn run dev? It should work on mainnet locally. Make sure to pull the latest changes.
> 
> i tried again but its still not working @MaxMillington

**Comment by MaxMillington** [comment]
Closing this and re-opened with more details and requirements [here](https://github.com/osmosis-labs/osmosis-frontend/issues/2733)
