### ISSUE TITLE
Save search in url

### ISSUE THREAD

**Issue by happylolonly** [osmosis-labs/osmosis-frontend#2524]
Hi, I am using https://app.osmosis.zone/pools?pool=stable&pool=weighted&pool=transmuter&pool=concentrated&incentive=internal&incentive=external&incentive=superfluid&incentive=noIncentives, but everytime after refresh page, need to type into search bar, can you save this in url?

<img width="724" alt="image" src="https://github.com/osmosis-labs/osmosis-frontend/assets/18665326/f171c80e-b0e6-4901-afd4-e79d35a3d98e">

**Comment by happylolonly** [comment]
Also check this - https://github.com/osmosis-labs/osmosis-frontend/actions/runs/7164113614

**Comment by jonator** [comment]
Added
