### ISSUE TITLE
Integrate Trust Wallet [500 USDC Reward!]

### ISSUE THREAD

**Issue by MaxMillington** [osmosis-labs/osmosis-frontend#2563]
🐛  Bug Bounty: Fix Needed! 🛠️ 
Reward: :trophy: 500 USDC 🏆 

We are excited to announce a bug bounty for third-party developers! If you've got the skills and know-how, here's your chance to earn some 💸  and contribute to our project.

Issue Description 📄
Integrate the Trust Wallet

Expected Behavior 💡
As a user, I should be able to connect my trust wallet

Information on adding a wallet can be found [here](https://github.com/osmosis-labs/osmosis-frontend/tree/stage/packages/web#adding-a-wallet)

Requirements for the Bounty 🏁

 Submit a pull request with a verified fix to the issue.
 The fix should not introduce any new bugs or vulnerabilities.
 Code should follow our project's style and contribution guidelines.
 Your solution will be reviewed by our team, and the bounty will be awarded upon approval.
How to Claim Your Bounty 💰

 Fork our repository.
 Create a new branch for your fix.
 Submit a pull request to our main branch.
 Include detailed information about your fix and how it addresses the issue.

 Once reviewed and merged, the 500 USDC will be transferred to your wallet.
We look forward to your contributions and thank you for helping improve our project!

**Please Note**: All bounty claimants must undergo a KYC (Know Your Customer) process with our finance team to receive the reward. This is a mandatory step to ensure compliance with financial regulations.

**Comment by MaxMillington** [comment]
begun [here](https://github.com/osmosis-labs/osmosis-frontend/pull/2434) but not currently working.

The web extension might not currently support cosmos

[Previous issue](https://github.com/osmosis-labs/osmosis-frontend/issues/2440)

**Comment by isreallee82** [comment]
whats the process for applying for the bounty here @MaxMillington

**Comment by skushagra9** [comment]
Hey @MaxMillington , I am willing to work on this

**Comment by MaxMillington** [comment]
@skushagra9 thanks!

**Comment by sunnya97** [comment]
@skushagra9 Trust Wallet is now supported on CosmosKit

**Comment by isreallee82** [comment]
@sunnya97 still in progress 
<img width="933" alt="Screenshot 2024-02-04 at 1 28 49 PM" src="https://github.com/osmosis-labs/osmosis-frontend/assets/70828114/b6ec9d58-ffaf-4bf3-a0d4-c2bb22f24606">

**Comment by MaxMillington** [comment]
@aaronxkong FYI ^

**Comment by forbesus** [comment]
@MaxMillington 
this work is still available?

**Comment by MaxMillington** [comment]
@forbesus yes, still available. Progress has been made [here](https://github.com/osmosis-labs/osmosis-frontend/pull/2774), but we pay the bounty to the first person to get it across the finish line

**Comment by forbesus** [comment]
@MaxMillington 
I am making PR [here](https://github.com/osmosis-labs/osmosis-frontend/pull/3219)

Please check it
