### ISSUE TITLE
Cosmwasm pools in pool row should open in new tab [100 USDC Reward!]

### ISSUE THREAD

**Issue by MaxMillington** [osmosis-labs/osmosis-frontend#2564]
🐛  Bug Bounty: Fix Needed! 🛠️ 
Reward: :trophy: 100 USDC 🏆 

We are excited to announce a bug bounty for third-party developers! If you've got the skills and know-how, here's your chance to earn some 💸  and contribute to our project.

Issue Description 📄
Cosmwasm pools in pool row should open in new tab

Expected Behavior 💡
As a user, when I click on a cosmwasm pool in a pool row, it should open in a new tab since they link to Celatone

Current Behavior ❌
Currently, fit opens in the same tab

Requirements for the Bounty 🏁

 Submit a pull request with a verified fix to the issue.
 The fix should not introduce any new bugs or vulnerabilities.
 Code should follow our project's style and contribution guidelines.
 Your solution will be reviewed by our team, and the bounty will be awarded upon approval.
How to Claim Your Bounty 💰

 Fork our repository.
 Create a new branch for your fix.
 Submit a pull request to our main branch.
 Include detailed information about your fix and how it addresses the issue.

 Once reviewed and merged, the 100 OSMO will be transferred to your wallet.
We look forward to your contributions and thank you for helping improve our project!

**Please Note**: All bounty claimants must undergo a KYC (Know Your Customer) process with our finance team to receive the reward. This is a mandatory step to ensure compliance with financial regulations.

**Comment by HarjobandeepSingh** [comment]
@MaxMillington Sir, Is it ok that others are also trying to submit pull requests for the same issue that I have been working on for a week. I have made some changes that are working, and I have followed the feedback and suggestions from the developers and making changes.
