### ISSUE TITLE
If I've already closed the banner, never have it show on FE reload [100 USDC Reward!]

### ISSUE THREAD

**Issue by MaxMillington** [osmosis-labs/osmosis-frontend#2565]
🐛  Bug Bounty: Fix Needed! 🛠️ 
Reward: :trophy: 100 USDC 🏆 

We are excited to announce a bug bounty for third-party developers! If you've got the skills and know-how, here's your chance to earn some 💸  and contribute to our project.

Issue Description 📄
Only show banner once

Expected Behavior 💡
As a user, when I close the announcement banner, it should not show up again on page reload

Current Behavior ❌
urrently there is code to make the frontend banner not re-show on refresh if I've already closed it.

However when I refresh, it shows for one to two seconds until what appears to be more JS loading.

Requirements for the Bounty 🏁

 Submit a pull request with a verified fix to the issue.
 The fix should not introduce any new bugs or vulnerabilities.
 Code should follow our project's style and contribution guidelines.
 Your solution will be reviewed by our team, and the bounty will be awarded upon approval.
How to Claim Your Bounty 💰

 Fork our repository.
 Create a new branch for your fix.
 Submit a pull request to our main branch.
 Include detailed information about your fix and how it addresses the issue.

 Once reviewed and merged, the 100 USDC will be transferred to your wallet.
We look forward to your contributions and thank you for helping improve our project!

**Please Note**: All bounty claimants must undergo a KYC (Know Your Customer) process with our finance team to receive the reward. This is a mandatory step to ensure compliance with financial regulations.

**Comment by bilalshaikh292** [comment]
heyy @MaxMillington is the issue Still open I would like to contribute ?

**Comment by MaxMillington** [comment]
@bilalshaikh292 feel free to give it a shot. thanks!

**Comment by BrianCraig** [comment]
Hi!

Analyzing the Next.js application's performance and bundle size, I've identified a critical aspect that seems to heavily influence the initial load and bundle size. Upon reviewing the application's loading metrics, I've noticed a significant portion of the bundle size attributed to the `_app.tsx` file, which appears to be highly coupled with multiple dependencies.

Considering the statistics below:

```
Route (pages) Size First Load JS
┌ ● / 923 B 2.09 MB
├ /_app 0 B 2.09 MB
├ ○ /404 (582 ms)                                       448 B          2.09 MB
├ ○ /500 (550 ms)                                       444 B          2.09 MB
├ λ /api/active-gauges                                  0 B            2.09 MB
├ λ /api/bridge-transfer/quotes                         0 B            2.09 MB
├ λ /api/bridge-transfer/quotes/[bridge]                0 B            2.09 MB
├ λ /api/bridge-transfer/transaction-requests/[bridge]  0 B            2.09 MB
├ λ /api/broadcast-transaction                          0 B            2.09 MB
├ ℇ /api/edge-trpc/[trpc]                               0 B            2.09 MB
├ ℇ /api/pools                                          0 B            2.09 MB
├ ℇ /api/pools/[id]                                     0 B            2.09 MB
├ λ /api/router/token-out-given-in                      0 B            2.09 MB
├ λ /api/simulate-transaction                           0 B            2.09 MB
├ λ /api/trpc/[trpc]                                    0 B            2.09 MB
├ ● /apps (ISR: 86400 Seconds) (554 ms)                 186 B          2.09 MB
... (other routes omitted for brevity)

  First Load JS shared by all 2.11 MB
  ├ chunks/7056-995831a93aefcb61.js 82.6 kB
  ├ chunks/7101-1b1047194f005759.js 2 MB
  ... (other chunks omitted for brevity)
 ```

The `_app.tsx` file seems to contribute significantly to the overall bundle size, making the initial load substantial and potentially impacting performance. I'm considering a strategy that involves decoupling `_app.tsx` from unnecessary dependencies and optimizing its structure to facilitate more effective tree shaking.

Before proceeding further with this approach, I wanted to seek confirmation if such solution would be considered as enough to solve the bounty.

Thank you, Brian.

**Comment by sirajlekhak** [comment]
Hey can you please also provide "how to reproduce it" part?

**Comment by MaxMillington** [comment]
fixed by @JoseRFelix with an assist from @BrianCraig. Thanks!
