### ISSUE TITLE
cosmwasm subdirectory missing from published @osmosis-labs/pools package

### ISSUE THREAD

**Issue by blake-regalia** [osmosis-labs/osmosis-frontend#2622]
Reproducing the issue:
`npm i @osmosis-labs/pools`

```ts
import { TransmuterPool } from "@osmosis-labs/pools";
//       ^^^^^^^^^^^^^^ Module '"@osmosis-labs/pools"' has no exported member 'TransmuterPool'.
```

Indeed, taking a look at the package reveals the `cosmwasm` subdirectory is missing from `src/` and `build/`

**Comment by jonator** [comment]
What version? We haven't published in a while

**Comment by jonator** [comment]
Pools package is deprecated
