### ISSUE TITLE
different prices shown on https://info.osmosis.zone/token/GRAV

### ISSUE THREAD

**Issue by voluntatis-summ** [osmosis-labs/osmosis-frontend#265]
![image](https://user-images.githubusercontent.com/93878971/154718206-9266cb80-e639-4b50-bbbc-32c5598ff74a.png)

**Comment by jonator** [comment]
Thanks for this! Please place such issues in the [osmosis-info](https://github.com/osmosis-labs/osmosis-info) repo.
