### ISSUE TITLE
Pools number should show up in links preview [100 USDC Reward!]

### ISSUE THREAD

**Issue by MaxMillington** [osmosis-labs/osmosis-frontend#2661]
🐛  Bug Bounty: Fix Needed! 🛠️ 
Reward: :trophy: 100 USDC 🏆 

We are excited to announce a bug bounty for third-party developers! If you've got the skills and know-how, here's your chance to earn some 💸  and contribute to our project.

Issue Description 📄
Pools number should show up in links preview 

Expected Behavior 💡
As a user, if I copy the link to a pools page and paste it on (e.g.) twitter, the pools number should show in the thumbnail preview

Current Behavior ❌
Currently, we do not have anything in the meta tags, so it just shows '#'
![image (1)](https://github.com/osmosis-labs/osmosis-frontend/assets/11064595/022b65ab-78c2-4d45-a046-1051fa1317ee)

Requirements for the Bounty 🏁

 Submit a pull request with a verified fix to the issue.
 The fix should not introduce any new bugs or vulnerabilities.
 Code should follow our project's style and contribution guidelines.
 Your solution will be reviewed by our team, and the bounty will be awarded upon approval.
How to Claim Your Bounty 💰

 Fork our repository.
 Create a new branch for your fix.
 Submit a pull request to our main branch.
 Include detailed information about your fix and how it addresses the issue.

 Once reviewed and merged, the 100 USDC will be transferred to your wallet.
We look forward to your contributions and thank you for helping improve our project!

**Please Note**: All bounty claimants must undergo a KYC (Know Your Customer) process with our finance team to receive the reward. This is a mandatory step to ensure compliance with financial regulations.

**Comment by jonator** [comment]
This should be doable with SSR.

**Comment by gnujoow** [comment]
> This should be doable with SSR.
i just wonder if osmosis app is going to convert to ssr.

**Comment by MaxMillington** [comment]
@gnujoow we already use SSR in a fair number of spots. Feels free to check it out!

**Comment by MaxMillington** [comment]
Fixed by @fabryscript
