### ISSUE TITLE
How to add a new token to the assets on Osmosis Zone web app？

### ISSUE THREAD

**Issue by nulnut** [osmosis-labs/osmosis-frontend#2691]
Previously, adding a new token was done by [submitting a pull request](https://docs.osmosis.zone/overview/integrate/registration/#steps-2). Now, it requires [submitting a form](https://github.com/osmosis-labs/assetlists/blob/main/LISTING.md).

Our team has followed the documentation and submitted the form three weeks ago, but we haven't received any response.  

Token has been added to osmosis-labs/assetlists through pr osmosis-labs/assetlists#871 .

Do you need any additional information, or is there any further action required from our side?

**Comment by JeremyParish69** [comment]
Hello, adding a new token does not require submitting a form, that is only for the 'Verfied' status. The listing process requires validation, which is currently blocked at the moment. We're looking to working through the pending listings, including $PURSE, ASAP.

**Comment by nulnut** [comment]
Thank you for your response. We will wait for the listing to be completed and proceed with the subsequent tasks. If there are any issues, feel free to contact us.

**Comment by JeremyParish69** [comment]
One blocker I'm facing with PURSE is that I'm unable to acquire $PUNDIX from Osmosis, so there's no way for me to Withdraw and Deposit $PURSE (because I need $PUNDIX for gas to Deposit)

**Comment by nulnut** [comment]
@JeremyParish69 Can you provide a PUNDIX address? We will transfer PUNDIX to you as a transaction fee.

The pull request to add the PUNDIX chain to Keplr has been submitted and is awaiting approval. Now to add the PUNDIX chain to Keplr, please refer to the documentation [support-keplr](https://docs.pundix.com/upgrade-instructions/support-keplr).
