### ISSUE TITLE
IBC deposits fail for certain chains during gas simulation

### ISSUE THREAD

**Issue by mdyring** [osmosis-labs/osmosis-frontend#2703]
IBC deposits have started to fail for older chains (such as emoney-3).

<img width="398" alt="image" src="https://github.com/osmosis-labs/osmosis-frontend/assets/18033781/f9f3e000-151a-404e-b99c-7dd0bb63f252">

It would be great if deposits could revert to using fixed/estimated gas if the simulation fails.

The simulate-transaction request can be reproduced below:
```
curl 'https://app.osmosis.zone/api/simulate-transaction' \
  -H 'authority: app.osmosis.zone' \
  -H 'accept: */*' \
  -H 'content-type: application/json' \
  --data-raw '{"restEndpoint":"https://emoney.validator.network/api","tx_bytes":"Cr0BCroBCikvaWJjLmFwcGxpY2F0aW9ucy50cmFuc2Zlci52MS5Nc2dUcmFuc2ZlchKMAQoIdHJhbnNmZXISCWNoYW5uZWwtMBoQCgR1bmdtEggxMDAwMDAwMCItZW1vbmV5MWdhcmxkZjZjYTBnOXZtbXRjNWNxcHE0YTB6eDQycXhkdzIyZjYwKitvc21vMWdhcmxkZjZjYTBnOXZtbXRjNWNxcHE0YTB6eDQycXhkZmpyZG1xMgcIARCzla0GEgwKCBIECgIIfxh1EgAaQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA="}' \
  --compressed
```

Let me know if I can assist in any way with setting up test account, etc.

**Comment by MaxMillington** [comment]
Closing as we haven't seen this in a while
