### ISSUE TITLE
Support user assets lists

### ISSUE THREAD

**Issue by jonator** [osmosis-labs/osmosis-frontend#272]
### Problem
The number of tokens being added to osmosis is increasing quickly. It's becoming unwieldy to navigate the various IBC assets available for trade (even with sort & search UI). We are currently suffering from the necessary "gatekeeping" problem; new assets are currently enabled by the core dev team, thus stifling the speed of liquidity for innovation.

### Solution
Inspired by Uniswap, there should be a place on the frontend where users can easily select the assets that are visible.

Requirements:
* UX should not be confusing to new/non-power users (put under gear icon on trade clipboard? & bottom of assets page?)
    * There should be a default assets list that contains assets recommended by the team (similar to the current list, could be called "Recommended")
* Users should be able to select multiple lists, and conflicts should throw an error
* (Stretch) Power users should be able to add their own assets list via a URL to a JSON file

Long term- we should seek to add [metadata](https://github.com/cosmos/chain-registry) on chain to be updated via governance proposals. This would grant us the added benefit of officiated token denoms.

**Comment by dogemos** [comment]
One thing we need to decide is whether the custom assetlists will only apply to the trade page's token selection, or globally across the web app (i.e. pools page and assets page).

**Comment by dogemos** [comment]
Right now I think the token lists should only apply to the trade + asset page, with a separate UI displayed to guide users (i.e. 'Not seeing tokens you're looking for?') that could guide users to modify the assetlist if the user doesn't see the asset they are looking for.

**Comment by sunnya97** [comment]
I think it should apply to everything.  Like it should at least re-label tokens on the pools page based off of the assetlist

**Comment by jasbanza** [comment]
> I think it should apply to everything. Like it should at least re-label tokens on the pools page based off of the assetlist

@sunnya97 how important is it for newly listed assets to be visible? I can imagine if a user's assetlist is always filtering his UI, that the user will potentially miss a listing...

**Comment by sunnya97** [comment]
I think that's okay.  People will likely learn about new listings from other sources, not from the assets page itself.  The assets page will show new listings that are added to the default list

**Comment by jasbanza** [comment]
@sunnya97 @jonator I'm not sure if this has been previously discussed elsewhere, if not now, perhaps consider this for later?

**Asset "category" filters:**
_Be able to filter your assets / trade list by the following:_

- SDK Native
- Juno CW-20s 
- Secret SNIP-20s
- Evmos ERC-20s
- Any other ecosystem / bridge filters that come later...

**Comment by jonator** [comment]
- [ ] Look into ways to incorporate chain registry as we work on this project #158 #68

**Comment by jonator** [comment]
Closing in favor of tracking on ClickUp
