### ISSUE TITLE
Metamask popup keeps appearing every time I navigate to https://app.osmosis.zone

### ISSUE THREAD

**Issue by refi93** [osmosis-labs/osmosis-frontend#2722]
Every time I navigate to https://app.osmosis.zone/ or to the "assets" section, a prompt asking me to unlock metamask keeps popping up until I log into metamask which is not good UX and makes the app unusable if I have no intention to unlock my Metamask wallet. Steps to reproduce:

1. go to https://app.osmosis.zone/
2. login with Keplr extension wallet
3. go to "Assets" section and click "deposit" on ETH
4. select Metamask wallet, confirm connection
5. lock metamask wallet
6. from then on, every time I go to https://app.osmosis.zone/ the metamask window asking me to log in pops up until I unlock metamask (or clear site data)

I believe that ideally, https://app.osmosis.zone/ should stop trying to interact with metamask as soon as a user rejects the connection prompt that pops up.

**Comment by jonator** [comment]
New bridge flow uses wagmi, which should solve this

**Comment by refi93** [comment]
just tried, seems to be solved indeed, thanks 👍
