### ISSUE TITLE
Create Pool Modal for Concentrated Liquidity [500 USDC Reward!]

### ISSUE THREAD

**Issue by MaxMillington** [osmosis-labs/osmosis-frontend#2727]
🐛 Bug Bounty: Fix Needed! 🛠️
Reward: 🏆 500 USDC 🏆

We are excited to announce a bug bounty for third-party developers! If you've got the skills and know-how, here's your chance to earn some 💸 and contribute to our project.

Issue Description 📄

Add modal for creating a pool for concentrated liquidity

Expected Behavior 💡

As a user, when I click in to create a pool, I should see an experience as in the below figma file. 

[Link to Designs](https://www.figma.com/file/kUhJRFf5dkSA477J2NVG1i/Create-Concentrated-Liquidity-Modal?type=design&node-id=15%3A1635&mode=design&t=rfBm5BPCtxD6v9hx-1)
Password: Wosmongton2024

<img width="1041" alt="Screenshot 2024-01-24 at 10 54 24 AM" src="https://github.com/osmosis-labs/osmosis-frontend/assets/11064595/b873ee68-7c5d-4822-82dd-bc84aa519a44">

Requirements for the Bounty 🏁

Submit a pull request with a verified fix to the issue.
The fix should not introduce any new bugs or vulnerabilities.
Code should follow our project's style and contribution guidelines.
Your solution will be reviewed by our team, and the bounty will be awarded upon approval.
How to Claim Your Bounty 💰

Fork our repository.
Create a new branch for your fix.
Submit a pull request to our main branch.
Include detailed information about your fix and how it addresses the issue.

Once reviewed and merged, the 500 USDC will be transferred to your wallet.
We look forward to your contributions and thank you for helping improve our project!

Please Note: All bounty claimants must undergo a KYC (Know Your Customer) process with our finance team to receive the reward. This is a mandatory step to ensure compliance with financial regulations.

PLEASE ALLOW 1 MONTH FOR PAYMENT TO BE RENDERED.

**Comment by ChetanKarwa** [comment]
Hey Max, I would like to work on this.
I also started working on this, but still, I was not able to get much ahead with creating the pool.
Stuck at the first step because the config on creating a new poll gives no assets.
Can you please help me out with how can I get some dummy data with which I can work?

Thank you

**Comment by MaxMillington** [comment]
@ChetanKarwa 

Thanks for starting work!

I'm not quite sure I understand the difficulty however, you should be able to follow the readme and run `yarn build && yarn dev` to run either the app on mainnet, or the app on testnet. You shouldn't need dummy data to run the app.

**Comment by ChetanKarwa** [comment]
Not sure if this is very naive question or not.

I started the app successfully on dev but was stuck here.
So In testnet I'm getting this error.
<img width="1728" alt="image" src="https://github.com/osmosis-labs/osmosis-frontend/assets/46815976/050e3d09-5da8-4414-9668-758677d991cc">
Else I am stuck here without info:
<img width="758" alt="image" src="https://github.com/osmosis-labs/osmosis-frontend/assets/46815976/53452966-a15e-494f-8731-c4f409e0fd7c">

**Comment by MaxMillington** [comment]
@ChetanKarwa in this case, I would recommend stubbing the actual create pools call, since implementing the attached designs shouldn't require any changes to that call (i.e. you can assume it works)

**Comment by MaxMillington** [comment]
@ChetanKarwa both dropdowns should be triggered by a click, like a normal dropdown. The swap fees should be pulled from the Concentrated Liquidity modules params. If you query the CL modules params they will show up.

**Comment by MaxMillington** [comment]
@ChetanKarwa you can follow the designs used in other dropdowns in the app

**Comment by aliraza556** [comment]
Hi @MaxMillington,
This issue is available?

**Comment by MaxMillington** [comment]
@aliraza556 Still available

**Comment by aliraza556** [comment]
Assign me

**Comment by fabryscript** [comment]
Almost implemented here with some small TODOs: #3452

**Comment by MaxMillington** [comment]
thank you @fabryscript
