### ISSUE TITLE
Simulate Gas for Inputs, and deduct fees when swapping using the MAX button [500 USDC Reward!]

### ISSUE THREAD

**Issue by MaxMillington** [osmosis-labs/osmosis-frontend#2733]
🐛 Bug Bounty: Fix Needed! 🛠️
Reward: 🏆 500 USDC 🏆

We are excited to announce a bug bounty for third-party developers! If you've got the skills and know-how, here's your chance to earn some 💸 and contribute to our project.

**Issue Description 📄**

Improve the existing fee estimation method by integrating on our inputs [Keplr's gas simulation implementation](https://github.com/chainapsis/keplr-wallet/blob/93a13dcceb91bea88dd63934d2fa8d1a234ab38c/packages/hooks/src/tx/gas-simulator.ts) or something similar. It should leverage the gas and fee configuration to precisely calculate the necessary transaction fee, taking into account input values. This enhancement aims to offer a more accurate and efficient way to estimate transaction costs, providing a better experience for users.

**Requirements**

1. Integrate Keplr Gas Simulation: Use Keplr's gas simulation to compute the gas costs based on the current gas and fee configurations. Ensure compatibility with our existing system.
2. Handle Input Values: Adapt the function to consider input values in the fee estimation. Evaluate how these values might affect the transaction cost and incorporate them into the calculation.
3. Provide Documentation: Update existing inline documentation (TSDoc) to reflect the changes and new functionalities. Include examples and use cases to assist developers in utilizing the enhanced function.
Acceptance Criteria

- Successful integration of Keplr's gas simulation or something similar into the fee estimation process.
- Accurate calculation of transaction fees, considering input values and configurations.
- Compatibility with existing functionality and systems.
- Comprehensive documentation for the new implementation.

**Risks/Considerations**
- Potential compatibility issues with Keplr's gas simulation.
- Complexity in handling various input values and configurations.
- Ensuring that the enhancement doesn't introduce unexpected behaviors in existing functionalities.

**Dependencies**

- Access to Keplr's [GasSimulator](https://github.com/chainapsis/keplr-wallet/blob/93a13dcceb91bea88dd63934d2fa8d1a234ab38c/packages/hooks/src/tx/gas-simulator.ts) class.
- Use [GasConfig](https://github.com/chainapsis/keplr-wallet/blob/93a13dcceb91bea88dd63934d2fa8d1a234ab38c/packages/hooks/src/tx/gas.ts#L7) and [FeeConfig](https://github.com/chainapsis/keplr-wallet/blob/93a13dcceb91bea88dd63934d2fa8d1a234ab38c/packages/hooks/src/tx/fee.ts#L21) to seamlessly handle conversion between gas and fee.

**Examples**

- Keplr's [useIBCTransferConfig](https://github.com/chainapsis/keplr-wallet/blob/master/packages/hooks/src/ibc/send-ibc-transfer.ts#L24) to see how GasSimulator can be used with AmountConfig. 
- Keplr's [IBC transfer implementation](https://github.com/chainapsis/keplr-wallet/blob/master/packages/extension/src/pages/ibc-transfer/index.tsx#L117) to see how to handle loading states with the gas simulator

**Possible Integration Steps**

1. Update our existing individual account stores to include new methods named makeTx. These methods will be responsible for composing a transaction. The composed transaction object should offer flexibility by providing both simulate and send functions, allowing developers to decide the desired operation on the transaction.
In other words, the makeTx the method will create a transaction object, and within that object, developers will have the option to either simulate the transaction to see potential outcomes or send it to execute the actual transaction. This dual functionality within the composed transaction object provides greater control and flexibility.

2. Look for all useFakeFeeConfig  and update the configs to use the gas simulator.

4. Handle loading states by setting a loading indicator when users press max/half.

Requirements for the Bounty 🏁

Submit a pull request with a verified fix to the issue.
The fix should not introduce any new bugs or vulnerabilities.
Code should follow our project's style and contribution guidelines.
Your solution will be reviewed by our team, and the bounty will be awarded upon approval.
How to Claim Your Bounty 💰

Fork our repository.
Create a new branch for your fix.
Submit a pull request to our main branch.
Include detailed information about your fix and how it addresses the issue.

Once reviewed and merged, the 500 USDC will be transferred to your wallet.
We look forward to your contributions and thank you for helping improve our project!

Please Note: All bounty claimants must undergo a KYC (Know Your Customer) process with our finance team to receive the reward. This is a mandatory step to ensure compliance with financial regulations.

PLEASE ALLOW 1 MONTH FOR PAYMENT TO BE RENDERED.

**Comment by Temidayo32** [comment]
@MaxMillington Can I work on this?

**Comment by MaxMillington** [comment]
@Temidayo32 of course! Thanks!

**Comment by skushagra9** [comment]
Hey, I see this bounty is not assigned, I have relevent experience in the past and would like to work on this bounty

**Comment by MaxMillington** [comment]
@skushagra9 feel free! Thanks !

**Comment by ManyRios** [comment]
Hey @MaxMillington is this bounty and the others still available?

**Comment by MaxMillington** [comment]
@ManyRios still available

**Comment by forbesus** [comment]
@MaxMillington 
this work is still available?

**Comment by MaxMillington** [comment]
@forbesus this one was completed. I'll close now. Thanks!
