### ISSUE TITLE
chore: set up VS code debugger for debugging the application with breakpoints e2e

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/osmosis-frontend#2739]
We need the ability to press a button and start an app with a debugger running for developer productivity.

Acceptance Criteria
- `launch.json` configuration
- I press a button and everything works
- Can stop on breakpoint

**Comment by p0mvn** [comment]
I did some investigations. The closest I could get is being able to set breakpoints in the `web` package only with the following configuration:
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Next.js Node Debug",
            "runtimeExecutable": "${workspaceFolder}/node_modules/next/dist/bin/next",
            "cwd": "${workspaceFolder}/packages/web",
            "console": "integratedTerminal"
        }
    ]
}
```

Opened a discussion in the turbo repo: https://github.com/vercel/turbo/discussions/7135

Sources that I found useful:
- https://github.com/vercel/turbo/discussions/4860
- https://github.com/vercel/turbo/discussions/2639

**Comment by MaxMillington** [comment]
Closing this as most JS devs use the chrome debugger tool to step through code
