### ISSUE TITLE
Search in liquidity pools 

### ISSUE THREAD

**Issue by CyberFFtod** [osmosis-labs/osmosis-frontend#2812]
Search in liquidity pools does not work, and my position in the pool is not displayed correctly

<img width="407" alt="screen 2024-02-16 в 00 53 44" src="https://github.com/osmosis-labs/osmosis-frontend/assets/64408226/092d326e-6adf-4eec-88df-caca8161c06b">

My pools are not empty
<img width="506" alt="screen 2024-02-16 в 00 53 32" src="https://github.com/osmosis-labs/osmosis-frontend/assets/64408226/714c6602-d62f-42fb-a8ca-f595a7c2dfbd">

Searching for a token in liquidity pools produces zero results
<img width="1177" alt="screen 2024-02-16 в 00 54 04" src="https://github.com/osmosis-labs/osmosis-frontend/assets/64408226/5a696e21-d231-43bd-90eb-e0cf73933841">

**Comment by jonator** [comment]
Works
