### ISSUE TITLE
fix: avoid hardcoding pool types

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/osmosis-frontend#2833]
Currently, we hardcode pool types as strings:
https://github.com/osmosis-labs/osmosis-frontend/blob/71528ee78a8396561d070338c9a3462de82661fd/packages/web/server/queries/complex/pools/index.ts#L10-L17

Instead, these should be enum values imported from a single file rather than hardcoded in various locations

**Acceptance Criteria**
- Pool types consolidated in a single file
- Constans are imported everywhere else instead of being hardcoded

**Comment by MaxMillington** [comment]
@p0mvn @jonator prices are migrated now right? Do we still need this issue?

**Comment by jonator** [comment]
Those are the only place they are defined, but the remaining references should be type safe string literals
