### ISSUE TITLE
Levana Geoblocked Request is not cached locally

### ISSUE THREAD

**Issue by ValarDragon** [osmosis-labs/osmosis-frontend#3057]
Try refreshing the frontend a few times with the cache enabled. You will see that the levana geoblocked request is not cached, and is remade on every request. This should ideally hit a local cache for the same input country code if you are coming from the same IP.

**Comment by MaxMillington** [comment]
Turned into a bounty https://github.com/osmosis-labs/osmosis-frontend/issues/3356
