### ISSUE TITLE
Asset selector will not load until long queries complete

### ISSUE THREAD

**Issue by ValarDragon** [osmosis-labs/osmosis-frontend#3061]
The asset selector icon on the Swap page will not load until this query completes `https://app.osmosis.zone/api/edge-trpc-assets/assets.getUserAssets`.

Theres two problems:
- That query takes insanely long in non-EU timexone (1.35s in very good internet in korea)
- We should not be blocked on this query for the asset selector. Its preferrable to have the icon load first, and then have clicking it have a delay. This at least makes the UI feel stable faster, and pipelines the latency for a user click on the selector.

**Comment by MaxMillington** [comment]
@jonator @JoseRFelix @DavideSegullo I think this is no longer an issue right?

**Comment by jonator** [comment]
Yes, overall we have all services multi region now
