### ISSUE TITLE
On swap page, getting the base asset prices should be fetched in parallel not sequence

### ISSUE THREAD

**Issue by ValarDragon** [osmosis-labs/osmosis-frontend#3062]
On the swap page, we load the from assets price first, then when that price response is obtianed, we start the network query to get the to asset's price. We should just request these both asynchronously in parallel. These queries have notable delay.

**Comment by p0mvn** [comment]
@ValarDragon tracking this issue under stability: https://linear.app/osmosis/issue/STABI-106/on-swap-page-getting-the-base-asset-prices-should-be-fetched-in

Please note that [this PR](https://github.com/osmosis-labs/osmosis-frontend/pull/3070) removes getting `toAsset` price by ,instead, computing the out amount fiat asset value from quote's price impact

We, however, are still going to evaluate whether #3070 addresses it in a follow-up to ensure nothing is missed.

I'm going to close this to avoid fragmenting issue fragmentation but please let us know on Linear if you have any follow-up thoughts
