### ISSUE TITLE
Add button "Hide zero balances" at https://app.osmosis.zone/assets

### ISSUE THREAD

**Issue by Antropocosmist** [osmosis-labs/osmosis-frontend#309]
The list of tokens that are available on Osmosis grew up very fast.
Now users need to scroll down the list to long.
If we will add button "Hide Zero Balances" at https://app.osmosis.zone/assets to show to user only tokens with balance - it will be really helpful for many users

**Comment by jonator** [comment]
Pull requests are welcome! This functionality is a WIP on the refactor. Closing as we've already covered this in the refactor tracking issues. Track our progress [here](https://github.com/osmosis-labs/osmosis-frontend/projects/1#card-79022520).
