### ISSUE TITLE
🇸🇻 Multi-language support 

### ISSUE THREAD

**Issue by daniel-farina** [osmosis-labs/osmosis-frontend#312]
I think this is a great opportunity to add multi language support after the refactoring is done.  We don’t have to translate everything right away but having the language files ready for integration would be huge.  I'm sure the community will help us get Osmosis translated as @jonator  mentioned. 

Maybe: 
https://www.npmjs.com/package/react-multi-lang

 @dogemos this would be a great item to add to Keplr’s backlog too.  I think this is really important for mass adoption.

**Comment by samuelstroschein** [comment]
Expressing interest to help osmosis out by easing the process for contributors. I showed @jonator what we are up to some months ago and comment here for visibility. 

We are working on https://github.com/inlang/inlang. Inlang's goal is to streamline localization (translation) of software by providing dev tools and an editor for translators. The editor enables translators, or contributors for OSS projects, to manage translations without mingling around in files.  

We intend to release a usable alpha by November.

**Comment by jonator** [comment]
@samuelstroschein great to hear from you! I've added myself to the beta launch notification- looking forward to seeing how inlang can help us in the future.
