### ISSUE TITLE
I can't run frontend server with `yarn dev`

### ISSUE THREAD

**Issue by forbesus** [osmosis-labs/osmosis-frontend#3209]
![image](https://github.com/osmosis-labs/osmosis-frontend/assets/117654974/449ad123-6d89-4ddf-bba1-1af89747a86e)

here is screenshot 
Could you tell me who is know this problem?

**Comment by forbesus** [comment]
Could you tell me what branch I should fork? @MaxMillington

**Comment by MaxMillington** [comment]
@forbesus stage. Make sure to run build back

**Comment by forbesus** [comment]
![image](https://github.com/osmosis-labs/osmosis-frontend/assets/117654974/20c474a5-6a32-4a9a-bfe3-0fd318ca81e7)

I am still getting same error.
Could you check it? @MaxMillington

**Comment by forbesus** [comment]
![image](https://github.com/osmosis-labs/osmosis-frontend/assets/117654974/aec6c45b-3330-4d92-b8b8-061d11bac039)
Also I check this error is displaying now @MaxMillington

**Comment by MaxMillington** [comment]
@forbesus are you building from the web directory or the root?

**Comment by forbesus** [comment]
I am building on root directory
But I analyzed error and it said error is occurring on `packages/web` so I tried on web directory once

**Comment by forbesus** [comment]
I am getting error on `root` directory exactly @MaxMillington

**Comment by jonator** [comment]
What branch are you on? This type error should be fixed on `stage` branch.

**Comment by forbesus** [comment]
I remove source code on local and re-forked repo again

It work well now 

Thank you for your support @jonator and @MaxMillington

**Comment by forbesus** [comment]
I need one help

Could you tell me how to install new npm module?

@jonator @MaxMillington
