### ISSUE TITLE
GAMM module refactor frontend changes

### ISSUE THREAD

**Issue by dogemos** [osmosis-labs/osmosis-frontend#331]
Running list of breaking changes: [link](https://github.com/osmosis-labs/osmosis/blob/287467103f183305e0baef940c5aef37790e07d0/x/gamm/breaking_changes_notes.md)

We need to ensure that the upcoming breaking changes are accounted for in the frontend:

- [ ]  `PoolAssetsQuery` -> `TotalLiquidity`
  * Pool weight queries need to be queried directly to the pool
- [ ]  `QuerySpotPrice`
  * `TokenInDenom` -> `QuoteAssetDenom`
  * `TokenOutDenom` -> `BaseAssetDenom`
  * Do we use the `withswapfee` param in the frontend?
- [ ]  `JoinPoolNoSwap`
- [ ]  `ExitPool`
- [ ]  `ExitSwapShareAmountIn`

Designs
- [ ] Modify create pool modal to accomodate stableswap pools
- [ ] Figure out how we want to handle pool weights
- [ ] Figure out routing for stableswap pools

**Comment by jonator** [comment]
What's the ETA of the new GAMM module?

**Comment by jonator** [comment]
4/7 meeting- may necessitate some routing changes @Thunnini

**Comment by jonator** [comment]
#372 is related, and specific to refactor

**Comment by jonator** [comment]
5/10 meeting- trying to get proposal on chain May 20

Should sync with @czarcas7ic on working with the release candidate on testnet, to ensure stuff works.

**Comment by czarcas7ic** [comment]
Hey! As soon as an RC gets released we can link and I can provide you a testnet to test whatever front-end things you may need

**Comment by dogemos** [comment]
Closing this to track gamm refactor changes on #372 instead
