### ISSUE TITLE
Ethereum bridge integration to frontend prep work

### ISSUE THREAD

**Issue by dogemos** [osmosis-labs/osmosis-frontend#332]
WIP

- [ ] Finalize user flow ([Figma file](https://www.figma.com/file/hZlR0KWL0V1wLxoggB0ry0/Bridge-Integration-UI-Sketch?node-id=4%3A13730))
- [ ] Finalize design (@victortokaito)
- [ ] Figure out bridge APIs needed (@jonator)
- [ ] Scope out work regarding Ethereum queries and txs (@Thunnini)
- [ ] Connect Ethereum wallet integration

**Comment by jonator** [comment]
Will we have separate designs for pre and post refactor? For pre- would be nice to have a MVP design that's easy to implement. For post- the best design we can come up with.

**Comment by dogemos** [comment]
Yup. Will definitely get both prepared.

**Comment by victortokaito** [comment]
[Figma link to Bridge Design (page 3)](https://www.figma.com/file/hZlR0KWL0V1wLxoggB0ry0/Bridge-Integration-UI-Sketch?node-id=234%3A36064)
