### ISSUE TITLE
Levana Geoblocked Request is not cached locally [200 USDC Reward!]

### ISSUE THREAD

**Issue by MaxMillington** [osmosis-labs/osmosis-frontend#3356]
🐛 Bug Bounty: Tree Shaking Optimization Needed! 🛠️
Reward: 🏆 200 USDC 🏆

We are thrilled to announce a special bug bounty for proficient third-party developers! This is an opportunity to showcase your expertise, make a significant impact, and earn a substantial reward.

Issue Description 📄
Cache Levana Geoblocking Request

Current Behavior ❌
Try refreshing the frontend a few times with the cache enabled. You will see that the levana geoblocked request is not cached, and is remade on every request. This should ideally hit a local cache for the same input country code if you are coming from the same IP.

Expected Behavior 💡
On page refresh from the same IP address, the levana geoblocking request should not be rerun but instead be fetched from the cache

Requirements for the Bounty 🏁

Submit a pull request with a verified solution to optimize tree shaking.
Demonstrate a measurable decrease in the bundle size as a result of your optimization.
Ensure the fix does not introduce any new bugs or vulnerabilities.
Adhere to our project's coding style and contribution guidelines.
Your solution will undergo a thorough review by our team, and the bounty will be awarded upon approval.

How to Claim Your Bounty 💰

Fork our repository.
Create a new branch dedicated to your optimization fix.
Submit a pull request to our main branch with comprehensive details of your optimization strategy and evidence of the reduced bundle size.

Upon review and approval, the 200 USDC will be transferred to your wallet.

Please Note: All bounty claimants must undergo a KYC (Know Your Customer) process with our finance team to receive the reward. This is a mandatory step to ensure compliance with financial regulations.

We eagerly await your innovative solutions and thank you for contributing to the efficiency and performance of our project!

**Comment by ramishj** [comment]
![Uploading Screenshot 2024-06-19 at 11.45.35 PM.png…]()
what might be the reason

**Comment by ramishj** [comment]
<img width="1000" alt="Screenshot 2024-06-19 at 11 45 46 PM" src="https://github.com/osmosis-labs/osmosis-frontend/assets/118445402/9c37e27b-7908-46b1-b650-b5676e7d4b1d">

**Comment by UkuLoskit** [comment]
I'm not sure if this can be really implemented. How would the browser know the current IP? To go by location, you'd need to ask for location permissions, but that is based on the user's consent only.

**Comment by MaxMillington** [comment]
@UkuLoskit you could use something like `https://api.ipify.org?format=json` to get it, but this essentially would mean you have to make that call on every page load instead of the call to Levana. It would only be worth it if the call to `https://api.ipify.org?format=json` was substantially faster than the call to Levana.

@UkuLoskit how about this, could you run some benchmarking between `https://api.ipify.org?format=json` and the levana geoblock call? If you can demonstrate that it would not result in a speed increase to make the change, I'll still pay the bounty

**Comment by UkuLoskit** [comment]
Very simple benchmark:

```
for i in $(seq 1 10); do curl -o /dev/null -s -w 'Total: %{time_total}s\n' "https://geoblocked.levana.finance/"; done
Total: 0.222422s
Total: 0.284780s
Total: 0.274545s
Total: 0.239662s
Total: 0.229956s
Total: 0.288214s
Total: 0.277087s
Total: 0.274759s
Total: 0.242830s
Total: 0.287495s
```
