### ISSUE TITLE
Cache Favicon.ico [200 USDC Reward!]

### ISSUE THREAD

**Issue by MaxMillington** [osmosis-labs/osmosis-frontend#3357]
🐛 Bug Bounty: Tree Shaking Optimization Needed! 🛠️
Reward: 🏆 200 USDC 🏆

We are thrilled to announce a special bug bounty for proficient third-party developers! This is an opportunity to showcase your expertise, make a significant impact, and earn a substantial reward.

Issue Description 📄
Cache Favicon.ico

Current Behavior ❌
Favicon.ico is not cached locally, and it sometimes takes a long time to retrieve

Expected Behavior 💡
This should just be on a local cache with long expiry time.

Requirements for the Bounty 🏁

Submit a pull request with a verified solution to optimize tree shaking.
Demonstrate a measurable decrease in the bundle size as a result of your optimization.
Ensure the fix does not introduce any new bugs or vulnerabilities.
Adhere to our project's coding style and contribution guidelines.
Your solution will undergo a thorough review by our team, and the bounty will be awarded upon approval.

How to Claim Your Bounty 💰

Fork our repository.
Create a new branch dedicated to your optimization fix.
Submit a pull request to our main branch with comprehensive details of your optimization strategy and evidence of the reduced bundle size.

Upon review and approval, the 200 USDC will be transferred to your wallet.

Please Note: All bounty claimants must undergo a KYC (Know Your Customer) process with our finance team to receive the reward. This is a mandatory step to ensure compliance with financial regulations.

We eagerly await your innovative solutions and thank you for contributing to the efficiency and performance of our project!

**Comment by ramishj** [comment]
I want to start working on this issue please assign it to me.
Thank You

**Comment by MaxMillington** [comment]
@ramishj No need to assign. We pay the bounty to the first person who merges a PR to fix the problem. Thanks!

**Comment by ramishj** [comment]
@MaxMillington why im getting this error while building locally 
![Uploading Screenshot 2024-06-23 at 12.04.30 AM.png…]()

**Comment by ramishj** [comment]
<img width="988" alt="Screenshot 2024-06-23 at 12 04 30 AM" src="https://github.com/osmosis-labs/osmosis-frontend/assets/118445402/7218aeaf-e3a6-4c4d-991f-437db88a15e6">
someone tell me how to fix this while build

**Comment by ramishj** [comment]
@CryptoAssassin1 @kamal-sutra 

> <img alt="Screenshot 2024-06-23 at 12 04 30 AM" width="988" src="https://private-user-images.githubusercontent.com/118445402/342385307-7218aeaf-e3a6-4c4d-991f-437db88a15e6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyNDA4MTcsIm5iZiI6MTcxOTI0MDUxNywicGF0aCI6Ii8xMTg0NDU0MDIvMzQyMzg1MzA3LTcyMThhZWFmLWUzYTYtNGM0ZC05OTFmLTQzN2RiODhhMTVlNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyNFQxNDQ4MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNmFmZTY2Y2JlZmQwNGYwZDMzMWQ3ZjlhMzg2YTY3ZWRjZDk0N2MzMTRjNTc2MDI5NzlhOTJkNzQ5MGVmNDVlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.NOr4Qv6SKtmRw8UK5zmaPjntle0ipe7qlH6ZmY70_2k"> someone tell me how to fix this while build

**Comment by MaxMillington** [comment]
@ramishj trying `yarn clean` and then `yarn && yarn build`

**Comment by ramishj** [comment]
> @ramishj trying `yarn clean` and then `yarn && yarn build`

nothing happens

**Comment by MaxMillington** [comment]
Thank you @Myestery
