### ISSUE TITLE
Add OKX Wallet Mobile [500 USDC Reward!]

### ISSUE THREAD

**Issue by MaxMillington** [osmosis-labs/osmosis-frontend#3358]
🐛 Bug Bounty: Fix Needed! 🛠️
Reward: 🏆 500 USDC 🏆

We are excited to announce a bug bounty for third-party developers! If you've got the skills and know-how, here's your chance to earn some 💸 and contribute to our project.

Issue Description 📄
Integrate the OKX Wallet Mobile

Expected Behavior 💡
As a user, I should be able to connect my OKX mobile wallet. We already have the desktop wallet, but not yet mobile.

Information on adding a wallet can be found [here](https://github.com/osmosis-labs/osmosis-frontend/tree/stage/packages/web#adding-a-wallet)

Requirements for the Bounty 🏁

Submit a pull request with a verified fix to the issue.
The fix should not introduce any new bugs or vulnerabilities.
Code should follow our project's style and contribution guidelines.
Your solution will be reviewed by our team, and the bounty will be awarded upon approval.
How to Claim Your Bounty 💰

Fork our repository.
Create a new branch for your fix.
Submit a pull request to our main branch.
Include detailed information about your fix and how it addresses the issue.

Once reviewed and merged, the 500 USDC will be transferred to your wallet.
We look forward to your contributions and thank you for helping improve our project!

Please Note: All bounty claimants must undergo a KYC (Know Your Customer) process with our finance team to receive the reward. This is a mandatory step to ensure compliance with financial regulations.

**Comment by MaxMillington** [comment]
@mawutory yes the mobile version. We already have the desktop version installed.

**Comment by ramishj** [comment]
<img width="1127" alt="Screenshot 2024-07-12 at 4 11 28 PM" src="https://github.com/user-attachments/assets/fe14fdd4-577c-48e5-9f3d-f299ec41130e">
I keep getting this error durig build whats the error

**Comment by ramishj** [comment]
> <img alt="Screenshot 2024-07-12 at 4 11 28 PM" width="1127" src="https://private-user-images.githubusercontent.com/118445402/348231641-fe14fdd4-577c-48e5-9f3d-f299ec41130e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA4NTMxMzAsIm5iZiI6MTcyMDg1MjgzMCwicGF0aCI6Ii8xMTg0NDU0MDIvMzQ4MjMxNjQxLWZlMTRmZGQ0LTU3N2MtNDhlNS05ZjNkLWYyOTllYzQxMTMwZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxM1QwNjQwMzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NTlkNTBlOGFlZmVlN2Y2MzkxOTI1NzcwYmM2NWMwYTE5MjRmYWQ2YmNmYjc0ZWNmZjY3YjdjZmJhMWJkNjJjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.U8X2Ht1AfzSt5xJ3o-AvLPGBc5Ox_GYZhtnvI4Vlk40"> I keep getting this error durig build whats the error

@MaxMillington @kamal-sutra @CryptoAssassin1  can you tell me why its happening

**Comment by MaxMillington** [comment]
@ramishj try running `yarn clean` and starting from scratch

**Comment by ramishj** [comment]
> @ramishj try running `yarn clean` and starting from scratch

nothing happens dude have tried alot of times

**Comment by Dylanb-dev** [comment]
Hi @MaxMillington ,

Is this still available?
