### ISSUE TITLE
Remove concentrated liquidity feature flag from repo [50 USDC Reward!]

### ISSUE THREAD

**Issue by MaxMillington** [osmosis-labs/osmosis-frontend#3359]
🐛 Bug Bounty: Fix Needed! 🛠️
Reward: 🏆 50 USDC 🏆

We are excited to announce a bug bounty for third-party developers! If you've got the skills and know-how, here's your chance to earn some 💸 and contribute to our project.

Issue Description 📄
Remove concentrated liquidity flag from repository.

Expected Behavior 💡
There are still a few places in our repo that have the concentrated liquidity feature flag. Let's delete all these as it is no longer necessary. Also remove from the `useFeatureFlags` hook

Requirements for the Bounty 🏁

Submit a pull request with a verified fix to the issue.
The fix should not introduce any new bugs or vulnerabilities.
Code should follow our project's style and contribution guidelines.
Your solution will be reviewed by our team, and the bounty will be awarded upon approval.
How to Claim Your Bounty 💰

Fork our repository.
Create a new branch for your fix.
Submit a pull request to our main branch.
Include detailed information about your fix and how it addresses the issue.

Once reviewed and merged, the 50 USDC will be transferred to your wallet.
We look forward to your contributions and thank you for helping improve our project!

Please Note: All bounty claimants must undergo a KYC (Know Your Customer) process with our finance team to receive the reward. This is a mandatory step to ensure compliance with financial regulations.

**Comment by ramishj** [comment]
Hi , 
I have created a pull request removing feauture flag hook _(it was used as 161 places)_  usage along with the hook. I have verified it by running the command **$ git grep -n useFeatureFlags**

**Comment by MaxMillington** [comment]
hi @ramishj. To clarify, we don't want to remove all feature flags, just the concentrated liquidity feature flag. We rely on all the other feature flags.

**Comment by ramishj** [comment]
okay i will try again

**Comment by ramishj** [comment]
only featureFlag.concentratedLiquidity and its uses thats it?

**Comment by ramishj** [comment]
I guess its correct this time..
