### ISSUE TITLE
[EPIC] Add mobile support

### ISSUE THREAD

**Issue by jonator** [osmosis-labs/osmosis-frontend#346]
* May need to add `isMobile` hook as we have in pre-refactor
  * Component rearrangement (assets list)
* Tables with 3 columns max
* Ellipsis truncation where needed
* Less padding

First:
- [x] #380

After:
- [x] #368
- [x] #369
- [x] #370
- [x] #371

**Comment by jonator** [comment]
- [ ] Create checklist items and separate issues to split this task by page/UI @delivan

**Comment by jonator** [comment]
@victortokaito Please link a Figma for an updated mobile design.

**Comment by victortokaito** [comment]
[Figma Link to mobile UI](https://www.figma.com/file/UXgL2cPiw5I4GALDOodfCy/Osmosis-Web-(Master-File)?node-id=408%3A1394)
