### ISSUE TITLE
Have a visual indicator that an asset's deposit/withdrawal buttons lead to an external website

### ISSUE THREAD

**Issue by sunnya97** [osmosis-labs/osmosis-frontend#352]
See: https://github.com/osmosis-labs/osmosis-frontend/pull/294#issuecomment-1087007557

**Comment by victortokaito** [comment]
Hey, we have what this looks like in the figma. Are there assets that would use this that are live on Frontier? 

Misunderstood and thought this was related to #332

**Comment by victortokaito** [comment]
<img width="1100" alt="Screen Shot 2022-04-08 at 9 55 19 AM" src="https://user-images.githubusercontent.com/39136683/162487400-24fc4cc0-d52b-4c89-b476-f077e5d7aeb6.png">

Link [here](https://www.figma.com/file/wQjMyxY0EnEk29gBzGDMe5/Osmosis-Component?node-id=4609%3A2451), ready to be implemented.

**Comment by victortokaito** [comment]
![image](https://user-images.githubusercontent.com/39136683/164316522-f7f5eb28-7311-4292-9aa4-b2588fc6c72d.png)

We have a few axelar assets on frontier that could use the external link. Is there a way to automate this–or is it all manual? @JeremyParish69 @jonator

**Comment by jonator** [comment]
Ah. Simple. Should I prioritize this and add the visual component? @victortokaito

**Comment by victortokaito** [comment]
I was thinking of marking this lower-priority for whenever you can get to it. It's more of an enhancement (since it's still functional without). I think refactor takes priority.

**Comment by jonator** [comment]
Done: https://github.com/osmosis-labs/osmosis-frontend/commit/4a11f4b9acebc951d7d152dbbca9b6b2d71d6da7
