### ISSUE TITLE
🚀 Final merge + regression test + polish

### ISSUE THREAD

**Issue by jonator** [osmosis-labs/osmosis-frontend#362]
Close this [issue](https://github.com/osmosis-labs/osmosis-frontend/issues/163) by merging refactor➡️master branches!

Checklist before merge:
- [x] Add updated `README.md` and `404.tsx`
- [x] Ensure rows of the `<Table />` component only have hover styling if `onClick` is supplied for rows
- [x] #437 
- [x] "Sign out" does not work ~~(@victortokaito should this be "disconnect wallet" instead?)~~
- [x] "Connect wallet" on ibc dialog does not work
- [x] Prevent Osmosis queries from running on non-Osmosis chains
- [ ] ~~Add dockerized local net setup, with local net detection in watch server~~ (creating icebox issue to let us add this later if we really need it)
- [x] Add `useConnectWalletModalRedirect` to pool detail modals. This easily allows users to first connect Keplr before performing an account action (sending a msg) within a pool detail page.
- [x] Complete any quick wins in Next.js [go to production docs](https://nextjs.org/docs/going-to-production)
- [x] Add [`CODEOWNERS`](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners) for config files to jeremy parish 
- [ ] #477 
- [x] Toggle pool column header should remove sort option (ascending, descending, default)
- [x] Add `isUnstable` functionality 
- [x] Fix remove liquidity 100% & slider

After ALL other refactor tasks merged:
- [ ] ~~Clean up / trim file imports by creating comprehensive index in components folder~~
- [x] Update `config.ts` for `app` and `frontier`. Test asset configs accordingly. ([convo with jeremy](https://osmosis-network.slack.com/archives/D037PHTDREG/p1652123551151809))
- [x] Update theme for `frontier`
- [ ] Remove `vercel.sh`
- [x] Add external link UI for frontier (see https://github.com/osmosis-labs/osmosis-frontend/commit/4a11f4b9acebc951d7d152dbbca9b6b2d71d6da7)
- [ ] @JeremyParish69 sync sync main/frontier config/assets into refactor
- [ ] Fix next/images
- [ ] Fix trade page swap query params and pool detail (consider using `getStaticProps`)

**Comment by victortokaito** [comment]
- [ ] review/troubleshoot "Superfluid Pools" grid
- [ ] enable hover interaction on `<Table >` component (e.g. SFS validator selection display)

**Comment by victortokaito** [comment]
re: @jonator I think "sign out" while not technically accurate works as a familiar metaphor 👍

**Comment by jonator** [comment]
![Osmosis-Vision](https://user-images.githubusercontent.com/4606373/166279061-0a84a577-164f-40e8-94f9-b6b5c6f76e3f.png)

Uploading osmosis vision PNG for README

**Comment by jonator** [comment]
Bundle analysis results:
```
Page                                       Size     First Load JS
┌ ○ / (1006 ms)                            2.69 kB        1.77 MB
├   /_app                                  0 B            1.77 MB
├ ○ /404 (983 ms)                          380 B          1.77 MB
├ ○ /500                                   385 B          1.77 MB
├ ○ /assets                                3.93 kB        1.78 MB
├ ○ /pool/[id]                             5.75 kB        1.78 MB
└ ○ /pools (1020 ms)                       107 kB         1.88 MB
+ First Load JS shared by all              1.77 MB
  ├ chunks/framework-fd865f22cad73a01.js   42 kB
  ├ chunks/main-5bf8c240bbed74bf.js        28.3 kB
  ├ chunks/pages/_app-33acae50087b9e1b.js  1.7 MB
  ├ chunks/webpack-c66a1cc0a3689c22.js     892 B
  └ css/47c8e6b01062bc7b.css               10.4 kB
```

1.7mb is a bit high. Will look into opportunities for dynamic loading.

**Comment by jonator** [comment]
Partially completed #359, added initial SSR rendering for pools page. Features:
* 10s cache
* Only gets SSR props for initial pools page load. If you implement `getServerSideProps` for a page, Next.js will make an API request to update data when user navigates back to page vs initial SSR HTML generation. This initial approach returns a `pools.json` with `null` for data if not initial load. These requests are synchronous and slow things down slightly.

**Comment by jonator** [comment]
Closing in favor of these tracking issues:

https://github.com/osmosis-labs/osmosis-frontend/issues/518
https://github.com/osmosis-labs/osmosis-frontend/issues/517
