### ISSUE TITLE
Update new GAMM refactor messages

### ISSUE THREAD

**Issue by daniel-farina** [osmosis-labs/osmosis-frontend#372]
Blocked by
- [ ] https://github.com/osmosis-labs/osmosis/issues/1050

**Comment by jonator** [comment]
Our goal: complete + deploy refactor in time for these new messages to be added to mainnet.

**Comment by dogemos** [comment]
Running list of breaking changes: [link](https://github.com/osmosis-labs/osmosis/blob/287467103f183305e0baef940c5aef37790e07d0/x/gamm/breaking_changes_notes.md)

We need to ensure that the upcoming breaking changes are accounted for in the frontend:

- [ ]  `PoolAssetsQuery` -> `TotalLiquidity`
  * Pool weight queries need to be queried directly to the pool
- [ ]  `QuerySpotPrice`
  * `TokenInDenom` -> `QuoteAssetDenom`
  * `TokenOutDenom` -> `BaseAssetDenom`
  * Do we use the `withswapfee` param in the frontend?
- [ ]  `JoinPoolNoSwap`
- [ ]  `ExitPool`
- [ ]  `ExitSwapShareAmountIn`

Designs
- [ ] Modify create pool modal to accomodate stableswap pools (Josh)
- [ ] Figure out how we want to handle pool weights (Josh)
- [ ] Figure out routing for stableswap pools (Josh)
