### ISSUE TITLE
Allow fee selection by users

### ISSUE THREAD

**Issue by victortokaito** [osmosis-labs/osmosis-frontend#377]
https://www.figma.com/file/wQjMyxY0EnEk29gBzGDMe5/Osmosis-Component?node-id=6410%3A26484

Users are currently able to set gas manually in Keplr, but not in Osmosis. We want to enable gas fee selection on the in-app swap modals especially [to deal with 0-fee spams](https://hackmd.io/@osmosis/r12CVrWG9).

**Comment by jonator** [comment]
@dogemos Could this include work to make fees payable in any token? I've heard it already works on chain, but is just usable via the CLI for now.

Which begs the question- should we also remove the 0 fee option to drive more protocol revenue? That's a big Q worth discussing with the whole team.

**Comment by victortokaito** [comment]
@jonator I think the goal was to increase volume, # of users, and user enjoyment before turning on fees. 

Would still like to see this implemented, as it allows users to account for gas-fee selection before it's automatically subtracted in the Keplr signing. This will better reflect an estimate of all included fees (and that "gas" is a user-selected fee)–something Syed mentioned hasn't been reflected to users.

**Comment by victortokaito** [comment]
@syed8rahman what do you think about including this in the new 'transaction summary' expandable dropdown? ^for reasons above, could be more informative for users as to why gas amounts are changing
