### ISSUE TITLE
Randomise Superfluid Staking Validator selection display

### ISSUE THREAD

**Issue by JohnnyWyles** [osmosis-labs/osmosis-frontend#385]
The display of available superfluid validators currently shows a user's existing delegated validators first followed by an alphabetised list of all other validators.

Due to this, the validators with the names appearing earliest in the list are gaining large amounts of delegations due to LPers not caring which validator they choose.

The validator [#decentralisehk](https://www.mintscan.io/osmosis/validators/osmovaloper1m73mgwn3cm2e8x9a9axa0kw8nqz8a492vg4hp4 ) has around 241k OSMO in delegations on the 28th February when superfluid staking launched. 
 3 Days later they had 805k OSMO in delegations from around 1000 SFS delegations. 
 The launch of the OSMO/UST and OSMO/LUNA pools gave them a similar leap from 938k OSMO to 1.2m OSMO in an additional 2200 SFS delegations.

Recently, another validator has noticed this and adjusted their name to become to top validator on this list: [#1🇨🇭 Vortex.live 🟢](https://www.mintscan.io/osmosis/validators/osmovaloper19fec46jadzr4y6gd596kkf8sskm7eyq32kkwc7)
This increased them from having 5 delegators on the 5th April to 110 delegators on the 7th:
![Screen_Shot_2022-04-11_at_3 03 21_PM](https://user-images.githubusercontent.com/97029546/163207850-7a279d12-e10e-4c16-b74b-c35136d2efb1.png)

This may escalate into validators attempting to position first on this list to get this boost through no other merit.  Randomising the extracted list rather than sorting would resolve this and ensure that delegators just picking the top selection picked a different validator every time.

**Comment by jonator** [comment]
@victortokaito what are your thoughts? I could easily add this to the refactor. I'm working on this portion right now.

**Comment by victortokaito** [comment]
Is Delivan [working on this](https://osmosis-network.slack.com/archives/C02BNJYSJEB/p1649098194835879?thread_ts=1648663468.651099&cid=C02BNJYSJEB)? Guess it's a good time to create an issue either way–thank you Jeremy for github issue tracking.

**Comment by victortokaito** [comment]
Thank you Johnny*

**Comment by delivan** [comment]
No I'm not. I might do this for Keplr dashboard.

**Comment by JohnnyWyles** [comment]
> @victortokaito No I'm not. I might do this for Keplr dashboard.

I was actually planning on raising a related issue over there too about potentially displaying the 33% voting power boundary.  My personal favourite implementation was over on https://solanabeach.io/validators but wanted to flesh out my reasoning before posting.

**Comment by jonator** [comment]
Closing because this was implemented in the refactor
