### ISSUE TITLE
Move to ts-proto

### ISSUE THREAD

**Issue by dogemos** [osmosis-labs/osmosis-frontend#388]
Move proto message generation to ts-proto

https://github.com/chainapsis/keplr-wallet/tree/master/packages/proto-types

https://github.com/confio/cosmjs-types

Ts-proto creates typescript files, but protobufjs creates javascript files. Because of this, in a typescript environment ts-proto creates more idiomatic code.

One big reason to move away from protobufjs is golang's protobuf compiler returns a different result in json encode, which can lead to potential issues when creating signDoc.

This can be resolved by migrating to ts-proto.

**Comment by jonator** [comment]
Why not use telescope 👀
