### ISSUE TITLE
Terms: Move to connect wallet

### ISSUE THREAD

**Issue by victortokaito** [osmosis-labs/osmosis-frontend#389]
New Osmosis users are greeted by a scary wall of text. Gradually introduce the full warning text to users by presenting [collapsible accordion-style dropdowns instead.](https://www.figma.com/file/UXgL2cPiw5I4GALDOodfCy/Osmosis-Web-(Master-File)?node-id=975%3A20881)

**Comment by jonator** [comment]
Adding the refactor label since we'll be rebuilding the UI anyways

**Comment by jonator** [comment]
Was checkout out how [uniswap](https://app.uniswap.org/#/swap?chain=mainnet) does it: we could instead show the disclaimer when a user first goes to connect a wallet. This may put off less users initially, and we know they won't be able to take any harmful actions without a wallet connected.

**Comment by jonator** [comment]
6/7 meeting - we should instead copy uniswap, show a link to disclaimer and tell user by connecting wallet they accept the disclaimer
