### ISSUE TITLE
add filter in 'pool' page to show pairs of a user-selected token

### ISSUE THREAD

**Issue by jblbit** [osmosis-labs/osmosis-frontend#396]
add filter in 'pool' page to show pairs of a user-selected token

e.g. in 'pool' page, users (e.g. I myself) want see only the pairs with 'akt'. Right now, I have to search with browser "control + f", would be nice to support this filtering natively on osmosis frontend

**Comment by jonator** [comment]
Thanks for the feedback! We will be including this exact functionality in the refactor- coming very soon. It will include both filter/search & sort functionality for pools and assets!

**Comment by jblbit** [comment]
nice! thanks
