### ISSUE TITLE
New user: link to chrome ext page if Keplr not installed

### ISSUE THREAD

**Issue by jonator** [osmosis-labs/osmosis-frontend#412]
If a new user explores our app without knowing about or having Keplr installed, they may not know that it is an extension that they use to interact with the chain.

**Comment by jonator** [comment]
4/27 meeting- Med. priority due to recent scammy results when googling "keplr" wallet to install

**Comment by CMarshall92** [comment]
I have raised a PR that makes the non install flow a bit clearer for a user that doesnt have keplr installed in the browser. You can find it at the following link. [PR here](https://github.com/osmosis-labs/osmosis-frontend/pull/613)

**Comment by CMarshall92** [comment]
Let me know if its something that works cant see any of the designs if there are any so i've kind of went with what the scan QR flow looks like for consistency
