### ISSUE TITLE
User research

### ISSUE THREAD

**Issue by syed8rahman** [osmosis-labs/osmosis-frontend#418]
Connect with a handful of super users to discuss the dashboard with. ~6 

- Understand their current behaviors
- Favorite dashboards
- Necessary information 
- Hierarchy of information

[Research notes and testing script are located here. ](https://www.notion.so/osmosiszone/Dashboard-Research-245d44e961f44435956278017090d45e)

[Findings will be collected in FigJam. ](https://www.figma.com/file/WaF6QN9Qb0TV1LCGY6cEi9/Personalized-Dashboard-Sprint?node-id=1%3A1193)

**Comment by jonator** [comment]
6/28 sprint planning- 

We should add these to our user research:
* Notification center #587 
* Batching functionality (for ledger users esp.), could be a good thing to add to Keplr, not just Osmosis FE #638 
* Incentives icons #571 (Victor: should be cautions about what is considered external incentive, spamming)

**Comment by jonator** [comment]
Closing since we've started tracking research/design tasks in Notion
