### ISSUE TITLE
Add IBC transfer status table

### ISSUE THREAD

**Issue by jonator** [osmosis-labs/osmosis-frontend#427]
We should show the status of a users transactions on the bottom of the assets page as we did pre-refactor. We can't depend on linking to mintscan since not all chains on Osmosis are supported there.

At launch June '21, we didn't have this feature and it was highly requested.

**Comment by jonator** [comment]
@victortokaito I believe in our last meeting you thought there should be no changes to the design/contents of the IBC transfer table?

**Comment by victortokaito** [comment]
As mentioned in slack: 
> Yeah, this looks pretty similar to the table component, has the tx hash, a link out to mintscan, amount, and status. The one thing I think we can possibly remove is the ibc sequence #.

Send it Jon 🚀

**Comment by jonator** [comment]
@victortokaito Current state. LMK if this is looks good to you. Regarding font sizes, spacing, etc.

![Screen Shot 2022-05-12 at 11 20 45 AM](https://user-images.githubusercontent.com/4606373/168142669-1878bbc2-7b70-4573-ab41-22e98e036ba3.png)

**Comment by victortokaito** [comment]
Is it possible to align the tx hash to the column header? All other columns look good. 

Can I build this commit to see the table in the context of the assets page?

**Comment by jonator** [comment]
You can, but it will only appear if there are IBC transfers cached in the browser within the past 3 days
