### ISSUE TITLE
Blank screens on Safari

### ISSUE THREAD

**Issue by jonator** [osmosis-labs/osmosis-frontend#437]
### Problem

The extension KV store, `ExtensionKVStore`, is causing a full app crash (blank screen) on Safari (mobile and desktop). 

`TypeError: undefined is not an object (evaluating 'browser.storage.local')`

extension.ts:
```
import { BaseKVStore } from "./base";
import { KVStoreProvider } from "./interface";

const ExtensionKVStoreProvider: KVStoreProvider = {
  get:
    typeof browser !== "undefined" <=====err
      ? browser.storage.local.get
      : (undefined as any),
  set:
    typeof browser !== "undefined" <=====err
      ? browser.storage.local.set
      : (undefined as any),
};

export class ExtensionKVStore extends BaseKVStore {
  constructor(prefix: string) {
    super(ExtensionKVStoreProvider, prefix);
  }
}
```

This seems to have recently surfaced, as I remember accessing the app from Safari on mobile and desktop not too long ago. Interestingly, it still works in the embedded Keplr wallet browser (WebKit). This affects deployments from `frontier`, `master`, and `refactor`.

### Proposed Solution
From my brief investigation, it appears some extension-only KV logic is running in the web apps. The check for `browser` functions as expected on Chrome where `browser` is `undefined`, however on Safari `browser` is defined yet has no member `storage`. We should add an additional check at this level, or at a higher level prevent any `ExtensionKV` logic from running within the window.

**Comment by Thunnini** [comment]
The `browser` is used as a polyfill to support both chromium and firefox. (Nevertheless, firefox is not supported.) I thought that there would be no browser in safari, but it seems to exist regardless of extension api. This is a problem on @keplr-wallet/* libraries. We will fix it in the next version.

**Comment by jonator** [comment]
Closing due to bug in Keplr

**Comment by jonator** [comment]
https://github.com/chainapsis/keplr-wallet/issues/378

Keplr tracks & fixes here ^
