### ISSUE TITLE
Express Osmosis Time more clearly

### ISSUE THREAD

**Issue by faddat** [osmosis-labs/osmosis-frontend#44]
Did you realize that we have gone and created a time zone?

Well, a while ago I noticed a glorious synchronization with other participants in the osmosis net work, because of epoch time. Currently, we are expressing time until epoch.

However, given that we will be ascendant, and that we are ambitious, I wish to propose Osmosis Time, or OZT "Osmosis Zone Time" or... (suggestions welcome here.

Ok, so for me, Epoch is midnight, I'm GMT+7.

Osmosis Time:

Days begin at epoch and end at the next epoch.

before epoch, the time is:

23:59:59

Epoch time is:
00:00:00

.... and that is the beginning of a new day.

Expressing this concept clearly, and using OTZ throughout the community may enhance the odd synchronicity benefits of OT.

Due to a lack of murderous stupidity in our community, OT has no concept of daylight savings time.

NB:  OT !=GMT+7

it is instead a clean break away from current time-related silliness plaguing the world.

**Comment by dogemos** [comment]
i think it's an interesting idea but maybe a bit too crazy to pull off at this time.

let's close this one for now and revisit once osmosis time becomes more of a convention around the world 😅
