### ISSUE TITLE
Pool page is always very slow in loading

### ISSUE THREAD

**Issue by RowanUtrecht** [osmosis-labs/osmosis-frontend#455]
The current pool page is very slow in load. This has a couple of reasons
- It loads all my own pools
- It loads all pools with incentives
- It loads a tabel with all pools.

And the loading is especially slow since my pools and the pools with incentives need to wait on an APR calculation

Solution:
Only show my own pools. That's in the end what most people would need more then 90% of the times they visit the pool page.
Add a button to show all pools, and then start loading the rest of the pools.

**Comment by jonator** [comment]
Closing as dup of #359. Thanks for the feedback. We're about to release the refactor which should be slightly faster with Next.js. However, once we implement 359, the pools page will start to be loaded on the server and cached. Then, the pools page should load nearly instantly.
