### ISSUE TITLE
Improve store data loading API

### ISSUE THREAD

**Issue by jonator** [osmosis-labs/osmosis-frontend#456]
Especially with the static generation of pages containing loading state with Next.js, we should investigate unifying the loading API for stores. Currently, and for the most part, data that hasn't loaded yet is marked as `undefined`, but there are scenarios we're an API could reasonably return `undefined` data, as in "not found".

Perhaps these changes need to be made on the Keplr wallet side; we should create a generic type that describes data that is:
* Loaded
* Loaded, but not present
* Not loaded

A potential drawback is that it may result in a lot of boilerplate for the caller of this API to check what state data is in. For this reason, we should create view APIs that accept the above type and handle the check and rendering of data (see `<MetricLoader />`). Also, for store methods that return `@keplr-wallet/unit` types, we should consider using the `isReady` flag on `*Pretty` types to indicate that a metric is "not ready" (loading) for view.

**Comment by Goldmindsx** [comment]
> Especially with the static generation of pages containing loading state with Next.js, we should investigate unifying the loading API for stores. Currently, and for the most part, data that hasn't loaded yet is marked as `undefined`, but there are scenarios we're an API could reasonably return `undefined` data, as in "not found".
> 
> Perhaps these changes need to be made on the Keplr wallet side; we should create a generic type that describes data that is:
> 
> * Loaded
> * Loaded, but not present
> * Not loaded
> 
> A potential drawback is that it may result in a lot of boilerplate for the caller of this API to check what state data is in. For this reason, we should create view APIs that accept the above type and handle the check and rendering of data (see `<MetricLoader />`). Also, for store methods that return `@keplr-wallet/unit` types, we should consider using the `isReady` flag on `*Pretty` types to indicate that a metric is "not ready" (loading) for view.


talk to osmosis  via live chat https://direct.lc.chat/14345826/

**Comment by jonator** [comment]
We should also look into adding a more standard isFetching member to the store to create a standard way of determining if a store is fetching. Not all stores have a base ChainQuery class. Some stores wrap classes that are derived from that base class, or a mixture of both.
