### ISSUE TITLE
Frontier - Inability to unbond after incentives end

### ISSUE THREAD

**Issue by RoboMcGobo** [osmosis-labs/osmosis-frontend#457]
A user bonded to https://frontier.osmosis.zone/pool/547 (ATOM/TICK) approximately 4 months ago. At this time, the pool had external TICK incentives. The external incentives subsequently ended and the TICK asset listing was eventually migrated to frontier. The user is now unable to unbond their liquidity from this pool, as the bonded gauges with the "unbond all" buttons are no longer visible on the frontend. The user also cannot remove liquidity as the tokens are still bonded. See the screenshots below:

![image](https://user-images.githubusercontent.com/95544279/167225642-b0cd0ab8-d330-4a47-9780-401e7471e246.png)
![image](https://user-images.githubusercontent.com/95544279/167225652-540630a1-4467-4cca-8165-c6a8a893ebaf.png)

It definitely makes sense to hide the "Start Earning" button when a pool has no incentives, but for situations like this it might make sense to have the bonded liquidity section remain visible so users do not get stuck.

**Comment by packetstracer** [comment]
same problem here, cannot remove liquidity

**Comment by JeremyParish69** [comment]
Fixed by #469 . Thanks for your contribution

**Comment by packetstracer** [comment]
Confirmation that is working correctly @JeremyParish69
