### ISSUE TITLE
Superfluid Indicator on Pool Card view

### ISSUE THREAD

**Issue by thecryptodrive** [osmosis-labs/osmosis-frontend#474]
Would be useful to be able to see at a glance on the grid view which pools have superfluid, especially of you have a lot of pools and want to double-check if you have enabled superfluid.

![image](https://user-images.githubusercontent.com/22358264/167544471-9a00a2a7-d6e5-4e40-a3fb-7b8f7bf63960.png)
 
 A simple indicator like this would work, but would be nice to also indicate whether you have enabled it or not, maybe a tickbox next to the purple flask icon?
 
Ricardo | Notional

**Comment by jonator** [comment]
5/10 meeting - We discussed this as a clearer way to show that a pool is superfluid vs the stroke. In that case, this icon would not show that you have a superfluid position, just that a pool is superfluid.

**Comment by victortokaito** [comment]
Let's ship refactor with just #477 card modifications and icebox this for now.

**Comment by jonator** [comment]
6/7 meeting - We will do this, but @victortokaito we'll need a new design for the new pool cards.

**Comment by thecryptodrive** [comment]
Awesome looking forward to the new card design

Ricardo | Notional

**Comment by victortokaito** [comment]
Hi Ricardo, we are putting this on hold as we feel adding icons to each superfluid card could be redundant and visually distracting (especially on mobile). Do you feel that the "Superfluid Pools" title + stroke is contextually sufficient?

<img width="1728" alt="Screen Shot 2022-06-29 at 12 53 05 PM" src="https://user-images.githubusercontent.com/39136683/176532136-d166941a-0d81-490f-979d-ec431b33ec6b.png">
.

**Comment by thecryptodrive** [comment]
Hi sorry I missed this comment, the Title is fine but it still doesn't tell me which of My Pools are superfluid and may be requiring my attention to enable it. I would have to go through each one to find out, if I have 20 pools it can be alot.
