### ISSUE TITLE
Cards modification (mobile)

### ISSUE THREAD

**Issue by victortokaito** [osmosis-labs/osmosis-frontend#477]
Implement changes based on nonce ux feedback.
- increasing vertical space
- reviewing visual hierarchy of metrics
- addition of pool # indicator on mobile

- [ ] review: new cards for My Pools + condensed cards for generalized pools (or new cards only)

**Comment by jonator** [comment]
@victortokaito Please add a Figma link to the relevant frame once design is done

**Comment by victortokaito** [comment]
### [Figma link to modified cards:](https://www.figma.com/file/UXgL2cPiw5I4GALDOodfCy/Osmosis-Web-(Master-File)?node-id=1342%3A25728)
• We're using expanded cards here. 
• The condensed cards would require a few more changes if they were to be shown alongside the expanded cards (pool indicators are presented differently and would require removing them for consistency). See figma comment for more details.

Also, please note the use of "[mobile switch" component](https://www.figma.com/file/wQjMyxY0EnEk29gBzGDMe5/Osmosis-Component?node-id=3762%3A14625) aka toggle slider. This one (28x18px) is smaller than the desktop version (52x32px).
<img width="749" alt="Screen Shot 2022-05-12 at 11 34 28 AM" src="https://user-images.githubusercontent.com/39136683/168144894-b9e84f02-2749-4663-9e1c-b073608af87d.png">

**Comment by jonator** [comment]
@victortokaito I added this to `pre-merge` branch. Check it out and LMK what you think and I'll close this

**Comment by victortokaito** [comment]
<img width="353" alt="Screen Shot 2022-05-13 at 2 06 36 PM" src="https://user-images.githubusercontent.com/39136683/168389766-ca9f33bf-ef00-42ec-8f31-38473de18ce3.png">

Latest commit on pre-merge, shows switch to still be 48x32px.

Have expanded cards been implemented? This is what I'm seeing.

**Comment by victortokaito** [comment]
<img width="359" alt="Screen Shot 2022-05-13 at 2 07 05 PM" src="https://user-images.githubusercontent.com/39136683/168391008-00d5e70c-43c1-4d8b-a810-5052818dd6e2.png">

Please space out category selector tabs to be 2.5 rem (~40px) apart.

**Comment by victortokaito** [comment]
<img width="363" alt="Screen Shot 2022-05-13 at 2 33 45 PM" src="https://user-images.githubusercontent.com/39136683/168392593-29a2bced-1dde-4c4e-abc7-8fde45ede490.png">


- [ ] Please set category selector + text for "Superfluid Pools" to SFS color provided.

<img width="816" alt="Screen Shot 2022-05-13 at 2 28 39 PM" src="https://user-images.githubusercontent.com/39136683/168391978-55c8c4a4-6226-4c7a-b128-d058a8362660.png">

**Comment by jonator** [comment]
> Latest commit on pre-merge, shows switch to still be 48x32px.
> 
> Have expanded cards been implemented? This is what I'm seeing.

You sure? The code is updated. Perhaps try CMD+SHIFT+R.

**Comment by jonator** [comment]
@victortokaito Updated: https://github.com/osmosis-labs/osmosis-frontend/pull/488/commits/358f3f22f3608e7d1dd85303c569b76e2a53d5c0
