### ISSUE TITLE
Add local net

### ISSUE THREAD

**Issue by jonator** [osmosis-labs/osmosis-frontend#486]
As we had with the pre-refactor frontend, we should add a dockerized local net setup to help us test. It should work the same as it did in pre-refactor.

Putting in icebox for now to let us track dev should we need a local net later. This may not be needed as we can point to a testnet now anyways.

**Comment by jonator** [comment]
6/28 sprint planning-

- [ ] @jonator Need to fix superfluid tests- approve osmo as SFS stakeable in LocalOsmosis genesis state.

**Comment by syed8rahman** [comment]
Should merge to master
