### ISSUE TITLE
Deposit/withdraw columns > single transfer column + modal

### ISSUE THREAD

**Issue by jonator** [osmosis-labs/osmosis-frontend#503]
We should consider removing the deposit/withdraw columns and using a single column with a "transfer" button. That would allow us to open a modal and guide the user through whatever method of transfer is relevant (IBC, bridge, wallet, external link, etc). Would also be a great place to acknowledge relayer issues or other problems related to transfer.

**Comment by Goldmindsx** [comment]
> We should consider removing the deposit/withdraw columns and using a single column with a "transfer" button. That would allow us to open a modal and guide the user through whatever method of transfer is relevant (IBC, bridge, wallet, external link, etc). Would also be a great place to acknowledge relayer issues or other problems related to transfer.


talk to osmosis  via live chat https://direct.lc.chat/14345826/
