### ISSUE TITLE
Cosmetic polishing

### ISSUE THREAD

**Issue by jonator** [osmosis-labs/osmosis-frontend#517]
Non-critical visual issues to be fixed post-refactor (as time permits). Please add a comment w/ checkboxes for each issue you find. Please edit your comment if you wish to add more issues later. Please include screenshots if possible.

**Comment by jonator** [comment]
- [ ] #477

**Comment by jonator** [comment]
>  are we still showing 3 metrics per card in the mobile version?

Currently showing 2

**Comment by delivan** [comment]
- [ ] On create new pool dialog, Token ratio is set 101% when adding just one token and clicking 100% button
- [ ] max width of page container looks small than the design

**Comment by jonator** [comment]
> max width of page container looks small than the design

Are you talking about `max-w-container`? I believe @victortokaito @syed8rahman and I decided to decrease that when messing with the card grids. @victortokaito think you could sync the design? It's `70rem` or `1120px`

**Comment by dogemos** [comment]
Adding a few things to the list here!

- [ ] Pool card width is too small, causing inconsistent line breaks
   - ![image](https://user-images.githubusercontent.com/42988601/171733916-8a805149-b7e8-45bf-9952-a4786a8124d9.png)

- [ ] Modify 'pool liquidity' to 'my liquidity'
   -![image](https://user-images.githubusercontent.com/42988601/171733961-bdd24462-8b79-49db-820f-7b6e1f6aecdb.png)

- [ ] Increase the reward distribution countdown number text size to match other numbers
   - ![image](https://user-images.githubusercontent.com/42988601/171734089-85196071-9fbb-4fa3-9b47-3640ff9c1339.png)

**Comment by jonator** [comment]
@dogemos @victortokaito 

> Pool card width is too small, causing inconsistent line breaks

Victor and I have talked a lot about this. We've found that we will need to allow pool names to wrap, given that pools can have denoms up to 6 characters that I've seen. My way of improving this was to vertically spread all card content evenly on the card, which can be seen in the PR [Vercel preview](https://osmosis-frontend-git-jon-cosmetic-osmo-labs.vercel.app/) for this issue. I think another way to address this could be to have the green line and the metrics hug the bottom of the card, and the only resizable portion would be the icons and the denoms on the top portion.

> Modify 'pool liquidity' to 'my liquidity'

Is this for the pools page or assets page? IMO for the pools page it makes more sense to show pool liquidity over user liquidity, and for the assets page the other way around. In other words, the pools page is user agnostic, the assets page shows pools but from a "user assets" perspective.

**Comment by jonator** [comment]
@dogemos to prevent blocking deployment, I'll close this issue and merge the PR. We can discuss and revisit these later as a new issue.

**Comment by victortokaito** [comment]
@jonator I think showing 'pool liquidity' makes sense for more general pools that a user hasn't LP'ed into yet. 

But maybe we can use 'my liquidity' for the **"My Pools"** section to show users how much they have LP'd?

**Comment by victortokaito** [comment]
Added some old notes for how to prevent name wrapping -> cosmetic v2
