### ISSUE TITLE
Bug bash

### ISSUE THREAD

**Issue by jonator** [osmosis-labs/osmosis-frontend#518]
Critical functional problems that must be fixed before refactor is merged. Please add a comment with checkboxes for each issue you find, and edit the comment if you find issues later.

**Comment by jonator** [comment]
- [ ] Issues with `next/image`s not loading
- [ ] Token swap query params
  - [ ] Sometimes don't get set on initial load (consider `getStaticProps`)
  - [ ] Handle case of `to` and `from` being same token
  - [ ] Make default tokens configurable in `/config/`
- [ ] Sometimes pool detail page initial load incorrectly redirects to `/pools`

**Comment by delivan** [comment]
- [ ] amount is shrinking whenever switching in and out token on trade clipboard

**Comment by jonator** [comment]
> Amount is shrinking on trade clipboard whenever switching in and out

This is what the original app does and I think it makes sense given that a fee is subtracted out. Otherwise the values being switched would have to be changed. If you agree then please strike out this checkbox item.

**Comment by JeremyParish69** [comment]
- [ ] Pool pages with Frontier assets still show '(channel-##)' (or maybe ibc/hash) instead of just the symbol, even when the coin information is available, but just not mentioned as a 'verified' asset.
- [ ] Some pools' pages with Frontier assets shows an amount worth just the half/portion with non-Frontier assets. E.g., 547 ATOM/TICK. But it still shows an amount of tokens.
- [ ] Going to a specific pool page un-highlights the 'Pools' button in the navigation pane.
![image](https://user-images.githubusercontent.com/95667791/169919113-10791b86-8b75-4a25-b955-31d10e7fb4ae.png)

- [ ] On a pool's page, the bonus bonding reward still shows even when there is 0 days remaining (gauge is finished, e.g., 602)
![image](https://user-images.githubusercontent.com/95667791/169919079-f20c28dd-d00d-405e-8a08-fdb4bb5be8b9.png)

- [ ] On Assets page, order is reversed? after osmo and ION, starts with DAI and ends on USDC. Sometimes it's inconsistent. I think it might be sorting where if there is a non-0 balance, then it is in the correct order, but all the tokens that don't have any balance are sorted in the opposite order.
![image](https://user-images.githubusercontent.com/95667791/169919433-37403983-f51f-4536-90cf-b6173f0d2765.png)

**Comment by jonator** [comment]
@JeremyParish69 

>  Pool pages with Frontier assets still show '(channel-##)' (or maybe ibc/hash) instead of just the symbol, even when the coin information is available, but just not mentioned as a 'verified' asset.

I think this is related to the IBC registry. I'd try clearing cache then reloading (given that config has recently updated). If that doesn't fix LMK.

> On Assets page, order is reversed? after osmo and ION, starts with DAI and ends on USDC. Sometimes it's inconsistent. I think it might be sorting where if there is a non-0 balance, then it is in the correct order, but all the tokens that don't have any balance are sorted in the opposite order.

Are you wanting to maintain config order for 0 balance assets?

**Comment by JeremyParish69** [comment]
> @JeremyParish69
> 
> > Pool pages with Frontier assets still show '(channel-##)' (or maybe ibc/hash) instead of just the symbol, even when the coin information is available, but just not mentioned as a 'verified' asset.
> 
> I think this is related to the IBC registry. I'd try clearing cache then reloading (given that config has recently updated). If that doesn't fix LMK.

I still see the same behaviour on multiple browsers after a hard refresh and clearing all cache and cookies.

> 
> > On Assets page, order is reversed? after osmo and ION, starts with DAI and ends on USDC. Sometimes it's inconsistent. I think it might be sorting where if there is a non-0 balance, then it is in the correct order, but all the tokens that don't have any balance are sorted in the opposite order.
> 
> Are you wanting to maintain config order for 0 balance assets?

Yes, it should probably match the order in the config file.

**Comment by victortokaito** [comment]
- [ ] Several users struggled with the "fuzzy" search library–it may be best to use just a direct search. Main issue: users were wondering why the other pools were coming up in unrelated search queries. For example, searching AKT places the "AKT pool" as # 4 after other less relevant pools (ATOM pools). Another user said "I probably don't understand how search works".

- [ ] WBTC doesn't appear in the asset dropdown of the main trade page. As Jeremy mentioned, there's a g-WBTC pool that shows 0 gWTBC even though there is liquidity (pool 694). During a user interview, user tried to swap for WBTC on main trading page, but WBTC cannot be chosen. However, WBTC does show up in the individual pool page's swap function. User assumed WBTC hasn't yet been added to the main frontend.

**Comment by JeremyParish69** [comment]
> * [ ]  WBTC doesn't appear in the asset dropdown of the main trade page. As Jeremy mentioned, there's a g-WBTC pool that shows 0 gWTBC even though there is liquidity (pool 694). During a user interview, user tried to swap for WBTC on main trading page, but WBTC cannot be chosen. However, WBTC does show up in the individual pool page's swap function. User assumed WBTC hasn't yet been added to the main frontend.

Neither gWBTC nor axlWBTC has been added to Main, so it won't show up there.
I was thinking maybe for any Pool containing a Frontier asset, we could automatically redirect the user to the Frontier site and give them an opportunity to go back. The same could apply for Frontier assets that come up in the search--we indicate to the user that selecting that asset will bring them to the Frontier site.
I'm not sure this can be addressed right away.

**Comment by jonator** [comment]
@victortokaito 
> Several users struggled with the "fuzzy" search library–it may be best to use just a direct search. Main issue: users were wondering why the other pools were coming up in unrelated search queries. For example, searching AKT places the "AKT pool" as # 4 after other less relevant pools (ATOM pools). Another user said "I probably don't understand how search works".

I fixed this. Good catch. The problem was that it was generating search results from input _then_ sorting. The solution was to sort first then filter by search box.

I wanted to comment because I also enabled [extended search](https://fusejs.io/examples.html#extended-search) for the search box. That lets users use advanced logic (and, or, exact match, prefix match, inverse match, etc.) in the search bar.

**Comment by jonator** [comment]
> On mobile, the Osmosis logo sometimes obscures the hamburger menu. This prevents users from clicking on to the Pools and Assets pages. The actual experience may be different as we're testing with users on mobile browsers rather than Keplr itself. Keplr's window may affect the interface in other ways. Is there a way that we can test the in-app Keplr UI before having pushed the refactor @delivan?

How small is the screen width? I'm seeing no problems down to a screen size of <280px, which is much smaller than any popular mobile device.

**Comment by jonator** [comment]
> Lost the ability to bond to arbitrary pools. This can be problematic for when a gauge has finished but some people have kept their liquidity bonded; they are given no way to remove it. Also makes it so that pools with new gauges (that are not yet registered) cannot be bonded to w/o CLI.

Is this still happening? Yesterday I made changes to unbonding UI in pool detail page
