### ISSUE TITLE
Include chain selection in deposit/withdraw workflow

### ISSUE THREAD

**Issue by jonator** [osmosis-labs/osmosis-frontend#523]
We should copy CEXs workflow for transferring to/from other chains:

<img width="711" alt="CleanShot 2022-05-21 at 00 21 20@2x" src="https://user-images.githubusercontent.com/4606373/169624318-7e151879-cf7f-4f28-9681-5fefb01d128d.png">

**Comment by victortokaito** [comment]
[Figma](https://www.figma.com/file/qze5yJO9TEw7vysInR07Ui/deposits%2Fwithdrawals-from-a-selection-of-chains-(non-IBC-Assets)?node-id=5%3A5047)

**Comment by jonator** [comment]
6/28 sprint planning-

Victor explainer: there would be a stableswap pool that abstracts away the non-fungibility of multi-bridged assets. This would be a utility separate from deposit IBC asset. Should revisit this when we get to axelar native integration.

**Blocked** waiting for axelar integration and stableswap, though not iceboxed due to time sensitivity

**Comment by jonator** [comment]
Functionality implemented and configurable
