### ISSUE TITLE
Keyboard support on frontend is gone after UI revamp

### ISSUE THREAD

**Issue by ckxpress** [osmosis-labs/osmosis-frontend#560]
A visually impaired friend needs to use keyboard (tab) to navigate the frontend of Osmosis. But after the UI is revamped, keyboard is no more supported, which is not good for accessibility.

Hope UI team can pay more attention to the need for accessibility and re-enable keyboard support.

**Comment by jonator** [comment]
What specific areas is your friend having trouble navigating? I'm able to navigate much of the controls/buttons

**Comment by jonator** [comment]
Closing with merge of #576, which brought tab and enter/space interactivity to all controls
