### ISSUE TITLE
Update to "hide zero balances" component.

### ISSUE THREAD

**Issue by victortokaito** [osmosis-labs/osmosis-frontend#566]
[Updated Figma.](https://www.figma.com/file/wQjMyxY0EnEk29gBzGDMe5/Osmosis-Component?node-id=4609%3A2451)

@jonator, changing "hide zero balances" to a slider toggle could help bring the mobile more closely in line with the desktop. Side note: Switches and checkboxes are both used to enable settings. But the immediacy of when users expect those settings to activate are different. And the slider toggle has more of an instantaneous feeling.

Addresses concerns in and closes #461.

**Comment by victortokaito** [comment]
Also applies to ["Show pools less than $1000".](https://www.figma.com/file/wQjMyxY0EnEk29gBzGDMe5/Osmosis-Component?node-id=4609%3A2451)

**Comment by jonator** [comment]
Going to icebox for now to bring up later in meeting, given low priority

**Comment by jonator** [comment]
6/7 meeting - adding to v2 polishing issue. Also moving to top of assets table
