### ISSUE TITLE
Iconography for Incentivized pools

### ISSUE THREAD

**Issue by syed8rahman** [osmosis-labs/osmosis-frontend#571]
Current icons aren't intuitive with the coins + check. First round of user research confirmed this. 

- [ ] Explore three different incentivized icons (internal, external, both)
- [ ] Conduct user testing

**Comment by jonator** [comment]
Removing from Refactor milestone (and closing the milestone) now that the refactor is deployed on main and frontier

**Comment by jonator** [comment]
[Figma](https://www.figma.com/file/wQjMyxY0EnEk29gBzGDMe5/Osmosis-Component?node-id=3959%3A1685)

**Comment by jonator** [comment]
6/38 sprint planning -

**Blocked** Still needs to be user researched. (added as bullet in #418 )

**Comment by jonator** [comment]
Closing due to redesign
