### ISSUE TITLE
Frontier - ASVT token is not available in swap menu on new frontier

### ISSUE THREAD

**Issue by angrymouse** [osmosis-labs/osmosis-frontend#589]
ASVT token not appears in swap menu, although it is visible in Assets tab and is listed in config.ts.
It has 2 pools: 716 and 717, with enough liquidity to appear on old frontier (5k$ 716).
It appears on old frontier (https://frontier-old.osmosis.zone), but not on new.

**Comment by jonator** [comment]
We're currently working on true optimized routing. Currently, we do dynamically calculate routes on the frontend, but we only route through a selection of pools we consider to have enough liquidity. ASVT should appear in the trade menu once we finish optimized routing.
