### ISSUE TITLE
Trade page selection - truncate precision

### ISSUE THREAD

**Issue by ValarDragon** [osmosis-labs/osmosis-frontend#594]
On the trade page, when you list your tokens in the from/to, we use the full ETH / BTC precision. It would be ideal to truncate these, to e.g. 9 decimal points. 

Would this be blocked on a `display decimals` field in assetlists?

**Comment by jonator** [comment]
Yeah precision for an "in" asset on the trade page is based on the `coinDecimals` field in the currencies in chain config (`chain-infos.ts`). The out asset decimals cannot exceed a hardcoded value of 6.
