### ISSUE TITLE
Revisit "My Pools" section in pools page

### ISSUE THREAD

**Issue by jonator** [osmosis-labs/osmosis-frontend#598]
[Notion meeting notes](https://www.notion.so/osmosiszone/6-6-2022-Pools-page-49ccb1cf9a4644e988ff5faf313e020b)
[Figma](https://www.figma.com/file/wQjMyxY0EnEk29gBzGDMe5/Osmosis-Component?node-id=5042%3A31893)

We've received a lot of feedback that it's confusing to see pools at the top of the assets page (as pool cards). We should revisit how we display owned pools (LP positions) in the assets page.

- [ ] Move "My Pools" section (as it is) below assets table & IBC transfers table
- [x] Move hide zero balances switch to left of search bar in assets table
- [x] Add link to support site
- [ ] Add highly engaging link to frontier site (address concerns with finding non-scammy links)

**Comment by CMarshall92** [comment]
If your happy for me to pick this up I could implement the changes fairly quickly i think.

Will post a PR soon

**Comment by CMarshall92** [comment]
Can we link the new PR thats now not a draft https://github.com/osmosis-labs/osmosis-frontend/pull/653
