### ISSUE TITLE
One click button to swap dust to OSMO

### ISSUE THREAD

**Issue by sunnya97** [osmosis-labs/osmosis-frontend#60]
Commonly requested feature: https://twitter.com/fwoods_xf/status/1448912286542753793

**Comment by faddat** [comment]
brilliant

**Comment by ValarDragon** [comment]
Token dust is caused from slippage's in LP'ing tokens I believe

**Comment by dogemos** [comment]
I can see some issues in the post-zero-fee Osmosis where if the amount of dust tokens < fees paid this won't be efficient.

Not sure if this should be a priority right now.

Thoughts?

**Comment by jonator** [comment]
IMO this is too much of an edge case to necessitate dedicated functionality. It would complicate/clutter things more than it's worth.
