### ISSUE TITLE
Search filter in assets not working.

### ISSUE THREAD

**Issue by iam-agf** [osmosis-labs/osmosis-frontend#615]
Enter Assets and use the search bar. It shouldn't work as how is working:

<img width="1172" alt="image" src="https://user-images.githubusercontent.com/61362029/173393031-2f9a49c4-ab30-4e61-ac28-94caebc22b3b.png">

---

**Device:** Macbook Air M1
**Browser:** Google Chrome

**Comment by jonator** [comment]
Our search functionality is what's called "fuzzy" search: it will rank results from most relevant to least, looking at everything from words to individual characters. "THIS IS WEIRD" returns no exact results, but it does match individual characters of the assets seen in the screenshot as less relevant results.

* Helps account for typos
* Increases the chance a user can find something even if they don't remember the name or exact spelling

Note: we support [extended search](https://fusejs.io/examples.html#extended-search). You can search for _only_ exact  and complete (no prefixing) results by prepending '=' to your query.

**Comment by iam-agf** [comment]
Now I get what you're doing here. Yes, you're right, it makes sense. 

I have some other questions that I'm not if it's an issue or works _as how it should_ like this one. I followed you in Twitter (cosmo_jorin) to send you a dm to mention them, but can't send you one because of the not following condition. Can I ask you here or somewhere else (to not fill this chat)?
