### ISSUE TITLE
Withdrawal address can't edit after Verify + Enter.

### ISSUE THREAD

**Issue by iam-agf** [osmosis-labs/osmosis-frontend#616]
Go to Assets, then withdraw for example ATOM, click on **Edit** in the **To** entry
![a](https://user-images.githubusercontent.com/61362029/173396096-616cc2fe-872a-4756-b7ab-3096c04169a1.jpeg)
 
Then click on "I verify..." and Enter.
![b](https://user-images.githubusercontent.com/61362029/173396438-f2942fa9-406d-47b6-b970-ca964724ec16.jpg)

Now you can't change the address. This shouldn't happen.

---

**Device:** MacBook Air M1
**Browser:** Google Chrome

**Comment by jonator** [comment]
This was intentional. Once the user changes the address, it is "locked in" and ready to be used for transferred. They can only edit again by reopening the modal.

**Comment by iam-agf** [comment]
I see. Then it's not a bug. 

But which is the idea behind locking it?

**Comment by jonator** [comment]
6/28 sprint planning -

Victor: we should let users edit again. Reset state to initial modal opening.
