### ISSUE TITLE
Mobile trade page: token select modal

### ISSUE THREAD

**Issue by jonator** [osmosis-labs/osmosis-frontend#624]
### Problem
The token select dropdowns on mobile can be hard to use, especially on smaller devices.

### Proposed Solution
As we did with the sort menu, use a modal to select tokens instead of a dropdown.

**Comment by victortokaito** [comment]
![trade_mobile_assets_dropdown](https://user-images.githubusercontent.com/39136683/174386133-69b75de6-7776-4d38-9284-f9ca77a0efa9.png)

Assets dropdown converted to a [modal on trade mobile.](https://www.figma.com/file/UXgL2cPiw5I4GALDOodfCy/Osmosis-Web-(Master-File)?node-id=1716%3A25626)
