### ISSUE TITLE
Pull EmbedChainInfos from chain-registry

### ISSUE THREAD

**Issue by ValarDragon** [osmosis-labs/osmosis-frontend#63]
We should automatically pull the [Embed-Chain infos](https://github.com/osmosis-labs/osmosis-frontend/blob/f8ec3832776dc303860ae1736d5aed48d5cdf26e/src/config.ts#L427) from the [chain-registry](https://github.com/cosmos/chain-registry). (If theres missing fields needed, we should add these to the chain-registry) 

This will significantly lower the manual overhead involved for replacing IBC denoms with human readable names.

**Comment by ValarDragon** [comment]
Seeing as github went down recently. We'd need the chain-registry data hosted in more places than just github before this can get deployed.

**Comment by JeremyParish69** [comment]
I like this idea and would like to reference this issue repeatedly to support my argument for additional changes on chain reg so that at least all required data could be derived from data on the chain reg.
