### ISSUE TITLE
Trade clipboard wallet status & slippage calculations

### ISSUE THREAD

**Issue by jonator** [osmosis-labs/osmosis-frontend#630]
### Problem
As @syed8rahman pointed out. There are some problems with new trade clipboard that were not present in [old frontend](https://testnet.osmosis.zone/?from=ATOM&to=OSMO):
* All estimate calculations give up (go to 0) after > 10% slippage
* If a user hasn't connected a wallet, the connect wallet button shouldn't turn red on high slippage

![example](https://user-images.githubusercontent.com/4606373/174333560-2268d209-35c5-4d0b-9801-20701c3ee4f1.gif)

### Proposed Solution

* Wallet disconnected
  - [x]  Don't show insufficient balance errors
  - [x] Don't turn button red
* Calculations
   - [ ] Don't zero out on high slippage

Currently, the red UI is based on an arbitrary/hard-coded slippage threshold, should we instead look at the user's slippage setting to determine what is a high slippage?

**Comment by jonator** [comment]
Making low priority since this doesn't disrupt common trading use cases. However, this isn't up to our quality standards.

**Comment by Thunnini** [comment]
In the case of slippage, the problem does not occur at 10%, but at 30%. It depends on the weight of the pool, but a problem occurs in about 30% if 50:50 pool. If the token in exceeds 30% of the pool's asset, it is treated as an error.

This restriction is also to prevent transactions of too large slippage, but in fact, each pool is given priority up to 30% and to induce mixed swap with other pools if the token in exceeds 30% of the pool's asset. If other pools exist and have sufficient liquidity, it can handle swaps with slippage lesser than 30%.

30% is too large slippage, so I don't know if it should be considered to be able to swap more than that, but I'll consider whether it can be handled in a way that allows more than 30% of asset if liquidity is insufficient even with mixed swap.

**Comment by jonator** [comment]
@Thunnini actually, I've decided to not fix the calculations going to 0. This happens because the route doesn't have enough liquidity once you enter a number high enough. Except in the case of playing with the UI just to see how high the calculations can get, I don't see a need to maintain these calculations.

Instead, I will just prevent the clipboard from showing red when wallet is not connected.
