### ISSUE TITLE
Testnet: add faucet link

### ISSUE THREAD

**Issue by jonator** [osmosis-labs/osmosis-frontend#632]
Add link to faucet.osmosis.zone somewhere in the testnet frontend once we merge the refactor code over. Perhaps in banner or bottom left banner.

Adding design label so we can answer that question.

**Comment by victortokaito** [comment]
![banner](https://user-images.githubusercontent.com/39136683/174377531-13a51aea-2f4c-4824-a2ab-4e4007f7d3b1.png)

Here's a [banner](https://www.figma.com/file/7iuO8MZeiYezTnF7suwTNN/draft-UI?node-id=924%3A36887) we can put on testnet site!

**Comment by jonator** [comment]
@victortokaito Thoughts on giving it the same design as the frontier site? That would make it more reusable.

**Comment by victortokaito** [comment]
The figma link above should be more reusable vs. the frontier banner (white text on gold may be difficult to use elsewhere).

This is also the standard prescribed for the support site (replacing the superfluid color banner).

**Comment by daniel-farina** [comment]
Nice touch 👏
