### ISSUE TITLE
Allow tx batch mode

### ISSUE THREAD

**Issue by jonator** [osmosis-labs/osmosis-frontend#638]
### Problem
Inspired by [this tweet](https://twitter.com/hasufl/status/1538793436085637121?s=20&t=hkdw4nibp9ISpN_DB38-Yw)

Especially for power users, it may be annoying to have to sign each individual action they want to take on the app, especially if they use a ledger to sign. Knowing they have to click the ledger key buttons 10+ times per transaction may prevent them from sending transactions the otherwise would have if they were using a hot wallet (signing in the extension).

### Proposed Solution
We should look into allowing power users to toggle on a "batch mode" that allows them to queue a bunch of transactions that they could later sign all together as one large multi-message transaction. We should warn about slippage if they include swap transactions.

**Comment by victortokaito** [comment]
Oh yeah, saw that! 

Last updates from the lab, sunny mentioned a more backend approach to this in the authz module (e.g. approve x amount of transactions or approve all transactions below $x amount). I wonder if we could have this authz setting/"batch mode" be accessed from the frontend of the core app's settings icon.

Maybe users would also be able to set up "allowances" with a slider.

**Comment by victortokaito** [comment]
["batch mode" toggle](https://www.figma.com/file/7iuO8MZeiYezTnF7suwTNN/draft-UI?node-id=950%3A40360)
![Transaction settings-1](https://user-images.githubusercontent.com/39136683/174906413-2a4c6a72-6aa0-4ac1-96f4-bf4493f714ca.png)
![Transaction settings](https://user-images.githubusercontent.com/39136683/174906415-baf74b75-5a49-467c-85e7-40ddfebf9506.png)

**Comment by jonator** [comment]
@victortokaito Nice! Two things come to mind:
* Regarding location: may want to avoid placing this setting with the swap clipboard as this is moreso intended for all txs except for swap txs because of slippage. Should this introduce the "Profile" modal as we discussed in Austin; tx history, send/receive buttons, etc. We could then place this setting there w/ any other settings down the road.
* Regarding batching transactions: should we have some sort of temporary toast-like UI that shows the current types of transactions being batched?

**Comment by victortokaito** [comment]
How might this work? Is there a confirmation or automatic:
• Once the user selects the dropdown–is there another UI for confirming/completing the experience "view cart/check out"? 
• Or are you saying there'd be a user-input quantity under this setting, and that the 'orders' would all go through once the limit is met (e.g. Upon adding a 5th swap/LP position, all "orders" are batched and automatically "sent")?

**Comment by jonator** [comment]
> Once the user selects the dropdown–is there another UI for confirming/completing the experience "view cart/check out"?

I'm thinking there could be a fixed list view, perhaps in place of the bottom sidebar, that would show a list of all batched transactions. Users could then see and modify that list.

> Or are you saying there'd be a user-input quantity under this setting, and that the 'orders' would all go through once the limit is met (e.g. Upon adding a 5th swap/LP position, all "orders" are batched and automatically "sent")?

I'd guess the user would click a "send" button near the list described above. But this is also an interesting idea. Perhaps we could have both, but create a limit at, say, 5, that would the make the user send the batch. There may also be a limit of transactions within a single block.

It seems we need to:
1) Discuss this idea with users, and make sure it is something they'd use (esp. if they use Ledger) @syed8rahman 
2) Investigate gas implications of batching

**Comment by jonator** [comment]
6/28 FE meeting - 

@dogemos we should look into adding batching as a feature/API in Keplr. Then all cosmos dapps could benefit. Most useful for Ledger users who are annoyed with clicking their Ledger to audit & confirm txs.

**Comment by jonator** [comment]
Note: from personal experience, batching multiple transactions won't reduce number of button presses on a Ledger device, only will concentrate them to a single event.

**Comment by JeremyParish69** [comment]
Allowing for batching of transactions brings a few questions to mind.

One is: will users be able to play with the "expected funds" they would have after one of the txs, but before the batch is complete? e.g., If I swap 50 USDC for ~ 6 ATOM, will I be able to swap, LP, or withdraw 100% of that ATOM later in the same batch( even though I don't know the exact amount of ATOM I'd receive from the first swap)?

Another is: will a bundle of swaps be optimized if they are in the same batch? e.g., if in a single batch, I swap 50 USDC for ATOM and swap another 50 USDC for OSMO, will it be able to swap a little bit between ATOM and OSMO if that'd be the optimal (i.e., if there's arbitrage)?

**Comment by jonator** [comment]
@JeremyParish69 we were planning on excluding swaps from batch txs. But that is a good point, we may need to forecast state changes and prevent batching txs if we think it will cause an error. Seems like a lot of added complexity to consider.

This idea may be shelved for now since we're pretty busy adding bridge integration functionality to the frontend.

**Comment by jonator** [comment]
Closing due to reasons above
