### ISSUE TITLE
Add a tool tip to explain the breakdown of pool APRs

### ISSUE THREAD

**Issue by ValarDragon** [osmosis-labs/osmosis-frontend#64]
From @jeremyparish https://commonwealth.im/osmosis/proposal/discussion/1547-how-can-we-improve-the-osmosis-frontend-feedback-thread?comment=7905 

Essentially it would be cool if we could add a tool tip to every APR on the front-end, showing a decomposition of where the APR is coming from. There would be three sources in Osmosis:
* Osmo Incentive APR
* Fee APR
* {other token} incentives APR

Not sure if we need more work to add the Fee APR at the moment though. It should be possible to derive using API data from imperator https://api-osmosis.imperator.co/swagger/#/

**Comment by jonator** [comment]
Perhaps a good (additional?) fit for a feature like this would be in the pool detail page. Perhaps 'fee APY' to the right of 'Bonded' and 'Swap Fee' numbers. How about 'Fee APY'? See:

<img width="630" alt="Screen Shot 2021-11-02 at 8 09 14 PM" src="https://user-images.githubusercontent.com/4606373/139981625-52d88a00-d855-4ee5-8402-91b2acae071c.png">
 
Also. I'm a total noob to this space, but my best guess for calculating APY from fee would be from the past year of volume * swap fee -> adjusted for year? Thanks

**Comment by ValarDragon** [comment]
yeah, thats pretty solid for calculating fee APY

**Comment by jonator** [comment]
In the refactor we will show fee returns in the pool card of non-incentivized pools. Otherwise, I think users should be going to info.osmosis.zone for this kind of data, even dexmos.app.
