### ISSUE TITLE
Landing page loads random tokens depending on web browser

### ISSUE THREAD

**Issue by arispech** [osmosis-labs/osmosis-frontend#640]
Uppon visiting the website for the first time on a new browser. The UI loads different tokens pairs on the default page depending on the browser.

Step to reproduce, images and video from internal QA testing:
https://github.com/osmosis-labs/test-management/issues/43

**Comment by arispech** [comment]
Updated link, it should be: https://github.com/osmosis-labs/test-management/issues/43

**Comment by jonator** [comment]
I've been having trouble replicating this. But I do think there is some undefined behavior arising when a user has first loaded the app and the registry hasn't yet loaded in the browser.
