### ISSUE TITLE
First time user, Connect Keplr not working. 

### ISSUE THREAD

**Issue by arispech** [osmosis-labs/osmosis-frontend#641]
First time user, Connect Keplr not working.

Details from internal QA here:
https://github.com/osmosis-labs/test-management/issues/2

@ValarDragon  suggested just adding a Keplr extension link in the meantime as this blocks new users from connecting to the site completely.

**Comment by daniel-farina** [comment]
by the way this is what Axelar does currently:

<img width="795" alt="image" src="https://user-images.githubusercontent.com/13665117/174890758-c5c7eb86-6498-4275-af89-2ad21a6fff70.png">

**Comment by jonator** [comment]
Currently being implemented in #613

**Comment by daniel-farina** [comment]
This PR has been in the works for 9 days and it could take several more days. I highly think we should  just add the link to Keplr for now and then get back to #613

**Comment by jonator** [comment]
https://osmosis-frontend-git-fork-cmarshall92-issue-412-osmo-labs.vercel.app/

@daniel-farina I updated the PR (#613) since the opener may have gotten caught up with life.. it now shows a link to Keplr official site if the extension isn't installed. Check it out ^
