### ISSUE TITLE
Asset Lists v1

### ISSUE THREAD

**Issue by victortokaito** [osmosis-labs/osmosis-frontend#642]
@jonator 
![AssetListv1 - List Dropdown](https://user-images.githubusercontent.com/39136683/174904935-c564345e-479f-4183-8388-3aae173b51a3.png)
![AssetListv1 - Token Dropdown](https://user-images.githubusercontent.com/39136683/174904938-a53e5c60-0466-439e-8381-ef07555fe155.png)

**Comment by jonator** [comment]
Think we could place this in a FigJam or Figma instead? We could then jam on the design a bit more efficiently there.
