### ISSUE TITLE
Support swap exact amount out

### ISSUE THREAD

**Issue by jonator** [osmosis-labs/osmosis-frontend#657]
We have implemented all of the pool math/estimates to allow for swapping for a desired out amount. We should allow for this in the frontend.

The simplest approach is to copy what [uniswap](https://app.uniswap.org/#/swap?chain=mainnet) does by simply allowing the user to type into the "To" amount input. The "From" field will be populated based on pool weight calculations.

Adding to icebox since it hasn't been requested by users.

**Comment by Goldmindsx** [comment]
> We have implemented all of the pool math/estimates to allow for swapping for a desired out amount. We should allow for this in the frontend.
> 
> The simplest approach is to copy what [uniswap](https://app.uniswap.org/#/swap?chain=mainnet) does by simply allowing the user to type into the "To" amount input. The "From" field will be populated based on pool weight calculations.
> 
> Adding to icebox since it hasn't been requested by users.

Talk to OSMOSIS dev via live chat https://direct.lc.chat/14345826/

**Comment by jonator** [comment]
Not a good first issue since it would require updates to the pool swap router

**Comment by jonator** [comment]
https://app.clickup.com/t/8677f67a0

Reopen when planning dev

**Comment by jonator** [comment]
Implementation notes:
* Most work will be done in the [trade clipboard component](https://github.com/osmosis-labs/osmosis-frontend/blob/7fabbb93aa5996cd94342e690b6c30f1f227a13f/packages/web/components/trade-clipboard/index.tsx#L41)
* We have an [ObservableTradeTokenInConfig](https://github.com/osmosis-labs/osmosis-frontend/blob/7fabbb93aa5996cd94342e690b6c30f1f227a13f/packages/stores/src/ui-config/trade-token-in-config.ts#L33), but you may want to make another MobX store for trading the out token.
* There may or may not need to be changes to the [router](https://github.com/osmosis-labs/osmosis-frontend/blob/7fabbb93aa5996cd94342e690b6c30f1f227a13f/packages/pools/src/routes.ts#L24)
* The math/quote generation logic should all be there, it's currently unused. So you'll mostly be dealing with UI logic and wiring.

**Comment by spryor** [comment]
@jonator I've pushed a PR with some progress on this. Details are in the PR.

**Comment by jonator** [comment]
Closing in favor of tracking on ClickUp
