### ISSUE TITLE
is now online an old version of https://frontier.osmosis.zone/ ?

### ISSUE THREAD

**Issue by Alvised** [osmosis-labs/osmosis-frontend#663]
Problem
I'm quite new in the site,but  since a couple of hours ago(10 minutes before the reward) i've seen big changes in the UI and it seems an old version of the site
Desktop
- the icons of the pools are not showing the token icons, but jus a generic flask and a monocrome background;
- on the asset page is now absent the section "my pools" and the button "hide token with 0 value";
-since that moment on pool 670 are not present the panels showing the rewards for bondin 7 or 14 days in Grav, but as a grav support confirmed they are still active.

![Senza titolo](https://user-images.githubusercontent.com/108695700/177212504-7c7a88d2-0799-4cec-b3f6-1343928da994.png)

**Comment by JeremyParish69** [comment]
I see the same.
Also, 670 should indeed be showing external incentives but it's not.
Appears to be pre-refactor @jonator

**Comment by jonator** [comment]
@Alvised @JeremyParish69 can you guys try again? We believe it is a caching issue. (cc @daniel-farina )

**Comment by Alvised** [comment]
now it work perfectly
