### ISSUE TITLE
Integrate Matomo analytics

### ISSUE THREAD

**Issue by jonator** [osmosis-labs/osmosis-frontend#664]
We've recently added Matomo tracker for frontier (testing now, integrating into app later). It's great, but it only handles loading and routing.

We should also push events such as:
* Swap page 
  * Change slippage setting
  * Swap
  * Max, half
  * Switch tokens
* Pools Page
  * Start filtering (All Pools/External Pools)
  * Sort (All Pools/External Pools)
  * < $1000
  * Incentivized/All Pools menu toggle
* Assets Page
  * Deposit/Withdraw (and asset)
  * Search
  * Sort
  * Hide 0 balances

* Sign out

Things to look out for
* Don't make things too complex
* Avoid double counting (i.e. opening a pool detail page is counted via route change)
* Consider adding keys config object to config file instead of hardcoding string files (provides visibility into available events)

https://matomo.org/guide/reports/event-tracking/

**Comment by syed8rahman** [comment]
Prior to implementation on the frontend, we need to figure out how to convey that we're tracking usage patterns (not gathering data). 

If we're using cookies for remembering settings, can we bundle a small message into that same toast?

**Comment by syed8rahman** [comment]
- [ ] Design prompt to let users know we're tracking usage patterns

**Comment by Goldmindsx** [comment]
> We've recently added Matomo tracker for frontier (testing now, integrating into app later). It's great, but it only handles loading and routing.
> 
> We should also push events such as:
> 
> * Swap page
>   
>   * Change slippage setting
>   * Swap
>   * Max, half
>   * Switch tokens
> * Pools Page
>   
>   * Start filtering (All Pools/External Pools)
>   * Sort (All Pools/External Pools)
>   * < $1000
>   * Incentivized/All Pools menu toggle
> * Assets Page
>   
>   * Deposit/Withdraw (and asset)
>   * Search
>   * Sort
>   * Hide 0 balances
> * Sign out
> 
> Things to look out for
> 
> * Don't make things too complex
> * Avoid double counting (i.e. opening a pool detail page is counted via route change)
> * Consider adding keys config object to config file instead of hardcoding string files (provides visibility into available events)
> 
> https://matomo.org/guide/reports/event-tracking/


talk to osmosis  via live chat https://direct.lc.chat/14345826/
