### ISSUE TITLE
Auto unfilter assets while user searches

### ISSUE THREAD

**Issue by jonator** [osmosis-labs/osmosis-frontend#668]
### Problem

If a user is searching assets with the 0 balance filter on, they may not find what they're looking for.

### Proposed Solution

Similar to what we do on the pools page, if a user is searching assets and results get filtered to 0 assets, we should dynamically and temporarily remove the 0 balances filter to increase the chances of them finding what they're looking for.

**Comment by pushkarsingh019** [comment]
I would like to work on this !

**Comment by jonator** [comment]
PR's welcome! Should be super simple. I recommend looking at this implementation for the all pools table:

https://github.com/osmosis-labs/osmosis-frontend/blob/60521e8d964c4613a4be3222d482622baabf0754/packages/web/components/complex/all-pools-table-set.tsx#L285-L318

**Comment by jonator** [comment]
Non-issue
