### ISSUE TITLE
Pool 722, multiple Lock IDs and a misconfigured error code.

### ISSUE THREAD

**Issue by Kilo-Osmosis** [osmosis-labs/osmosis-frontend#670]
Myself, and a few users who bonded for 14 days in pool 722 had an issue where when we attempted to enable SFS, we would get a generic "internal" error. This error was broadcast on chain as a failed tx. 
![image](https://user-images.githubusercontent.com/108903244/177879880-e4815fe9-a50e-430c-a14a-7f7bd075be5e.png)
Through a little testing we were able to figure out some users had multiple lock IDs when attempting to enable SFS in this pool. 
![image](https://user-images.githubusercontent.com/108903244/177880236-739a1374-813f-478f-8cd6-c1fcd858c571.png)
This was causing an out of gas error, however, that error message was never relayed. Significantly increasing the gas fixed this error and let users enable SFS successfully. 

Assuming fixing the multiple lock IDs for some users isn't easily achievable, can we enable the proper "out of gas" error message for failures of this nature?

**Comment by jonator** [comment]
Root problem: 
* Delegating on multiple locks requires more gas than suggested, perhaps related to multi msg.
* Out of gas error is returned from chain as `internal` message. May be chain issue.

**Comment by jonator** [comment]
Good first issue if you're interested in working on multi msg tx gas estimations
