### ISSUE TITLE
superfluid validators who are inactive or jailed "disappear"

### ISSUE THREAD

**Issue by doggystylez** [osmosis-labs/osmosis-frontend#684]
![image](https://user-images.githubusercontent.com/98429202/179074012-8d6f37f1-7f56-46df-a5dd-1e1e51facc5a.png)

Some users have reported that their superfluid validator has disappeared. I tested this by manually delegating to an inactive validator

**Comment by jonator** [comment]
@victortokaito @syed8rahman we should discuss ways we can show this and let the user unbond. Note: they can redelegate because SFS does not support redelegation (cc @ValarDragon )

**Comment by victortokaito** [comment]
This is an explanation of how it works currently^. Maybe we add support for users who are stuck in these edge cases. 

There isn't any functionality for this yet, but can we add a get-out-of-jail functionality for users whose validators are inactive? I understand SFS is locked, but their underlying stake is still being delegated to a validator outside of the active set–at the least, can we allow users to redelegate this portion to another validator?

**Comment by jonator** [comment]
I think given how it's currently implemented on chain -- since we can't re-delegate an SFS bond (lock) -- IMO the simplest thing to do would be to help the user unbond all locks from the jailed validator.

**Comment by Goldmindsx** [comment]
> ![image](https://user-images.githubusercontent.com/98429202/179074012-8d6f37f1-7f56-46df-a5dd-1e1e51facc5a.png)
> 
> Some users have reported that their superfluid validator has disappeared. I tested this by manually delegating to an inactive validator

talk to osmosis  via live chat https://direct.lc.chat/14345826/
