### ISSUE TITLE
Address book for withdraw addresses

### ISSUE THREAD

**Issue by jonator** [osmosis-labs/osmosis-frontend#687]
Similar to wallets and CEXs, we should enable the user to save common withdraw addresses in an address book.

**Comment by Goldmindsx** [comment]
> Similar to wallets and CEXs, we should enable the user to save common withdraw addresses in an address book.


talk to osmosis  via live chat https://direct.lc.chat/14345826/

**Comment by Goldmindsx** [comment]
> Similar to wallets and CEXs, we should enable the user to save common withdraw addresses in an address book.


talk to osmosis  via live chat https://direct.lc.chat/14345826/

**Comment by jonator** [comment]
Update: this should only affect IBC transfers, since currently that is the only type of transfer we support custom addresses for.

This functionality could be enabled as a flag as part of the withdraw address config:
https://github.com/osmosis-labs/osmosis-frontend/blob/ac71ef0a8d50ba4311e1c6fe8b6e529d862f2e04/packages/web/components/complex/transfer.tsx#L29

Addresses could be stored in localstorage, namespaced by [transfer path](https://github.com/osmosis-labs/osmosis-frontend/blob/ac71ef0a8d50ba4311e1c6fe8b6e529d862f2e04/packages/web/components/complex/transfer.tsx#L20).

Rough idea: perhaps create a useAddressBook hook where you pass in the context and it returns view config and any update actions. Could also look into creating a mobx store and adding it to the root store (root.ts).

**Comment by jonator** [comment]
Closing since it's an idea in clickup. Can reopen if pursued.
