### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by berelton** [osmosis-labs/osmosis-frontend#698]
Hi Osmo team, do you have any guidance with the docker image to run app from this repo?

With `16-alpine` getting this error:

```
#15 18.53 lerna ERR! yarn run build stderr:
#15 18.53 error - Failed to load SWC binary
```

**Comment by berelton** [comment]
any updates folks?

**Comment by jonator** [comment]
Are you talking about running the frontend in a container?

**Comment by berelton** [comment]
> Are you talking about running the frontend in a container?

yes

**Comment by jonator** [comment]
https://nextjs.org/docs/deployment#docker-image
