### ISSUE TITLE
desmos | Transaction Failed when trying to withdraw or deposit on Osmosis

### ISSUE THREAD

**Issue by lorenzomenegon** [osmosis-labs/osmosis-frontend#704]
**System information**
Osmosis version: 10.1.1
OS & Version: OS Monterey 12.4

**Expected behaviour**
The transaction should be correctly broadcasted.

**Actual behaviour**
A lot of Keplr users are facing this issue when trying to submit a transaction between Keplr and Osmosis with Desmos chain. The error message is the following:

`Transaction Failed: you have too many concurrent txs going on! Try resending after your prior tx lands on chain. (We couldn't send the tx with sequence number 0)`

**Steps to reproduce the behaviour**
To Reproduce
Steps to reproduce the behavior (not happening to every account):

Go to https://app.osmosis.zone/assets.
Click on Deposit button.
Sign the transaction.
See the error message posted in the description.

**Backtrace**
This was marked as an Osmosis frontend issue: #https://github.com/chainapsis/keplr-wallet/issues/468

**Comment by jonator** [comment]
Have you tried this again? Are you still getting this issue? This may happen if there's a pending transaction already.

**Comment by lorenzomenegon** [comment]
There are no pending transactions. This is happening to a lot of different users without any reason. As you can see i reported it to Chainapsis because i was almost sure it was an issue related to Keplr, but the reply talked about Osmosis...

**Comment by Moistbobo** [comment]
I am also experiencing this, here's what appears in the console:

![image](https://user-images.githubusercontent.com/29080587/184520235-2f1d865a-770b-4b01-98c2-d77911083bee.png)

And the `data` object that gets sent (addresses omitted)

```json
{
  "chain_id": "desmos-mainnet",
  "account_number": "0",
  "sequence": "0",
  "fee": {
    "gas": "130000",
    "amount": [
      {
        "denom": "udsm",
        "amount": "3250"
      }
    ]
  },
  "msgs": [
    {
      "type": "cosmos-sdk/MsgTransfer",
      "value": {
        "source_port": "transfer",
        "source_channel": "channel-2",
        "token": {
          "denom": "udsm",
          "amount": "1000000"
        },
        "sender": "[redacted]",
        "receiver": "[redacted]",
        "timeout_height": {
          "revision_number": "1",
          "revision_height": "5576840"
        }
      }
    }
  ],
  "memo": ""
}
```

**Comment by CommunityStaking** [comment]
I also tried to send DSM through Keplr IBC, but got this error, while somebody else had no issues doing the same thing:
![Untitled](https://user-images.githubusercontent.com/43610279/186639834-4abc1145-7793-4a29-9792-250fece30f3f.png)

**Comment by jonator** [comment]
> There are no pending transactions. This is happening to a lot of different users without any reason (and their DSM are stuck). As you can see i reported it to Chainapsis because i was almost sure it was an issue related to Keplr, but the reply talked about Osmosis...

Do you have any other details about the reply relating to Osmosis?

**Comment by lorenzomenegon** [comment]
No, this is the reference: https://github.com/chainapsis/keplr-wallet/issues/468

**Comment by jonator** [comment]
Ah. Yeah it's worth mentioning an issue persists when initiating an IBC transfer directly via Keplr extension.

**Comment by lorenzomenegon** [comment]
@jonator should i open another issue to Keplr?

**Comment by jonator** [comment]
Please!
