### ISSUE TITLE
Specify favorite assets

### ISSUE THREAD

**Issue by jonator** [osmosis-labs/osmosis-frontend#710]
[From discord](https://discord.com/channels/798583171548840026/855908784445849610/1001822923507642430)

Similar to the info site, would be great to specify assets that are a users favorite.

User stories:
* A user commonly withdraws/deposits an asset, but since the balance is currently 0 the user is required filter/find the asset.

Should discuss & research whether user stories justify the added UI & dev complexity.

**Comment by jonator** [comment]
Is a good first issue, but **blocked** on design link @victortokaito

**Comment by victortokaito** [comment]
### Specify Favorites![Specify Favorites](https://user-images.githubusercontent.com/39136683/192857760-8fceb128-72ea-437e-99c6-e2e79e2463f4.png)
### Drag to rearrange ![Specify Favorites - shadow drag to rearrange](https://user-images.githubusercontent.com/39136683/192857769-673108a9-23bf-436d-98c0-49fc076d2e3a.png)

[Figma link](https://www.figma.com/file/TbhltqFzPjWgIdxdcQ23dj/Assets?node-id=114%3A3605) ([frames without the 3D visual assets](https://www.figma.com/file/TbhltqFzPjWgIdxdcQ23dj/Assets?node-id=114%3A3320))

**Comment by victortokaito** [comment]
### More fun and game vibe
![Specify Favorites](https://user-images.githubusercontent.com/39136683/192866496-933ca8e4-8708-4e32-a975-dcb35892dac7.png)
![Specify Favorites - shadow drag to rearrange](https://user-images.githubusercontent.com/39136683/192866493-69863346-4611-40e2-8cb8-e4a720a2afdc.png)

**Comment by jonator** [comment]
@victortokaito how would sorting be affected? Shouldn't the stars column be a new sortable column?

**Comment by victortokaito** [comment]
As part of the development workflow, we need to add tracking to new user-facing features. Whenever we merge features, we can get some automated notification through clickup to update amplitude
