### ISSUE TITLE
[Testcase - Trade Page] - Navbar UI overlap

### ISSUE THREAD

**Issue by arispech** [osmosis-labs/osmosis-frontend#713]
The following test case is not failing but there are UI issues on the mobile version (Android)
https://github.com/osmosis-labs/test-management/issues/15

### Steps
1. Visit app.osmosis.zone (app on Android)
2. Enter the number of tokens preferred in the amount input field

As seen in the image below, there are blocking elements, when the user is trying to enter the amount to swap.
The osmosis and menu bar flow over the trade box.

![Screenshot_20220808-164854_Keplr](https://user-images.githubusercontent.com/56182049/183407007-fd54489c-4447-435b-8aa3-9807082590fa.jpg)

**Comment by jonator** [comment]
@arispech is this still an issue with the new swap page redesign? I'm not having this issue on my iPhone 13 Pro (though I don't own an Android to test with).

**Comment by arispech** [comment]
Yep, looks like this has been fixed with the new UI redesign. 
Closing this issue!
