### ISSUE TITLE
 [Testcase - Pools page] - My Pools show pools without liquidity

### ISSUE THREAD

**Issue by arispech** [osmosis-labs/osmosis-frontend#714]
The following test case is not failing. However, My pools should show only pools that users have liquidity in

https://github.com/osmosis-labs/test-management/issues/51

###Steps
1. Visit app.osmosis.zone 
2. Open the Pools page

As seen in the image below, the My pools section shows pools without liquidity (desktop and mobile)
<img width="1147" alt="image" src="https://user-images.githubusercontent.com/56182049/183415924-510edb24-9026-4441-975e-86776d0b35b1.png">

**Comment by jonator** [comment]
Have you checked if you've added liquidity but not bonded to those pools?

**Comment by arispech** [comment]
Yes, I have def not added liquidity to these pools. A couple of people reported these issues on the bug report form we created. One person points out that this seems like dust liquidity that has been added to their accounts. It's a way of showing their pools on top of the list. 

So for example this pool:
<img width="870" alt="image" src="https://user-images.githubusercontent.com/56182049/187491229-4e57ff1a-f6ee-4020-a354-e5e6c669296a.png">

has a liquidity of  `LP token balance:
0.000000000000000254 GAMM-577` 
<img width="570" alt="image" src="https://user-images.githubusercontent.com/56182049/187491300-d721045c-51f4-49c4-a8ce-5d69aa275a3b.png">


I guess people are dropping GAMM tokens to other accounts which becomes dust and makes it visible on "My pools"

**Comment by jonator** [comment]
Yeah this is a known issue. It's not a bug, but someone spammed the chain with micro amounts of shares causing people's "My Pools" views to become cluttered.

We are looking into adding a toggle to "filter dust assets and pools" once we add the new nav bar and profile page.
