### ISSUE TITLE
FakeFeeConfig logging to console

### ISSUE THREAD

**Issue by jeebster** [osmosis-labs/osmosis-frontend#72]
I noticed this recently while browsing the app; any reason the [fee primitive should be logged](https://github.com/osmosis-labs/osmosis-frontend/blob/399e3dca6feb40759faf0f6b5ce7399cd6907e16/src/hooks/tx/fake-fee-config.ts#L63)? I'm happy to open a PR removing this unless there's a specific reason to keep this

**Comment by jonator** [comment]
@daniel-farina this issue was resolved in pull #86
