### ISSUE TITLE
New display of pending transfers

### ISSUE THREAD

**Issue by jonator** [osmosis-labs/osmosis-frontend#722]
Increase user confidence by displaying pending IBC + bespoke bridge transfers front and center in the assets page.

### Key Requirements
- Once a transfer is underway, display key stats in a card at the top of the assets page
- Amount being transferred in native token
- Amount in USD
- Link to mintscan explorer
- Animated countdown of estimated time remaining
- Once the transfer is complete:
  - Overlay an animation
  - Give the user the option to close the card

![image](https://user-images.githubusercontent.com/4606373/229162521-4ce72057-cf78-4dff-ae4b-1916f1a55ceb.png)
![image](https://user-images.githubusercontent.com/4606373/229162545-1a207e6b-b82b-4888-96dd-bf3e7a0c03de.png)

### Technical Notes
* Currently, IBC and Axelar transfers are displayed the `TransferHistoryTable` [component](https://github.com/osmosis-labs/osmosis-frontend/blob/cbf31efc3ef58f6c637454eeae048dfcc91f8c9a/packages/web/components/table/transfer-history.tsx#L30) on the assets page.
  * Use this as a reference for getting the current IBC and Axelar transfers from the store
* It's ok to roughly estimate transfer times for the countdown. All of the wait times we show to the user in the transfer modal can be found by all values passed to this view component [prop](https://github.com/osmosis-labs/osmosis-frontend/blob/cbf31efc3ef58f6c637454eeae048dfcc91f8c9a/packages/web/modals/ibc-transfer.tsx#L194). For Axelar it's 15 minutes for transfers from Polygon and Ethereum (due to confirmation confidence), and 3 minutes otherwise. For IBC it's 20 seconds. May be a good idea to add some time to IBC in order to avoid the countdown sitting at 0 for too long.

**Comment by jonator** [comment]
We should look into adding a fun game while users are waiting -> http://www.sunnya97.com/osmo-runner/

**Comment by jonator** [comment]
Closing, can reopen if we pursue this idea in the redesign (stale)

**Comment by dswilson4** [comment]
@jonator Can I take on this issue?

**Comment by jonator** [comment]
Go for it!

**Comment by dswilson4** [comment]
Any suggestions for testing an IBC transfer on the testnet for an end-to-end test?  I have tokens on the osmosis testnet and am trying to do an IBC transfer, looking for IBC relayers on other testnets but not having luck: https://testnet.mintscan.io/cosmoshub-testnet/relayers

**Comment by dswilson4** [comment]
I have been using a hardcoded array of History objects following the [same type here](https://github.com/osmosis-labs/osmosis-frontend/blob/cbf31efc3ef58f6c637454eeae048dfcc91f8c9a/packages/web/components/table/transfer-history.tsx#L30:~:text=type%20History%20%3D,%7D%3B) to render and test sample data like so:

`
    const histories: History[] = [
      {
        txHash: "txHash1",
        createdAtMs: Date.now() - 3600000,
        explorerUrl: "https://explorer.example.com/tx/txHash1",
        amount: "100",
        status: "pending",
        isWithdraw: true,
      },
      {
        txHash: "txHash2",
        createdAtMs: Date.now() - 7200000,
        explorerUrl: "https://explorer.example.com/tx/txHash2",
        amount: "200",
        status: "complete",
        isWithdraw: false,
      },
      {
        txHash: "txHash3",
        createdAtMs: Date.now() - 10800000,
        explorerUrl: "https://explorer.example.com/tx/txHash3",
        amount: "300",
        status: "pending",
        isWithdraw: true,
      },
    ];  
`

**Comment by dswilson4** [comment]
Also where is the source for the osmo runner canvas component?  I'll also ask Sunny if he has it available

**Comment by jonator** [comment]
Yeah you'd have to ask sunny for that

The current histories, for IBC transfers and for Axelar transfers, can be found in these stores in the root store.
https://github.com/osmosis-labs/osmosis-frontend/blob/master/packages/web/stores/root.ts#LL66C3-L67C70

You'll import them into your component like

```
const {
      ...,
      nonIbcBridgeHistoryStore,
      ibcTransferHistoryStore,
      ...,
} = useStore();
```
