### ISSUE TITLE
[Testcase - Pools page] Add liquidity to pool's input on iphone

### ISSUE THREAD

**Issue by arispech** [osmosis-labs/osmosis-frontend#732]
The following test case is not failing. However, it is hard to see the number of the token that users try to add on ios (iPhone 13)

https://github.com/osmosis-labs/test-management/issues/26

### Steps
1. Visit app.osmosis.zone
2. Connect Wallet
3. Click the Pool page
4. Click on a particular pool
5. Click on Add / Remove liquidity button 
6. Enter the available amount (both tokens need to have an available amount)

As seen in the image below, the number of tokens is not in the center of the box
![IMG_0097](https://user-images.githubusercontent.com/56182049/184374406-4ec89195-093a-46bf-bf90-6dbc7426eae6.jpeg)
)

**Comment by jonator** [comment]
![IMG_D843755FAC59-1](https://user-images.githubusercontent.com/4606373/187319283-da5b7929-0e2c-4e48-93c0-bcc5a82069c5.jpeg)

@arispech what device? It is working on my iPhone 13 Pro. I can try a simulator of your device.

**Comment by arispech** [comment]
It is still happening on the iPhone 13 (not Pro)

**Comment by arispech** [comment]
Not sure why this still happening. First I thought it was the screen size-related issue so I tested again on the all different screen sizes as seen in the images below. And this should not be the cache issue as well, given the fact that these are tested using a simulator program so each session starts clean.

iPhone 13
<img width="354" alt="image" src="https://user-images.githubusercontent.com/56182049/188912952-72711f43-9310-40c7-aa47-9c95199daa19.png">
iPhone 13 Pro
<img width="345" alt="image" src="https://user-images.githubusercontent.com/56182049/188913930-2a6acf76-5d12-42b3-936c-62a054dc7963.png">
iPhone 13 Pro Max
<img width="353" alt="image" src="https://user-images.githubusercontent.com/56182049/188915167-50fac8fe-e7e8-4557-b43d-851678b38448.png">
iPhone 13 (Safari)
<img width="335" alt="image" src="https://user-images.githubusercontent.com/56182049/188916758-6c87b94e-be62-4efe-bb03-5ab400491b84.png">
