### ISSUE TITLE
[Testcase - Swap page] - Switch between 2 tokens selected (new Swap page)

### ISSUE THREAD

**Issue by arispech** [osmosis-labs/osmosis-frontend#738]
The following test case is not failing however when users click on the down arrow there is no action(tokens not switching). This only happens on ios (iphone)
https://github.com/osmosis-labs/test-management/issues/12

### Steps
1. Visit app.osmosis.zone
2. Using up&down arrow button to switch between 2 tokens selected

As seen in the video below, 
1. The page was refreshed
2. Clicked on the down arrow, both tokens should be switched. Instead, the down arrow changed to half up and down arrows.
3. Click away, the down arrow shows up again. And when clicked on it, the tokens are not switched.  
It requires users to click 2 times to switch between 2 tokens. 

https://user-images.githubusercontent.com/56182049/185427363-59a92263-1e8d-463c-8a17-2efbf39f844d.mov

**Comment by jonator** [comment]
@arispech what is the recommended process for closing issues once merged to stage? Do we close it when we confirm it's fixed on stage? When it is merged to master? When it is merged to stage?

**Comment by daniel-farina** [comment]
@jonator 
We can close them once we confirm it's fixed on stage.  Master should be part of a regression testing after deployment we should do once a while or for major releases. 

@arispech  will re-test and close when it passes.

**Comment by arispech** [comment]
Tested on stage and it's worked with one click 👍  Closing this issue 🍾
