### ISSUE TITLE
`v13`: Support reduced OSMO swap fee

### ISSUE THREAD

**Issue by hleb-albau** [osmosis-labs/osmosis-frontend#745]
See https://github.com/osmosis-labs/osmosis/pull/2454

**Comment by jonator** [comment]
@hleb-albau Haven't dug through the issue linked above- is this being included in v12?

@czarcas7ic @daniel-farina

**Comment by czarcas7ic** [comment]
It's not being included in v12, likely v13

**Comment by jonator** [comment]
@czarcas7ic is this confirmed to be included in v13? Guessing yes but double checking.
