### ISSUE TITLE
[Testcase - Swap page] - Set slippage tolerance not shown (Matomo events)

### ISSUE THREAD

**Issue by arispech** [osmosis-labs/osmosis-frontend#763]
SetSlippageTolerance is not shown in Matomo's action in the stage environment. 

Set slippage tolerance was performed between these actions but did not show up as seen in the image below

![image](https://user-images.githubusercontent.com/56182049/187502333-ca3437ec-bf17-4cd4-a1c4-c85634f6db2c.png)

**Comment by jonator** [comment]
Matomo is no longer in use
