### ISSUE TITLE
[Testcase - Pool page] - Next button when choose Superfluid Stake is not working on Stage

### ISSUE THREAD

**Issue by arispech** [osmosis-labs/osmosis-frontend#764]
When trying to bond liquidity to the pool and choose 14 days with Superfluid Stake the Next button as shown in the image below is not working

### Steps
1. https://stage.osmosis.zone/pool/
2. Click Start Earning
3. Pick 14 days with Superfluid Stake checked in the bottom
4. Enter the amount to bond
5. Click on the Next button

<img width="758" alt="image" src="https://user-images.githubusercontent.com/56182049/187512209-20f47424-bde0-4dda-b40d-7de83a674c0a.png">

Note:
Pick 1 day then the Bond button shows up and it's clickable ✅ 
Pick 7 days then the Bond button shows up and it's clickable ✅ 
Pick 14 days then the Bond button shows up and it's clickable  ✅ 
Pick 14 days with Superfluid Stake checked then the Next button shows up but **clicking does nothing** - not working ❌

**Comment by jonator** [comment]
😅 thanks for catching this. I accidentally trigger the wrong event instead of showing the validator modal. Fixed.

**Comment by arispech** [comment]
Tested and the Next button works ⏭️ 👍  Closing the issue!
