### ISSUE TITLE
[Testcase - Swap page] - Wrong price data for LUNC on frontier

### ISSUE THREAD

**Issue by arispech** [osmosis-labs/osmosis-frontend#767]
The current exchange rate for LUNC is too high, if you swap $1 in ATOM or anything else for LUNC, you will get like $4 in LUNC
However, if you the same amount of LUNC swap back to another token, you will get the accurate price.
### Steps
1. https://frontier.osmosis.zone/
2. Try to swap $1 of ATOM or OSMO to LUNC

<img width="455" alt="image" src="https://user-images.githubusercontent.com/56182049/188497917-451a752d-d3c2-4612-a073-b4ec600ddd55.png">
<img width="446" alt="image" src="https://user-images.githubusercontent.com/56182049/188497986-cc0ba226-6e8e-410e-871e-2b5927e7b808.png">

Swap back the same LUNC amount
<img width="460" alt="image" src="https://user-images.githubusercontent.com/56182049/188498444-8901b6f5-fe8d-42bf-b7d6-8db86c2830fa.png">

**Comment by sunnya97** [comment]
We gotta make LUNC use pool price instead of coingecko, because until Terra Classic fixes the IBC channels, LUNC and Osmosis/LUNC are not convertible

**Comment by jonator** [comment]
@JeremyParish69 could we add lunc to pool price config?
