### ISSUE TITLE
Liquidity removal issue pool 802. Calculated amount is lesser than min amount (at msg 0)

### ISSUE THREAD

**Issue by Rustyburi** [osmosis-labs/osmosis-frontend#787]
Last liquidity provider in pool 802 ATOM-stATOM cant remove his funds. He is the only one left in the pool and gets an error withdrawing. Withdrawing only 50% did not work.
Tx: https://www.mintscan.io/osmosis/txs/3EBA57060A4059923E0901C4A13B01DCFF65AC500452AE5B76DEE2BAB39B5F54

![IMAGE 2022-09-11 19:54:01](https://user-images.githubusercontent.com/113249069/189541964-094ea920-61f4-4d51-ab93-5626260f0e95.jpg)
![IMAGE 2022-09-11 19:54:16](https://user-images.githubusercontent.com/113249069/189541976-a49de0b1-4deb-40b9-92c2-284b24822a41.jpg)

**Comment by jonator** [comment]
Caused by not handling exit fee in FE calculations

**Comment by arispech** [comment]
Successfully removed funds from pool 802
<img width="1133" alt="image" src="https://user-images.githubusercontent.com/56182049/191334626-da5b09be-54c1-494a-aaa5-2608bed54b60.png">
