### ISSUE TITLE
Pool cards overflow: reduce sig figs

### ISSUE THREAD

**Issue by victortokaito** [osmosis-labs/osmosis-frontend#788]
### Problem 

Cards will begin to overflow when fees and liquidity reach 9-10 significant figures.

### Solution 
Begin abbreviating in millions to avoid overflow on cards (e.g. $170,680,543 -> $170.6M)

_ex)  large fee edgecase_
![IMG_1688](https://user-images.githubusercontent.com/39136683/189760558-68aa84b7-ec66-4314-a975-0e97a19199d6.PNG)

**Comment by jonator** [comment]
Should we do the same for the tables?

<img width="1023" alt="Screen Shot 2022-09-15 at 2 01 39 PM" src="https://user-images.githubusercontent.com/4606373/190398536-9e7b0a39-36ec-4d90-b281-706102d9e2b2.png">

**Comment by arispech** [comment]
Looks good✨
<img width="701" alt="image" src="https://user-images.githubusercontent.com/56182049/191321945-f9fa7971-47ac-49c0-adbd-ed1cf5ae0be1.png">
Closing this issue!

**Comment by victortokaito** [comment]
I think tables are fine for now. Unless they start overflowing as well, it's nice as a more detailed view. Cards are like quick call-outs that a user can dig into for more info!
