### ISSUE TITLE
User reports $0 bonded cards in My Pools

### ISSUE THREAD

**Issue by victortokaito** [osmosis-labs/osmosis-frontend#790]
### Problem
User reports receiving tiny amounts of a bunch coins

[User has $0 bonded for all these pools, but they show up in my pools anyways.](https://www.notion.so/osmosiszone/Hadley-b35e5391d15345ddb9aec8b5826ae55f)

@JeremyParish69 @jonator Have you heard similar reports? Is this related to permissionless gauges?
![image](https://user-images.githubusercontent.com/39136683/189765641-19003f8f-a2c1-44bd-8930-9feb8284189a.png)

**Comment by jonator** [comment]
Hmm. Hopefully we can solve this issue with the <1¢ settings toggle.

**Comment by victortokaito** [comment]
User doesn't remember adding to these pools either. Will keep an ear out if this is an isolated event.

**Comment by jonator** [comment]
@arispech please close if tested and working.

**Comment by victortokaito** [comment]
🫠 I didn't even know it's possible to send bonded gamm shares? or did user bond afterwards?

**Comment by jonator** [comment]
The former. Happened to many including me.

**Comment by victortokaito** [comment]
Is there more context on this issue? Did the sender use CLI for this? Can it be prevented in the future?

**Comment by jonator** [comment]
I think there was a chain upgrade to make something like this more expensive, don't remember the details.

**Comment by jonator** [comment]
Going to close this as we are going to fix it with #709 as a toggle in the new settings menu in nav bar
