### ISSUE TITLE
Open Link in New Tab : open pools in new tab

### ISSUE THREAD

**Issue by arispech** [osmosis-labs/osmosis-frontend#795]
Adding html tags to pools so users could right click and "Open link in New Tab", or command-click to open new tabs

<img width="887" alt="image" src="https://user-images.githubusercontent.com/56182049/190226643-1c5096da-eb9f-409c-bcc9-4c130c98e3de.png">

**Comment by victortokaito** [comment]
Thanks Aris. Such a good use case (I'm consistently opening new tabs). This will help users not have to backtrace as they're browsing new pool stats/consider LP'ing

**Comment by arispech** [comment]
Open many pools at the same time with a right-click to Open Link in New Tap Yay!!
<img width="569" alt="image" src="https://user-images.githubusercontent.com/56182049/191323471-366e5794-e2b6-4a15-93c3-5172a032d17f.png">
