### ISSUE TITLE
Mobile: close menu drawer on menu item selection.

### ISSUE THREAD

**Issue by jonator** [osmosis-labs/osmosis-frontend#80]
## Problem
It's quite annoying to have to tap away from the menu after making a selection in the menu. It's one extra tap that isn't needed.

## Proposed Solution
We should automatically close the menu when someone makes a menu selection on mobile.

**Comment by Thunnini** [comment]
We are currently aware of this issue and it has been resolved in the `fix-mobile-view` branch. It will be deployed soon.
