### ISSUE TITLE
Allow to withdraw EVMOS asset using Ethereum address

### ISSUE THREAD

**Issue by arispech** [osmosis-labs/osmosis-frontend#804]
## Current Method
Currently, users can withdraw EVMOS by doing and IBC transfer at https://app.evmos.org/transfer

On this page they will  get their `0x` address and `EVMOS` address after conencting  Metamask. 

<img width="450" alt="image" src="https://user-images.githubusercontent.com/56182049/190650017-4bf6783b-b0a2-4fe3-886a-c36f006389e2.png">

## New method
https://osmosis-frontend-git-fork-disperze-master-osmo-labs.vercel.app/assets
Now we will allow users to withdraw directy from Osmosis, however the address  is incorrect. 

# Solution
Allow to withdraw EVMOS asset using the Ox address and convert it to the right evmos address. 

Original discussion from thia PR: 
https://github.com/osmosis-labs/osmosis-frontend/pull/780

**Comment by jonator** [comment]
Removing as stale
