### ISSUE TITLE
Osmosis Info - Click on "Top Movers" tokens 

### ISSUE THREAD

**Issue by Traumz** [osmosis-labs/osmosis-frontend#806]
Adding the possibility to click on each tokens in the "Top Movers" scrolling menu, in order to arrive on its chart

![image](https://user-images.githubusercontent.com/98484053/190924675-10856343-a7b9-413e-96b9-1bbc3e415690.png)

**Comment by Loa212** [comment]
Are you referring to [info.osmosis.zone](https://info.osmosis.zone/) ? if so, you should post this on [this repo](https://github.com/osmosis-labs/osmosis-info).
