### ISSUE TITLE
Add user analytics events to use on Amplitude

### ISSUE THREAD

**Issue by victortokaito** [osmosis-labs/osmosis-frontend#814]
https://github.com/osmosis-labs/osmosis-frontend/commit/76cb6161605329b998ebf45116ec1b397688d8e6

* seems clicking both the "Global Withdraw" and "Global Deposit" at the top actually triggers `Assets: Deposit clicked` . Is it possible to split this up between deposit/withdraw?
<img width="1405" alt="Screen Shot 2022-09-20 at 12 53 43 PM" src="https://user-images.githubusercontent.com/39136683/191351908-16a89b8f-0cde-43f5-a9ba-ab608eed9e12.png">

<img width="1728" alt="Screen Shot 2022-09-20 at 12 52 33 PM" src="https://user-images.githubusercontent.com/39136683/191352002-d51ec8ca-50e8-4683-8ddc-620d6ef5e398.png">

* requested tag: Deposit completed (both IBC and non-IBC assets)
– we currently have `Deposit IBC asset: deposit completed` , but we don't yet have this tag for non-IBC assets
– want to distinguish between `Deposit started` and `Deposit completed` and track all events where user actually clicks confirm.
– no need to query if asset actually went through, just want to know if user completed the user flow.

![image](https://user-images.githubusercontent.com/39136683/191352494-f60a1c42-af6b-4584-88ae-151efae510e5.png)
![image](https://user-images.githubusercontent.com/39136683/191352517-508041f7-75b4-4ec0-bd4b-92423dcbf1ae.png)

**Comment by delivan** [comment]
@victortokaito First thing you issued will be fixed. Thanks!
Second thing is already fixed. We currently have `Deposit asset: Deposit started` event for IBC and non-IBC assets(we can distinguish by setting event property `bridge`)

**Comment by victortokaito** [comment]
Beautiful! Thank you Delivan. I'll try it out.

**Comment by victortokaito** [comment]
<img width="966" alt="image" src="https://user-images.githubusercontent.com/39136683/191565215-bc0f1590-f717-4845-a58a-190e159569f1.png">

Is this event not implemented because difficulty with confirming successful completion of axelar transaction?

**Comment by jonator** [comment]
We may be able to use a useEffect hook in the assets page to detect when a transfer has completed via the NonIbcBridgeTransfer history store.

**Comment by delivan** [comment]
@victortokaito The event is implemented. You can see it on Amplitude. (but now reverted temporarily because of some issues)
<img width="1384" alt="스크린샷 2022-09-22 오후 2 53 46" src="https://user-images.githubusercontent.com/32129022/191669077-1a4b6cfe-315e-4ab3-a6df-8db02be9cbc8.png">
