### ISSUE TITLE
Adding Liquidity: input amount resets

### ISSUE THREAD

**Issue by victortokaito** [osmosis-labs/osmosis-frontend#816]
### Problem
Adding liquidity in the "traditional LP" method (bringing a proper distribution of assets manually rather than through "auto swap") resets the input amount for the asset pair.

https://user-images.githubusercontent.com/39136683/191373396-cf47c759-78cd-42f1-8975-49b9b8165e2a.mov

Side Note: 
* Setting "max" works. 
* I'm testing whether the event tracking works. If we end up seeing very little % of users using "traditional LP", it could be because a bug forces users to auto swap single asset when the traditional LP method doesn't work.

**Comment by jonator** [comment]
Redesigning this workflow
