### ISSUE TITLE
Metamask launches every time you navigate to the Assets

### ISSUE THREAD

**Issue by arispech** [osmosis-labs/osmosis-frontend#842]
Metamask launches every time you navigate to the Assets page on the frontier after interacting with withdrawals or deposits of USDC. 

Steps :
1. Interact with withdrawals or deposits of USDC on the frontier and sign into Metamask, allowing your MM address to populate.
2. Close the browser completely
3. Reopen the browser and navigate to the assets page on the frontier. Every time you do Step 3 moving forward, Metamask will pop up requesting to sign in.

**Comment by jonator** [comment]
This is similar to how Keplr works. If you open a site with a connection after closing the browser completely, it has to ask for your password in order to decrypt your private key and enable proper function with the Dapp.

**Comment by jonator** [comment]
That's true. Though we can't control what Metamask does from our app. What we could do is try to disconnect Metamask after each transfer, but then the user would have to approve Metamask again each time they want to do another transfer. We already do the best we can by attempting to disconnect all other wallets if they connect a different wallet.

**Comment by arispech** [comment]
Sounds good! I will go ahead and close this issue for now. I'm pretty sure we do the best we can to handle all other wallets connection🙌
