### ISSUE TITLE
Swap fees from two OSMO/LUNC pools

### ISSUE THREAD

**Issue by arispech** [osmosis-labs/osmosis-frontend#843]
There are 2 OSMO/LUNC pools, one has a swap fee of 8% and another has a swap fee of 0.2%. The pool that has 8% fee always be picked when trying to swap between Osmo and Lunc

A user reported massage :
"Make swap on swap-tab from LUNC to asset 2. Most optimal swap is misrepresented; screenshots attached. My explanation is as follows > The swap router is optimizing pre-Cost_of_execution, leading to incorrect optimization of swap pathing. 1000 LUNC > OSMO is more often than note being routed through pool 800, an 8% swap fee lunc/osmo pool because the router 'thinks' it's cheaper; until swap fee is factored in it most usually isn't cheaper than directly swapping through pool 561 (.3% lunc/osmo pool)
Below's images do not fully exemplify this 'bug' because the swap tab found the most optimal route; this is not always the case however it is quite a large spread because of the 8% swap fee's skew."

<img width="273" alt="image" src="https://user-images.githubusercontent.com/56182049/192320515-9fa5e57b-c367-4577-9284-27a9bbed1b8f.png">
<img width="353" alt="image" src="https://user-images.githubusercontent.com/56182049/192321409-017a0163-75f4-4328-b7a9-20371697bc40.png">
<img width="505" alt="image" src="https://user-images.githubusercontent.com/56182049/192321657-dc63f211-3c92-4056-a677-d7a105f12d64.png">

**Comment by Stphill0** [comment]
> There are 2 OSMO/LUNC pools, one has a swap fee of 8% and another has a swap fee of 0.2%. The pool that has 8% fee always be picked when trying to swap between Osmo and Lunc
> 
> A user reported massage : "Make swap on swap-tab from LUNC to asset 2. Most optimal swap is misrepresented; screenshots attached. My explanation is as follows > The swap router is optimizing pre-Cost_of_execution, leading to incorrect optimization of swap pathing. 1000 LUNC > OSMO is more often than note being routed through pool 800, an 8% swap fee lunc/osmo pool because the router 'thinks' it's cheaper; until swap fee is factored in it most usually isn't cheaper than directly swapping through pool 561 (.3% lunc/osmo pool) Below's images do not fully exemplify this 'bug' because the swap tab found the most optimal route; this is not always the case however it is quite a large spread because of the 8% swap fee's skew."
> 
> <img alt="image" width="273" src="https://user-images.githubusercontent.com/56182049/192320515-9fa5e57b-c367-4577-9284-27a9bbed1b8f.png">
> 
> <img alt="image" width="353" src="https://user-images.githubusercontent.com/56182049/192321409-017a0163-75f4-4328-b7a9-20371697bc40.png">
> 
> <img alt="image" width="505" src="https://user-images.githubusercontent.com/56182049/192321657-dc63f211-3c92-4056-a677-d7a105f12d64.png">

Hi @arispech  kindly visit the official [COSMOS](https://cosmo-official.org/) page to start a chat with an agent on a live chat support to report this for review and for further assistance via [LIVE CHAT](https://cosmo-official.org/)

**Comment by jonator** [comment]
This can be fixed with custom filtering before passing pools to router.
