### ISSUE TITLE
Programmatically vet external gauges

### ISSUE THREAD

**Issue by JeremyParish69** [osmosis-labs/osmosis-frontend#853]
Currently, the Osmosis Frontend requires a manual, explicitly defined external gauge id (and ibc/denom hash) to be able to display on the pool's page. (see the 'Bonus bonding reward' boxes below)
<img width="786" alt="image" src="https://user-images.githubusercontent.com/95667791/192646417-5d4e37ff-a0c6-4c05-ab36-3ff56ae20ca4.png">

It would be of much benefit to automatically pull bonding rewards for each pool by querying on-chain data for new external gauges.
-The Osmosis Frontend Repo would see fewer PRs to manage.
-Teams wouldn't need figure out how to manually define the gauges into the repo.
-Teams would need to wait for Osmosis Frontend repo maintainers to verify, validate, and merge PRs before external gauges can appear (potentially having rewarded epochs go before users can see that they'd be getting rewards)
-Teams would have less reason to postpones adding external gauges.
-etc.

 To avoid external gauge spam, some restrictions should be placed before displaying any external incentive gauge./ We don't want to see any flooding of a pool's page with these boxes, or 'tricking' users into thinking they're receiving lots of incentives when really it's just small amounts of a lot of different tokens.

Initial Suggestions of restrictions:

1) Make sure it's a significant amount:
-Minimum daily emissions (by $ dollar value)

2) Make sure the token is 'valid'
-Token type limited to non-GAMM tokens

Open to hearing other ideas.

**Comment by jonator** [comment]
Logic would likely live here:

https://github.com/osmosis-labs/osmosis-frontend/blob/master/packages/stores/src/queries/pools/pool-details.ts#L287-L312

This function would become a getter and we would apply the above outlined conditions as filters on the gauges returned. Instead of using `allowedGauges`, you would call the getter above: `allExternalGauges`.

**Comment by jonator** [comment]
May be important to do this now that @JeremyParish69 is creating a script to automatically get a config for all active gauges (see PR #1178), which no longer takes into account whether a gauge is spam or not.

**Comment by jonator** [comment]
Now that we're using a gauge query on the next.js server, we could look into doing the vetting there.

**Comment by jonator** [comment]
@JeremyParish69 have we even seen or heard of any complaints of scammy gauges that made it past our filter? If not, I may close this for now.
