### ISSUE TITLE
Incorrect link pointed to install MetaMask on mobile versions

### ISSUE THREAD

**Issue by arispech** [osmosis-labs/osmosis-frontend#883]
Deposit or withdraw USDC - when choosing Metamark and clicking install MetaMark, the link points to install MetaMark for chrome desktop instead of Google Play or App Store to download the app 

<img width="400" alt="image" src="https://user-images.githubusercontent.com/56182049/194340135-e6037011-cf5d-4c20-b3a0-b2f2e55d678f.png">

on android shows 👇🏼

<img width="400" alt="image" src="https://user-images.githubusercontent.com/56182049/194338337-86897ae6-b190-4a33-b317-f4e55663d2c3.png">

on android shows 👇🏼

<img width="400" alt="image" src="https://user-images.githubusercontent.com/56182049/194344732-3a3c365b-4b41-44cf-a8d9-15ed9c2b8ff9.png">

**Comment by jonator** [comment]
Currently we don't support Metamask on mobile

I need to fix it so it's not selectable on mobile
