### ISSUE TITLE
Edit ETH address: withdraw using the native Axelar integration

### ISSUE THREAD

**Issue by victortokaito** [osmosis-labs/osmosis-frontend#892]
### Context
When withdrawing using the native Axelar integration, the transfer modal currently supports switching wallet extensions.
<img width="513" alt="Screen Shot 2022-10-10 at 10 24 56 AM" src="https://user-images.githubusercontent.com/39136683/194921699-72b2e2bd-0646-43a5-9aa0-db359c77b15b.png">

Instead/in addition we can support `edit to any address` as we do for `Withdraw IBC asset`.

<img width="414" alt="Screen Shot 2022-10-10 at 10 23 07 AM" src="https://user-images.githubusercontent.com/39136683/194921411-b95ffad3-b517-423e-81a6-9f4803bd1897.png">

### Possible solution
`Withdraw` supports edit to any ethereum address. `Deposit` still allows switching between ethereum wallets 
<img width="1086" alt="Screen Shot 2022-10-10 at 10 28 20 AM" src="https://user-images.githubusercontent.com/39136683/194922224-aef48f36-b833-43ba-99c3-89e23e110cfd.png">

### Tradeoffs, drawbacks, and suggested alternative
However, there is a UX drawback to this solution. Novice users likely only want to withdraw to wallet addresses they have access to through wallet extensions. Supporting an `edit` feature exposes them to accidentally entering incorrect addresses, possibly losing their funds. 

* If an advanced user's only goal is to connect and withdraw to a non-MM wallet extension, it's possible this issue will be resolved by the addition of `web3modal`.
* If advanced users seek to withdraw assets to specific addresses, it may be optimal to protect novice users and have those advanced users send to specific addresses from their respective wallets post-withdraw from Osmosis (trade-off: gas costs, UX for advanced users).
* If Osmosis were to add more wallet-like capabilities, as @jonator mentioned, this could be sectioned off into a send/receive feature.

**Comment by jonator** [comment]
Note: we already support users switching multiple accounts within MetaMask

**Comment by jonator** [comment]
Note: this requires regeneration of Axelar deposit address. We may want to user a less dynamic UI because of this.

**Comment by jonator** [comment]
It's not a big deal to generate new deposit addresses, it just takes time. According to Axelar.
