### ISSUE TITLE
New amplitude events

### ISSUE THREAD

**Issue by jonator** [osmosis-labs/osmosis-frontend#894]
Work with @victortokaito and @delivan on adding new amplitude events.

**Comment by victortokaito** [comment]
### Readme
For an [in-depth look at Amplitude events](https://www.notion.so/osmosiszone/0c2e22f48c7e4bc19e9f4ba5f8323b35?v=34a0541dba434d06a7a24c1811f0caf8) (including description, property tags, change notes). Check out "Key changes". Add filters to table view as needed. We should discuss and decide together on some of the nuances (see change notes) in the notion doc.

### In amplitude, waiting to be added
- [ ] Pool detail: Remove liquidity completed
- [ ] Pool detail: Add liquidity completed
- [ ] Topnav: Connect wallet clicked
- [ ] Topnav: Sign out clicked
- [ ] Pool detail: Unbond shares clicked
- [ ] Pool detail: Card details expanded
- [ ] Assets: Buy Osmo clicked
- [ ] Pool detail: Remove liquidity started
- [ ] Pool detail: Add liquidity started
- [ ] Pool detail: Superfluid stake completed
- [ ] Pool detail: Go Superfluid clicked
- [ ] Pool detail: Earn more by bonding clicked
- [ ] Pool detail: Superfluid stake started
- [ ] Pool detail: Bonding completed
- [ ] Pool detail: Bonding started

### Set to inactive in amplitude, need to be removed
- [ ] Sidebar: Discord clicked
- [ ] Sidebar: Telegram clicked
- [ ] Sidebar: Connect wallet clicked
- [ ] Sidebar: Twitter clicked
- [ ] Sidebar: Sign out clicked
- [ ] Sidebar: Medium clicked
- [ ] Sidebar: Commonwealth clicked
- [ ] Pool detail: Add/Remove liquidity clicked
- [ ] Pool detail: Unbond

**Comment by jonator** [comment]
Note: in Amplitude the Redesign branch will be moved to master branch once we deploy these changes.
