### ISSUE TITLE
IBC scrollbars

### ISSUE THREAD

**Issue by chmichael** [osmosis-labs/osmosis-frontend#90]
Hello,
  Is it possible to remove these scrollbars ? Or replace them with something more modern ?
  
  Thank you

![Osmosis-IBC](https://user-images.githubusercontent.com/13120950/141871715-1cefda42-32f9-46f0-b954-2f6a5b86f32e.jpg)
u

**Comment by daniel-farina** [comment]
@chmichael 

Could you please share your OS & Browser version? 

Thanks

**Comment by chmichael** [comment]
Windows 11 & latest Chrome

**Comment by Thunnini** [comment]
Thanks for your suggestion. In fact, since we are not developing in a Windows environment, this is a part I accidentally missed. I fixed it.

**Comment by chmichael** [comment]
After a couple of the fix the horizontal scrollbar re-appeared!
