### ISSUE TITLE
Rounded decimals breaks EVMOS withdrawal

### ISSUE THREAD

**Issue by jasbanza** [osmosis-labs/osmosis-frontend#909]
As per a user, when clicking "MAX withdrawal" for $EVMOS, the following error occurs. 

https://www.mintscan.io/osmosis/txs/5C57B24F13E6177597421514C574612565D1A03C757AD815679F0C2F661F5F1A
<img width="829" alt="image" src="https://user-images.githubusercontent.com/1925470/196477145-81dcfa64-10ec-4fcc-96f1-4d874af4e0da.png">

This should be prevented before msg broadcast - perhaps check to pass all decimal points (or at the very least rounded down instead of up?) 

Since the error message coming back from the chain is a bit vague to a non-technical user, they kept trying and wasted gas unnecessarily.

**Comment by jonator** [comment]
Errors should be clarified in #1069
