### ISSUE TITLE
Add Relayer status!

### ISSUE THREAD

**Issue by chmichael** [osmosis-labs/osmosis-frontend#91]
Hello,
  Could you please add the relayer status when you try to deposit/withdraw in order to avoid doing that when the relayer is down or has a malfunction ? (or even better disable it the buttons)

Currently i can find this info on Osmosis Discord  #ibc-status

Thank you

**Comment by ValarDragon** [comment]
This is a really good idea! May need some reconfiguring of the IBC bot, to let servers poll whats going on with different IBC statuses'

**Comment by chmichael** [comment]
Also disable Withdraw button if IBC malfunction is detected to avoid SPAM!

![ibc-wihdraw-info](https://user-images.githubusercontent.com/13120950/157097076-cea11c73-606f-401f-a5f2-ce54ee7e79b6.jpg)

**Comment by jonator** [comment]
This functionality is implemented in: https://info.osmosis.zone/ibc.

**Comment by chmichael** [comment]
Take a look a Juno's halt today!
Users should know if the Relayer is working or not that's why i insist put the Relayer status on the Deposit/Withdrawn IBC Assest window!
Most of the users will not go to the https://info.osmosis.zone/ibc to check if the relayer or chain is working! 
They will just do the deposit and/or withdraw!

![juno-halt](https://user-images.githubusercontent.com/13120950/161769495-12114c6a-2cfc-4f28-ba18-ab3c4a4e63f1.jpg)

Relayer status on the Deposit/Withdrawn IBC Assest window and Disabling the "Deposit/Withdraw" buttons is the solution to this!

Thank you

**Comment by jonator** [comment]
5/10 FE product meeting - looking into adding simple status indicator in IBC transfer dialog. Would perhaps be good to investigate there being a cosmos public API for getting IBC relayer status.

**Comment by jonator** [comment]
August update - given new IBC transfer animation, we could look into incorporating relayer status somewhere in/over the animation

<img width="688" alt="Screen Shot 2022-08-24 at 9 17 56 AM" src="https://user-images.githubusercontent.com/4606373/186442252-b02ac9d7-4918-4c63-b0cb-7017cc726ba5.png">

**Comment by jonator** [comment]
@victortokaito could we add/find and link any Figma designs?

Screenshots would be good too, as this is a "good first issue"

**Comment by jonator** [comment]
Actually, closing in favor of #789
