### ISSUE TITLE
Update localizations to new copy, add Korean

### ISSUE THREAD

**Issue by jonator** [osmosis-labs/osmosis-frontend#919]
- [x] @DLatouche update FR (will get you a diff of what changed since your PR, mostly on pool detail page)
- [x] @dogemos or @delivan  add/delegate KR

**Comment by gnujoow** [comment]
@jonator
I've checked the pr but I couldn't find the JSON file related to the Korean translation. If it's not going on yet, can I contribute about translation?

**Comment by jonator** [comment]
@gnujoow Will be adding Korean
