### ISSUE TITLE
Bridge Integration: auto-wrap native assets

### ISSUE THREAD

**Issue by jonator** [osmosis-labs/osmosis-frontend#920]
### Background
WETH is simply an ERC20 1:1 version of native ETH, which is treated differently on Ethereum. It allows products that depend on the ERC20 standard to work with ETH as well. In this case, the product is Axelar’s gateway contract. It is somewhat a pitfall of the EVM design.

### Proposed solution 
For our WETH integration, we should support the option for users to deposit native ETH.

Since Axelar is adding [support](https://osmosis-network.slack.com/archives/C028SRRL4LX/p1666405744118759) themselves, we'd just need to update our querying and add UI to let the user switch to ETH from WETH. Then we'd send Eth to the generated address, instead of an ERC20 transfer.

**Comment by jonator** [comment]
[Slack thread](https://osmosis-network.slack.com/archives/C028SRRL4LX/p1666405744118759)

**Comment by jonator** [comment]
Update 11/3: changed name, since this applies to BNB->WBNB as well.

**Comment by Cordtus** [comment]
WDOT, WGLMR, WMATIC also. Auto-unwrap for all native/fee tokens on other networks is a nice feature.

**Comment by jonator** [comment]
Update: Axelar should have this ready by Jan 16
