### ISSUE TITLE
Pools show different incentives APR

### ISSUE THREAD

**Issue by arispech** [osmosis-labs/osmosis-frontend#923]
Steps:
1. https://app.osmosis.zone/pools
2. Go to pool 604 and pool 611
3. Click Start Earning button

As seen on images below pool 604 : STARS / OSMO and pool 611 : ATOM / STARS showed different incentives APR when click Start Earning button

<img width="982" alt="image" src="https://user-images.githubusercontent.com/56182049/197846486-37eb2651-e32c-4b25-aad8-494c9adceee1.png">

![image](https://user-images.githubusercontent.com/56182049/197847156-80c4afe3-6515-48fa-9b6a-cd70c3e9d777.png)

**Comment by jonator** [comment]
Ah yes this is the work @srph did. The difference comes from adding the external incentives only to the view in the background.

**Comment by jonator** [comment]
I think I'm going to close this not to be completed since we're releasing the redesign soon.

I've double checked that we account for this in the redesign.
