### ISSUE TITLE
Remove general table component

### ISSUE THREAD

**Issue by jonator** [osmosis-labs/osmosis-frontend#970]
### Problem
I tried to make future dev easier by adding a general [table component](https://github.com/osmosis-labs/osmosis-frontend/blob/master/packages/web/components/table/index.tsx), but I think this was a mistake. Not only is it hard to understand for new devs, it barely saves on reusability and has terrible performance. The mechanism uses react components to render custom individual cells, which creates a lot of overhead. The entire table could easily be one component. In addition, as seen with the pools page, it is difficult to properly memoize the table data.

### Proposed Solution
Wherever we use a table, we should just construct the table manually in that component where the data is processed. Instead instantiating individual components for each cell, we can simply re-render the entire visible table in a single component.

**Comment by JoseRFelix** [comment]
@jonator @sehyunc Perhaps instead of maintaining a table component ourselves, we could rely on [React Table](https://tanstack.com/table/v8) (now called TanStack table). It handles accessibility, and all the other features we need. It's tried, tested, and trusted by the react community

It also includes pagination with virtualization which helps with our rendering performance issue on the pool page

**Comment by sehyunc** [comment]
> @jonator @sehyunc Perhaps instead of maintaining a table component ourselves, we could rely on [React Table](https://tanstack.com/table/v8) (now called TanStack table). It handles accessibility, and all the other features we need. It's tried, tested, and trusted by the react community
> 
> 
> 
> It also includes pagination with virtualization which helps with our rendering performance issue on the pools page 
> 
> 
> 
>  

Huge fan of TanStack so definitely will look into this library and try to implement it, thanks for the suggestion!

**Comment by jonator** [comment]
Work on pools tables blocked until we update to new pools page (#1175)

**Comment by jonator** [comment]
Not worth focusing on for now
