### ISSUE TITLE
Hotfixes

### ISSUE THREAD

**Issue by jonator** [osmosis-labs/osmosis-frontend#984]
- [x] Bonding section caption is inline with title
- [x] Double check APRs in pools tables and pool cards
- [x] Show bonding durations with positive bonded balances.
- [x] Deposit withdraw buttons broken when navigating to assets page
- [x] Display balances in tokenselect modal, improve search bar
- [x] Show num days left by external incentives
- [x] Fix deposit direction in transfer history table

**Comment by ValarDragon** [comment]
The default slippage tolerance is 1% right now, this seems quite high / higher than what it used to be

**Comment by arispech** [comment]
Bug on deposit screen

<img width="300" alt="image" src="https://user-images.githubusercontent.com/56182049/200909101-f66e6322-48a2-4427-9391-57e1ebc72967.png">

**Comment by syed8rahman** [comment]
Unselected colors on side nav are from old guidelines it seems. 
<img width="183" alt="Screen Shot 2022-11-09 at 9 18 35 PM" src="https://user-images.githubusercontent.com/22246254/200909691-71c748e6-41ed-449a-9f2d-f31529ad358c.png">

Figma
<img width="275" alt="Screen Shot 2022-11-09 at 9 19 46 PM" src="https://user-images.githubusercontent.com/22246254/200909946-759e29c4-5784-487a-83f7-bbf99ce56ed8.png">

**Comment by syed8rahman** [comment]
<img width="107" alt="Screen Shot 2022-11-09 at 9 24 09 PM" src="https://user-images.githubusercontent.com/22246254/200910840-9449559b-a666-4685-87f4-6486675c2ce2.png">
Hover state is using incorrect color for the icon. Should be 
<img width="136" alt="Screen Shot 2022-11-09 at 9 24 27 PM" src="https://user-images.githubusercontent.com/22246254/200910909-16c491d9-d69d-45ed-92d0-78e9c327032a.png">

**Comment by jonator** [comment]
> It also takes a ton of time for the Transak modal to pop up after clicking "Buy" - leaves a user stuck in limbo for a while. Is this something we should address with design?

Oh shoot the transak modal should have been disabled

**Comment by syed8rahman** [comment]
<img width="654" alt="Screen Shot 2022-11-09 at 9 26 48 PM" src="https://user-images.githubusercontent.com/22246254/200911342-7e26cfbd-e886-4060-90f1-a616397af595.png">

This warning dialogue isn't referencing the right colors.

**Comment by arispech** [comment]
A user report : https://frontier.osmosis.zone/pool/832
Unbonding not shown "If you bond via CLI and choose a duration which is more than the max specified in the pool frontend, its not shown. I bonded for 14 days in the JKL pool via CLI, but max bond duration is 7 days. Old frontend showed my unbondings, new frontend doesn't."

**Comment by syed8rahman** [comment]
<img width="739" alt="Screen Shot 2022-11-09 at 9 31 12 PM" src="https://user-images.githubusercontent.com/22246254/200912177-8141e890-ad20-42a2-b95a-7ddfee5e7069.png">
It looks like a couple of things are off with the single asset modal. 
1. padding within the asset select. 
2. Let's move the arrow up to be aligned wit hthe token name
3. Is internal padding the same as the figma below? 
4. Just double checking the toggle button height - seems a bit tall.

<img width="820" alt="Screen Shot 2022-11-09 at 9 30 22 PM" src="https://user-images.githubusercontent.com/22246254/200912012-9aad66b5-1a40-4372-a5cd-3a8cbf54cbda.png">

**Comment by arispech** [comment]
- [ ] A user report: https://app.osmosis.zone/assets

Withdraw button next to asset not working "When attempting to withdraw stargaze, the button next to the stargaze asset doesn't do anything on Brave. I needed to go through the withdraw steps at the top of the page."

Note: this works fine on other browsers

**Comment by arispech** [comment]
- [ ] Bonded tokens disappear from the UI. 

In this example, there were 10 tokens that were unbonding and once the unbonding completed, they did not show up. 

<img width="800" alt="image" src="https://user-images.githubusercontent.com/56182049/200917331-a25686ce-9c36-4825-88d2-530564786f06.png">


<img width="800" alt="Screen Shot 2022-11-09 at 1 08 48 PM" src="https://user-images.githubusercontent.com/56182049/200915225-13aae299-8033-47c0-90e4-6f6dbe9daa6d.png">


## 30 minutes later after unbond
<img width="1417" alt="image" src="https://user-images.githubusercontent.com/56182049/200917994-33e9c439-777e-4b5b-89c6-bd03ea49a136.png">

![image](https://user-images.githubusercontent.com/56182049/200918287-c1d6976b-3d75-43d4-80c7-44436f9af2b0.png)

**Comment by jonator** [comment]
> Unselected colors on side nav are from old guidelines it seems. <img alt="Screen Shot 2022-11-09 at 9 18 35 PM" width="183" src="https://user-images.githubusercontent.com/22246254/200909691-71c748e6-41ed-449a-9f2d-f31529ad358c.png">
> 
> Figma <img alt="Screen Shot 2022-11-09 at 9 19 46 PM" width="275" src="https://user-images.githubusercontent.com/22246254/200909946-759e29c4-5784-487a-83f7-bbf99ce56ed8.png">

Could we change this to what I have in the app in figma? I do this to avoid loading different icons for selected and deselected. (I have yet to figure out how to change the color of icons programatically)

**Comment by victortokaito** [comment]
### On the swap UI
* User has to first click into the search box to start typing.
* Search box is only clickable within the area highlighted in red.

Observed user behavior: user clicks around multiple times, perceiving this to be lag/unresponsiveness.

### Proposed solution
* The input field should be automatically selected (upon clicking the dropdown, before user click as seen [here](https://legacy.osmosis.zone/)). 
* The input field's clickable area's width is not matching its parent. It's listening to click event, only up to the width of its placeholder. [Its width should be width:100%.](https://github.com/osmosis-labs/osmosis-frontend/issues/991) 


![image](https://user-images.githubusercontent.com/39136683/201365016-aa0a95e8-f95e-4ff4-994d-4ca1c09d94e3.png)

**Comment by jonator** [comment]
@victortokaito that has been updated

**Comment by victortokaito** [comment]
Can the input field also be automatically focused? (upon clicking the dropdown–without a user click being necessary)
